-- Schema-only fixture captured 2026-09-14; auth claim source is local-test only.
create role anon; create role authenticated;
create schema auth; create schema private;
create table auth.users(id uuid primary key,email_confirmed_at timestamptz,is_anonymous boolean default false);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.user_id',true),'')::uuid $$;
create function private.is_verified_permanent_user() returns boolean language sql stable security definer set search_path='pg_catalog','auth' as $$ select exists(select 1 from auth.users u where u.id=auth.uid() and u.email_confirmed_at is not null and coalesce(u.is_anonymous,false)=false) $$;
grant usage on schema auth,private,public to authenticated,anon;
create table public.bikes (
"id" uuid default gen_random_uuid() not null,
"user_id" uuid not null,
"name" text not null,
"year" text,
"make" text,
"model" text,
"odometer" numeric default 0,
"notes" text,
"created_at" timestamptz default now() not null,
"updated_at" timestamptz default now() not null,
"image_url" text,
"gps_odometer_miles" numeric default 0 not null,
"rides_since_odometer_confirm" int4 default 0 not null,
"odometer_last_confirmed_at" timestamptz,
constraint "bikes_pkey" PRIMARY KEY (id),
constraint "bikes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
alter table public.bikes enable row level security;
create table public.ride_sessions (
"id" uuid default gen_random_uuid() not null,
"user_id" uuid not null,
"bike_id" uuid,
"bike_name" text not null,
"started_at" timestamptz default now() not null,
"ended_at" timestamptz,
"duration_seconds" int4 default 0 not null,
"distance_miles" numeric default 0 not null,
"max_speed_mph" numeric default 0 not null,
"average_speed_mph" numeric default 0 not null,
"max_accel_g" numeric default 0 not null,
"max_brake_g" numeric default 0 not null,
"max_lean_deg" numeric default 0 not null,
"start_lat" float8,
"start_lng" float8,
"end_lat" float8,
"end_lng" float8,
"notes" text,
"status" text default 'recording'::text not null,
"created_at" timestamptz default now() not null,
"updated_at" timestamptz default now() not null,
constraint "ride_sessions_bike_id_fkey" FOREIGN KEY (bike_id) REFERENCES bikes(id) ON DELETE SET NULL,
constraint "ride_sessions_pkey" PRIMARY KEY (id),
constraint "ride_sessions_status_check" CHECK ((status = ANY (ARRAY['recording'::text, 'complete'::text, 'cancelled'::text]))),
constraint "ride_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
alter table public.ride_sessions enable row level security;
create table public.ride_samples (
"id" int8 generated by default as identity not null,
"session_id" uuid not null,
"user_id" uuid not null,
"recorded_at" timestamptz default now() not null,
"latitude" float8,
"longitude" float8,
"altitude_m" float8,
"accuracy_m" float8,
"speed_mps" float8,
"heading_deg" float8,
"accel_x" float8,
"accel_y" float8,
"accel_z" float8,
"accel_g" float8,
"rotation_alpha" float8,
"rotation_beta" float8,
"rotation_gamma" float8,
"lean_deg" float8,
"pitch_deg" float8,
"roll_deg" float8,
constraint "ride_samples_pkey" PRIMARY KEY (id),
constraint "ride_samples_session_id_fkey" FOREIGN KEY (session_id) REFERENCES ride_sessions(id) ON DELETE CASCADE,
constraint "ride_samples_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
alter table public.ride_samples enable row level security;
create policy "Users manage own bikes" on public.bikes as PERMISSIVE for ALL to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "verified_permanent_accounts_only" on public.bikes as RESTRICTIVE for ALL to authenticated using (private.is_verified_permanent_user()) with check (private.is_verified_permanent_user());
create policy "verified_permanent_accounts_only" on public.ride_samples as RESTRICTIVE for ALL to authenticated using (private.is_verified_permanent_user()) with check (private.is_verified_permanent_user());
create policy "Users manage own ride samples" on public.ride_samples as PERMISSIVE for ALL to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "verified_permanent_accounts_only" on public.ride_sessions as RESTRICTIVE for ALL to authenticated using (private.is_verified_permanent_user()) with check (private.is_verified_permanent_user());
create policy "Users manage own ride sessions" on public.ride_sessions as PERMISSIVE for ALL to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
grant INSERT on public.bikes to anon;
grant SELECT on public.bikes to anon;
grant UPDATE on public.bikes to anon;
grant DELETE on public.bikes to anon;
grant TRUNCATE on public.bikes to anon;
grant REFERENCES on public.bikes to anon;
grant TRIGGER on public.bikes to anon;
grant INSERT on public.bikes to authenticated;
grant SELECT on public.bikes to authenticated;
grant UPDATE on public.bikes to authenticated;
grant DELETE on public.bikes to authenticated;
grant TRUNCATE on public.bikes to authenticated;
grant REFERENCES on public.bikes to authenticated;
grant TRIGGER on public.bikes to authenticated;
grant INSERT on public.ride_sessions to anon;
grant SELECT on public.ride_sessions to anon;
grant UPDATE on public.ride_sessions to anon;
grant DELETE on public.ride_sessions to anon;
grant TRUNCATE on public.ride_sessions to anon;
grant REFERENCES on public.ride_sessions to anon;
grant TRIGGER on public.ride_sessions to anon;
grant INSERT on public.ride_sessions to authenticated;
grant SELECT on public.ride_sessions to authenticated;
grant UPDATE on public.ride_sessions to authenticated;
grant DELETE on public.ride_sessions to authenticated;
grant TRUNCATE on public.ride_sessions to authenticated;
grant REFERENCES on public.ride_sessions to authenticated;
grant TRIGGER on public.ride_sessions to authenticated;
grant INSERT on public.ride_samples to anon;
grant SELECT on public.ride_samples to anon;
grant UPDATE on public.ride_samples to anon;
grant DELETE on public.ride_samples to anon;
grant TRUNCATE on public.ride_samples to anon;
grant REFERENCES on public.ride_samples to anon;
grant TRIGGER on public.ride_samples to anon;
grant INSERT on public.ride_samples to authenticated;
grant SELECT on public.ride_samples to authenticated;
grant UPDATE on public.ride_samples to authenticated;
grant DELETE on public.ride_samples to authenticated;
grant TRUNCATE on public.ride_samples to authenticated;
grant REFERENCES on public.ride_samples to authenticated;
grant TRIGGER on public.ride_samples to authenticated;
grant usage,select on all sequences in schema public to authenticated;
