import { supabase } from './supabase.js';

const ROLE_RANK={rider:1,technician:2,engineer:3,admin:4,owner:5};
const PREVIEW_ROLES=['rider','technician','engineer','admin'];
const PREVIEW_KEY='motoPreviewRole';
const VIEW_FEATURE={dashboard:'dashboard',garageMode:'garage_mode',garage:'motorcycles',maintenance:'maintenance',rides:'ride_log',parts:'parts',roadmap:'work_packages',engineering:'engineering',pcb:'pcb',firmware:'firmware',notes:'notebook',media:'project_files',ai:'ai_assistant'};
const VIEW_AREA={dashboard:'garage',garageMode:'garage',garage:'garage',maintenance:'garage',rides:'garage',parts:'engineering',roadmap:'engineering',engineering:'engineering',pcb:'engineering',firmware:'engineering',notes:'engineering',media:'engineering',ai:'engineering'};
let session=null,profile={role:'rider',display_name:''},flags=[],grants=[],profiles=[],accessReady=false,applying=false,loadToken=0,openLogged=false;
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const toast=t=>{const e=$('#toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}else console.info(t)};
const actualRole=()=>profile.role||'rider';
function previewRole(){if(!['admin','owner'].includes(actualRole()))return null;const value=sessionStorage.getItem(PREVIEW_KEY);return PREVIEW_ROLES.includes(value)?value:null}
const effectiveRole=()=>previewRole()||actualRole();
function hasGrant(flag){if(previewRole())return false;return !!flag&&grants.some(g=>g.feature_id===flag.id&&g.enabled&&(!g.expires_at||new Date(g.expires_at)>new Date()))}
function stageAllows(flag){const role=effectiveRole();if(['owner','admin'].includes(role))return true;if(flag.release_stage==='production')return true;if(flag.release_stage==='beta')return ['technician','engineer'].includes(role);if(['testing','development'].includes(flag.release_stage))return role==='engineer';return false}
function canUse(flag){if(!accessReady)return true;if(!flag||!flag.enabled)return false;if(hasGrant(flag))return true;if((ROLE_RANK[effectiveRole()]||1)<(ROLE_RANK[flag.minimum_role]||1))return false;return stageAllows(flag)}
function flagFor(key){return flags.find(f=>f.feature_key===key)}
async function logOpen(){if(openLogged||!session)return;openLogged=true;const pwa=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;const {error}=await supabase.from('user_activity_events').insert({user_id:session.user.id,event_type:pwa?'app_open':'website_open',source:pwa?'pwa':'browser'});if(error)console.warn('Open metric unavailable',error)}
async function loadAccess(){const token=++loadToken;const {data:{session:s}}=await supabase.auth.getSession();if(token!==loadToken)return;session=s;if(!session){accessReady=false;return}const [p,f,g,u]=await Promise.all([supabase.from('user_profiles').select('*').eq('user_id',session.user.id).maybeSingle(),supabase.from('feature_flags').select('*').order('sort_order'),supabase.from('user_feature_access').select('*'),supabase.from('user_profiles').select('*').order('created_at')]);if(token!==loadToken)return;if(p.error||f.error){console.error('Access data unavailable',p.error||f.error);accessReady=false;applyAccess();return}if(p.data)profile=p.data;flags=f.data||[];grants=g.data||[];profiles=u.data||[];accessReady=true;applyAccess();logOpen()}
function applyAccess(){if(applying||!session)return;const nav=$('#nav');if(!nav)return;applying=true;try{$$('[data-v]').forEach(btn=>{const view=btn.dataset.v,key=VIEW_FEATURE[view],flag=flagFor(key);if(!key)return;const allowed=canUse(flag);btn.hidden=!allowed;if(flag){btn.dataset.releaseStage=flag.release_stage;let badge=btn.querySelector('.releaseBadge');if(flag.release_stage!=='production'&&allowed){if(!badge){badge=document.createElement('small');badge.className='releaseBadge';btn.appendChild(badge)}badge.textContent=hasGrant(flag)?'granted':flag.release_stage}else badge?.remove()}});relabelGroups(nav);document.querySelector('#accessRoleBadge')?.remove();addAdminButtons(nav);protectActiveView()}finally{applying=false}}
function relabelGroups(nav){nav.querySelectorAll('.navGroup').forEach(group=>{if(group.classList.contains('accessAdminGroup'))return;const visible=[...group.querySelectorAll('[data-v]')].filter(b=>!b.hidden);if(!visible.length){group.hidden=true;return}group.hidden=false;const areas=new Set(visible.map(b=>VIEW_AREA[b.dataset.v]).filter(Boolean));const label=group.querySelector('.navLabel');if(areas.size===1&&label)label.textContent=areas.has('garage')?'MY GARAGE':'ENGINEERING LAB'});const intro=nav.querySelector('.navIntro');if(intro&&accessReady){intro.querySelector('strong').textContent='Moto Mission';intro.querySelector('small').textContent=previewRole()?`Viewing as ${effectiveRole()}`:effectiveRole()==='rider'?'Rider workspace':'Garage + Engineering workspace'}}
function addAdminButtons(nav){nav.querySelector('.accessAdminGroup')?.remove();if(!accessReady||!['admin','owner'].includes(actualRole()))return;const group=document.createElement('div');group.className='navGroup accessAdminGroup';group.innerHTML=`<div class="navLabel">ADMINISTRATION</div><button id="rolePreviewNav"><span class="navIcon">◉</span><span>View as Role</span></button><button id="userMetricsNav"><span class="navIcon">▥</span><span>User Metrics</span></button><button id="releaseManagerNav"><span class="navIcon">⇧</span><span>Release Manager</span></button>${actualRole()==='owner'?'<button id="userAccessNav"><span class="navIcon">♙</span><span>Users & Access</span></button>':''}`;group.hidden=false;nav.insertBefore(group,nav.querySelector('.navFooter'));$('#rolePreviewNav').onclick=showRolePreview;$('#userMetricsNav').onclick=showUserMetrics;$('#releaseManagerNav').onclick=showReleaseManager;$('#userAccessNav')?.addEventListener('click',showUserAccess)}
function protectActiveView(){if(!accessReady)return;const active=$('[data-v].active');if(!active||!active.hidden)return;const fallback=$$('[data-v]').find(b=>!b.hidden);fallback?.click();toast('That area is not enabled for the previewed role.')}
function showRolePreview(){const m=$('#main');if(!m)return;const current=previewRole();m.innerHTML=`<div class="section"><div><span class="eyebrow">ADMIN PREVIEW</span><h2>View as Role</h2><p>Your real account remains <strong>${esc(actualRole())}</strong>. This changes only the visible interface and never writes a new role to your profile.</p></div></div><div class="rolePreviewGrid"><button data-preview-role="" class="rolePreviewCard ${!current?'selected':''}"><strong>Actual access</strong><span>${esc(actualRole())}</span></button>${PREVIEW_ROLES.map(r=>`<button data-preview-role="${r}" class="rolePreviewCard ${current===r?'selected':''}"><strong>${r}</strong><span>Preview this workspace</span></button>`).join('')}</div>`;$$('[data-preview-role]').forEach(x=>x.onclick=()=>{const role=x.dataset.previewRole;if(role)sessionStorage.setItem(PREVIEW_KEY,role);else sessionStorage.removeItem(PREVIEW_KEY);applyAccess();toast(role?`Viewing as ${role}`:'Returned to actual admin access');showRolePreview()})}
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
const when=v=>v?new Date(v).toLocaleString():'No tracked opens yet';
async function showUserMetrics(){const m=$('#main');if(!m)return;m.innerHTML='<div class="section"><div><span class="eyebrow">ADMIN ANALYTICS</span><h2>User Metrics</h2><p>Loading account activity and garage totals…</p></div></div>';const {data,error}=await supabase.rpc('get_admin_user_metrics');if(error){m.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}const rows=data||[];const totals=rows.reduce((a,r)=>({opens:a.opens+Number(r.total_opens||0),bikes:a.bikes+Number(r.bikes||0),rides:a.rides+Number(r.rides||0),miles:a.miles+Number(r.total_miles||0),hours:a.hours+Number(r.total_hours||0)}),{opens:0,bikes:0,rides:0,miles:0,hours:0});m.innerHTML=`<div class="section"><div><span class="eyebrow">ADMIN ANALYTICS</span><h2>User Metrics</h2><p>Open tracking starts with this release. Garage and ride totals include existing database records.</p></div></div><div class="metrics"><div class="metric"><span>Users</span><strong>${rows.length}</strong></div><div class="metric"><span>Total opens</span><strong>${fmt(totals.opens)}</strong></div><div class="metric"><span>Bikes</span><strong>${fmt(totals.bikes)}</strong></div><div class="metric"><span>Rides</span><strong>${fmt(totals.rides)}</strong></div><div class="metric"><span>Tracked miles</span><strong>${fmt(totals.miles)}</strong></div><div class="metric"><span>Ride hours</span><strong>${fmt(totals.hours)}</strong></div></div><div class="stack">${rows.map(r=>`<article class="item userMetricCard"><div class="rowtop"><div><span class="eyebrow">${esc(r.role)}</span><h3>${esc(r.display_name)}</h3><div class="sub">Last activity: ${esc(when(r.last_activity))}</div></div><strong>${fmt(r.total_opens)} opens</strong></div><div class="userMetricGrid"><span><b>${fmt(r.app_opens)}</b>App opens</span><span><b>${fmt(r.website_opens)}</b>Website opens</span><span><b>${fmt(r.bikes)}</b>Bikes</span><span><b>${fmt(r.rides)}</b>Rides</span><span><b>${fmt(r.total_miles)}</b>Miles</span><span><b>${fmt(r.total_hours)}</b>Hours</span><span><b>${fmt(r.maintenance_records)}</b>Maintenance</span><span><b>${fmt(r.parts)}</b>Parts</span></div></article>`).join('')||'<div class="empty">No users found.</div>'}</div>`}
function stageOptions(current){return ['development','testing','beta','production','deprecated','hidden'].map(x=>`<option value="${x}" ${x===current?'selected':''}>${x}</option>`).join('')}
function roleOptions(current){return ['rider','technician','engineer','admin','owner'].map(x=>`<option value="${x}" ${x===current?'selected':''}>${x}</option>`).join('')}
function showReleaseManager(){const m=$('#main');if(!m)return;m.innerHTML=`<div class="section"><div><span class="eyebrow">CONTROLLED ROLLOUT</span><h2>Release Manager</h2><p>Move each feature through development, testing, beta, and production when it is ready.</p></div></div><div class="metrics"><div class="metric"><span>Development</span><strong>${flags.filter(x=>x.release_stage==='development').length}</strong></div><div class="metric"><span>Testing</span><strong>${flags.filter(x=>x.release_stage==='testing').length}</strong></div><div class="metric"><span>Beta</span><strong>${flags.filter(x=>x.release_stage==='beta').length}</strong></div><div class="metric"><span>Production</span><strong>${flags.filter(x=>x.release_stage==='production').length}</strong></div></div><div class="stack">${flags.map(f=>`<article class="item releaseItem"><div class="rowtop"><div><span class="eyebrow">${esc(f.area)} · ${esc(f.minimum_role)}+</span><h3>${esc(f.name)}</h3><p>${esc(f.description||'')}</p></div><label class="releaseToggle"><input type="checkbox" data-feature-enabled="${f.id}" ${f.enabled?'checked':''}> Enabled</label></div><div class="releaseControls"><label>Rollout stage<select data-feature-stage="${f.id}">${stageOptions(f.release_stage)}</select></label><label>Minimum role<select data-feature-role="${f.id}">${roleOptions(f.minimum_role)}</select></label></div></article>`).join('')}</div>`;$$('[data-feature-stage]').forEach(x=>x.onchange=()=>updateFeature(x.dataset.featureStage,{release_stage:x.value}));$$('[data-feature-role]').forEach(x=>x.onchange=()=>updateFeature(x.dataset.featureRole,{minimum_role:x.value}));$$('[data-feature-enabled]').forEach(x=>x.onchange=()=>updateFeature(x.dataset.featureEnabled,{enabled:x.checked}))}
async function updateFeature(id,changes){const {error}=await supabase.from('feature_flags').update({...changes,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast(error.message);return}toast('Feature rollout updated');await loadAccess();showReleaseManager()}
function showUserAccess(){const m=$('#main');if(!m)return;m.innerHTML=`<div class="section"><div><span class="eyebrow">OWNER CONTROL</span><h2>Users & Access</h2><p>Assign a base role. Individual feature grants can expose a feature without promoting the account.</p></div></div><div class="stack">${profiles.map(p=>`<article class="item"><div class="rowtop"><div><h3>${esc(p.display_name||p.user_id)}</h3><div class="sub">${esc(p.user_id)}</div></div><label>Role<select data-profile-role="${p.user_id}">${roleOptions(p.role)}</select></label></div><details><summary>Feature overrides</summary><div class="featureGrantGrid">${flags.map(f=>{let g=grants.find(x=>x.user_id===p.user_id&&x.feature_id===f.id);return `<label><input type="checkbox" data-grant-user="${p.user_id}" data-grant-feature="${f.id}" ${g?.enabled?'checked':''}> ${esc(f.name)} <small>${esc(f.release_stage)}</small></label>`}).join('')}</div></details></article>`).join('')||'<div class="empty">No user profiles found.</div>'}</div>`;$$('[data-profile-role]').forEach(x=>x.onchange=()=>updateRole(x.dataset.profileRole,x.value));$$('[data-grant-user]').forEach(x=>x.onchange=()=>setGrant(x.dataset.grantUser,x.dataset.grantFeature,x.checked))}
async function updateRole(userId,role){if(userId===session.user.id&&['admin','owner'].includes(actualRole())&&role!==actualRole()&&!confirm('This changes your real access. Use View as Role for a safe preview. Continue?')){showUserAccess();return}const {error}=await supabase.from('user_profiles').update({role,updated_at:new Date().toISOString()}).eq('user_id',userId);if(error){toast(error.message);return}toast('User role updated');await loadAccess();showUserAccess()}
async function setGrant(userId,featureId,enabled){const row={user_id:userId,feature_id:featureId,enabled,granted_by:session.user.id};const {error}=await supabase.from('user_feature_access').upsert(row,{onConflict:'user_id,feature_id'});if(error){toast(error.message);return}toast(enabled?'Feature access granted':'Feature override disabled');const {data}=await supabase.from('user_feature_access').select('*');grants=data||[]}
const appRoot=$('#app');if(appRoot){const observer=new MutationObserver(()=>queueMicrotask(applyAccess));observer.observe(appRoot,{childList:true})}
supabase.auth.onAuthStateChange((_event,s)=>{session=s;if(s)setTimeout(loadAccess,50);else{accessReady=false;profile={role:'rider',display_name:''};flags=[];grants=[];profiles=[];openLogged=false;sessionStorage.removeItem(PREVIEW_KEY)}});
loadAccess();