import { supabase } from './supabase.js';

const $ = q => document.querySelector(q);
const esc = (s='') => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const xmlEsc = (s='') => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]));
const rad = n => n*Math.PI/180;
const miles=(a,b)=>{if(!a||!b)return Infinity;const R=3958.7613,d1=rad(b.lat-a.lat),d2=rad(b.lon-a.lon),q=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const bearing=(a,b)=>{if(!a||!b)return 0;const y=Math.sin(rad(b.lon-a.lon))*Math.cos(rad(b.lat));const x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lon-a.lon));return(Math.atan2(y,x)*180/Math.PI+360)%360};
const total=pts=>pts.slice(1).reduce((n,p,i)=>n+miles(pts[i],p),0);
const styleKey=id=>`motoRouteStyle:${id}`;
const defaultStyle={color:'#2563eb',weight:6,opacity:.9,dash:'solid',arrows:true};
const ORIENTATION_STORE='motoAdventureOrientationV1';

let session,map,layers={},trackLayer,waypointLayer,poiLayer,directionLayer,rider,rangeCircle,routes=[],activeRoute,lastFix,follow=true,headingUp=localStorage.getItem(ORIENTATION_STORE)==='heading',gpsHandler,addPointMode=false,geometryPointMode=null,activeSheet=null,routePointIndex=0,styleSaveTimer;

async function leaflet(){if(window.L)return;await new Promise((ok,no)=>{let l=document.querySelector('link[data-leaflet]');if(!l){l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}let s=document.querySelector('script[data-leaflet]');if(s){if(window.L)return ok();s.addEventListener('load',ok,{once:true});s.addEventListener('error',no,{once:true});return}s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function parseGPX(text,name){const x=new DOMParser().parseFromString(text,'application/xml');if(x.querySelector('parsererror'))throw Error('Invalid GPX file');const read=n=>({lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon'),ele:+(n.querySelector('ele')?.textContent||NaN),name:n.querySelector('name')?.textContent||''});let pts=[...x.querySelectorAll('trkpt')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)),kind='track';if(!pts.length){pts=[...x.querySelectorAll('rtept')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));kind='route'}if(pts.length<2)throw Error('GPX needs at least two points');const waypoints=[...x.querySelectorAll('wpt')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));let gain=0;for(let i=1;i<pts.length;i++)if(Number.isFinite(pts[i].ele)&&Number.isFinite(pts[i-1].ele)&&pts[i].ele>pts[i-1].ele)gain+=(pts[i].ele-pts[i-1].ele)*3.28084;return {name:x.querySelector('metadata>name,trk>name,rte>name')?.textContent?.trim()||name.replace(/\.gpx$/i,''),kind,pts,waypoints,distance:total(pts),gain}}
function geojson(pts,properties={}){return {type:'Feature',properties,geometry:{type:'LineString',coordinates:pts.map(p=>[p.lon,p.lat,Number.isFinite(p.ele)?p.ele:0])}}}
function nav(){const n=$('#nav');if(!n||$('#adventureNav'))return;const b=document.createElement('button');b.id='adventureNav';b.innerHTML='<span class="navIcon">△</span><span>Adventure Ride</span><em>MAP</em>';b.onclick=open;const g=[...n.querySelectorAll('.navGroup')].find(x=>x.querySelector('.navLabel')?.textContent.trim()==='Operations');(g||n).appendChild(b)}
function close(){window.removeEventListener('moto-gps-fix',gpsHandler);map?.remove();map=null;clearTimeout(styleSaveTimer);document.body.classList.remove('adventure-open','adventure-map-fullscreen');$('#adventureOverlay')?.remove()}

function sheet(id,title,content){return `<section class="advSheet" id="${id}" aria-hidden="true"><div class="advSheetHandle"></div><header><strong>${title}</strong><button data-sheet-close aria-label="Close panel">×</button></header>${content}</section>`}
function shell(){return `<section class="adventureShell">
  <div id="adventureMap"></div>
  <header class="advTopBar"><button id="closeAdventure" class="advBack" aria-label="Back to app">‹</button><div class="advTopIdentity"><small>ADVENTURE</small><strong id="advTopTitle">Explore</strong></div><div class="advTopStatus"><span id="advGpsDot"></span><b id="advGpsText">GPS</b></div><button id="advRideReturn" class="advRideReturn">🏍 RIDE</button></header>
  <div class="advSpeedHud"><div class="advSpeedChip"><strong id="advSpeed">--</strong><small>MPH</small></div><div class="advLimitSign"><strong id="advLimit">--</strong><small>LIMIT</small></div></div>
  <nav class="advBottomBar">
    <button data-sheet="advTrackSheet"><span class="advNavGlyph">●</span><b>Track</b></button>
    <button data-sheet="advRoutesSheet" id="advRoutesButton" class="route-empty"><span class="advNavGlyph">⌁</span><b>Routes</b></button>
    <button data-sheet="advPointsSheet"><span class="advNavGlyph">＋</span><b>Points</b></button>
    <button data-sheet="advLayersSheet"><span class="advNavGlyph">▱</span><b>Layers</b></button>
    <button data-sheet="advMoreSheet"><span class="advNavGlyph">•••</span><b>More</b></button>
  </nav>
  ${sheet('advTrackSheet','Track','<div id="advRidePanel"></div><div id="advStopsPanel"></div>')}
  ${sheet('advRoutesSheet','Routes','<div class="advRouteTabs"><button data-route-tab="library" class="active">ROUTES</button><button data-route-tab="manager" id="advRouteManagerTab">ROUTE MANAGER</button></div><section data-route-panel="library"><div id="advRouteSummary" class="advRouteSummary"></div><label class="advImportButton">IMPORT GPX<input id="gpxInput" type="file" accept=".gpx,application/gpx+xml"></label><div id="adventureRouteList" class="advList advRouteList"></div></section><section data-route-panel="manager" hidden><div id="advRouteEditor" class="advRouteEditor empty">Select a route or track first.</div></section>')}
  ${sheet('advPointsSheet','Points','<div class="advPointActions"><button id="advAddPoint">＋ ADD ON MAP</button><button id="advAddHere">◎ ADD HERE</button></div><div id="advWaypointList" class="advList"></div>')}
  ${sheet('advLayersSheet','Layers','<div class="advSectionLabel">MAP STYLE</div><div class="advLayerGrid"><button data-layer="street" class="active"><span>▦</span>Street</button><button data-layer="satellite"><span>◫</span>Satellite</button><button data-layer="terrain"><span>⌁</span>Topographic</button></div>')}
  ${sheet('advMoreSheet','More','<div class="advQuickGrid"><button id="advCenter"><span>◎</span><b>Recenter</b><small>Center on GPS</small></button><button id="advFollow" class="active"><span>➤</span><b>Follow</b><small>Keep rider centered</small></button><button id="advFull"><span>⛶</span><b>Fullscreen</b><small>Expand map view</small></button></div><div class="advSectionLabel">HEADING ORIENTATION</div><div class="advOrientationList"><label><input type="radio" name="advOrientation" data-orientation="north"><span><b>North Up</b><small>Map stays oriented north</small></span></label><label><input type="radio" name="advOrientation" data-orientation="heading"><span><b>Heading Up</b><small>Map rotates with your heading</small></span></label></div><div class="advSectionLabel">LIVE STATUS</div><div class="advStatusGrid"><article><small>HEADING</small><strong id="advCourse">--</strong></article><article><small>ROAD</small><strong id="advRoad">Waiting</strong></article><article><small>ALTITUDE</small><strong id="advAltitude">--</strong></article><article><small>GPS ACCURACY</small><strong id="advAccuracy">--</strong></article></div><label class="advRangeRow"><span>RANGE CIRCLE</span><input id="advRange" type="number" min="0" max="500" step="5" placeholder="Miles"><button id="advRangeDraw">SHOW</button></label>')}
  <div id="adventureStatus" class="advToast">Waiting for shared GPS…</div>
</section>`}

async function open(){close();const o=document.createElement('div');o.id='adventureOverlay';o.innerHTML=shell();document.body.appendChild(o);document.body.classList.add('adventure-open');bind();await leaflet();init();await loadRoutes();gpsHandler=e=>useFix(e.detail);window.addEventListener('moto-gps-fix',gpsHandler);if(window.MotoGPS)useFix(window.MotoGPS)}
function bind(){
  $('#closeAdventure').onclick=close;
  $('#advRideReturn').onclick=close;
  $('#gpxInput').onchange=e=>importGPX(e.target.files?.[0]);
  $('#advCenter').onclick=center;
  $('#advFollow').onclick=()=>{follow=!follow;syncFollowControl()};
  $('#advFull').onclick=fullscreen;
  $('#advRangeDraw').onclick=drawRange;
  document.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));
  document.querySelectorAll('[data-sheet-close]').forEach(b=>b.onclick=()=>openSheet(null));
  document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{base(b.dataset.layer);document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b))});
  document.querySelectorAll('[data-orientation]').forEach(input=>input.onchange=()=>{if(input.checked)setOrientation(input.dataset.orientation)});
  document.querySelectorAll('[data-route-tab]').forEach(button=>button.onclick=()=>setRouteTab(button.dataset.routeTab));
  $('#advAddPoint').onclick=()=>{geometryPointMode=null;addPointMode=!addPointMode;$('#advAddPoint').classList.toggle('active',addPointMode);toast(addPointMode?'Tap the map to add a waypoint.':'Waypoint mode off.')};
  $('#advAddHere').onclick=()=>{if(lastFix)addWaypoint(lastFix.lat,lastFix.lon);else toast('Waiting for GPS.')};
  syncOrientationControls();
  syncFollowControl();
  syncRouteIndicator();
}
function openSheet(id){document.querySelectorAll('.advSheet').forEach(s=>{const on=s.id===id;s.classList.toggle('open',on);s.setAttribute('aria-hidden',String(!on))});document.querySelectorAll('.advBottomBar [data-sheet]').forEach(b=>b.classList.toggle('active',b.dataset.sheet===id));activeSheet=id;if(id==='advRoutesSheet'){setRouteTab('library');renderRouteSummary()}setTimeout(()=>map?.invalidateSize(false),230)}
function setRouteTab(tab){if(tab==='manager'&&!activeRoute){toast('Select a route or track first.');tab='library'}document.querySelectorAll('[data-route-tab]').forEach(button=>button.classList.toggle('active',button.dataset.routeTab===tab));document.querySelectorAll('[data-route-panel]').forEach(panel=>panel.hidden=panel.dataset.routePanel!==tab);if(tab==='manager')renderEditor()}
function setOrientation(mode){headingUp=mode==='heading';localStorage.setItem(ORIENTATION_STORE,headingUp?'heading':'north');syncOrientationControls();applyRotation();if(headingUp&&!Number.isFinite(lastFix?.heading))toast('Heading Up will activate when GPS provides a course.')}
function syncOrientationControls(){const mode=headingUp?'heading':'north';document.querySelectorAll('[data-orientation]').forEach(input=>input.checked=input.dataset.orientation===mode)}
function syncFollowControl(){const button=$('#advFollow');if(!button)return;button.classList.toggle('active',follow);button.querySelector('small').textContent=follow?'Keep rider centered':'Manual map control'}
function syncRouteIndicator(){const button=$('#advRoutesButton');if(button){button.classList.toggle('route-ready',Boolean(activeRoute));button.classList.toggle('route-empty',!activeRoute);button.setAttribute('aria-label',activeRoute?`Routes, ${activeRoute.name} selected`:'Routes, no route selected')}const manager=$('#advRouteManagerTab');if(manager)manager.disabled=!activeRoute}
function init(){map=L.map('adventureMap',{zoomControl:false,preferCanvas:true}).setView([31,-99],6);layers.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'});layers.satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'});layers.terrain=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});layers.street.addTo(map);poiLayer=L.layerGroup().addTo(map);waypointLayer=L.layerGroup().addTo(map);directionLayer=L.layerGroup().addTo(map);map.on('dragstart zoomstart',()=>{follow=false;syncFollowControl()});map.on('click',e=>{if(geometryPointMode){insertGeometryPoint(e.latlng.lat,e.latlng.lng,geometryPointMode.insertAt);geometryPointMode=null;return}if(addPointMode){addWaypoint(e.latlng.lat,e.latlng.lng);addPointMode=false;$('#advAddPoint')?.classList.remove('active')}});requestAnimationFrame(()=>{map.invalidateSize(true);applyRotation()})}
function base(k){Object.values(layers).forEach(x=>map.hasLayer(x)&&map.removeLayer(x));layers[k]?.addTo(map)}
function useFix(d){if(!Number.isFinite(d?.latitude)||!Number.isFinite(d?.longitude))return;lastFix={lat:d.latitude,lon:d.longitude,heading:d.heading,speed:d.speed,accuracy:d.accuracy,altitude:d.altitude};if(!rider)rider=L.marker([lastFix.lat,lastFix.lon],{icon:L.divIcon({className:'advRider',html:'<span>▲</span>',iconSize:[36,36],iconAnchor:[18,18]})}).addTo(map);else rider.setLatLng([lastFix.lat,lastFix.lon]);const el=rider.getElement()?.querySelector('span');if(el)el.style.transform=`rotate(${Number.isFinite(d.heading)?d.heading:0}deg)`;if(follow)map.panTo([lastFix.lat,lastFix.lon],{animate:true,duration:.3});$('#advGpsDot')?.classList.add('locked');if($('#advGpsText'))$('#advGpsText').textContent=Number.isFinite(d.accuracy)?`±${Math.round(d.accuracy*3.28084)} ft`:'GPS';if($('#advSpeed'))$('#advSpeed').textContent=Number.isFinite(d.speed)?`${Math.round(d.speed)}`:'--';if($('#advCourse'))$('#advCourse').textContent=Number.isFinite(d.heading)?`${Math.round(d.heading)}°`:'--';if($('#advAltitude'))$('#advAltitude').textContent=Number.isFinite(d.altitude)?`${Math.round(d.altitude*3.28084)} ft`:'--';if($('#advAccuracy'))$('#advAccuracy').textContent=Number.isFinite(d.accuracy)?`±${Math.round(d.accuracy*3.28084)} ft`:'--';updateStats();applyRotation()}
function applyRotation(){const pane=$('#adventureMap .leaflet-map-pane');if(!pane)return;const h=headingUp&&Number.isFinite(lastFix?.heading)?-lastFix.heading:0;pane.style.transformOrigin='50% 50%';pane.style.rotate=`${h}deg`}
function center(){if(lastFix){follow=true;syncFollowControl();map.setView([lastFix.lat,lastFix.lon],16)}else toast('Start Ride Center to provide GPS.')}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#adventureOverlay')?.requestFullscreen)await $('#adventureOverlay').requestFullscreen();else document.body.classList.toggle('adventure-map-fullscreen')}catch{document.body.classList.toggle('adventure-map-fullscreen')}setTimeout(()=>map?.invalidateSize(true),150)}
function toast(msg){const e=$('#adventureStatus');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}

async function importGPX(file){if(!file)return;try{if(!session?.user)throw Error('Sign in before importing routes.');const p=parseGPX(await file.text(),file.name),payload={user_id:session.user.id,name:p.name,source_filename:file.name,route_kind:p.kind,geojson:geojson(p.pts,{style:defaultStyle}),waypoints:p.waypoints,distance_miles:p.distance,elevation_gain_ft:p.gain};const {data,error}=await supabase.from('adventure_routes').insert(payload).select().single();if(error)throw error;routes.unshift({...data,points:p.pts});selectRoute(routes[0]);setRouteTab('manager');toast('GPX imported.')}catch(e){toast(e.message||String(e))}finally{if($('#gpxInput'))$('#gpxInput').value=''}}
async function loadRoutes(){const {data,error}=await supabase.from('adventure_routes').select('*').order('created_at',{ascending:false});if(error){toast('Routes could not be loaded.');return}routes=(data||[]).map(r=>({...r,points:(r.geojson?.geometry?.coordinates||[]).map(c=>({lon:c[0],lat:c[1],ele:c[2]}))}));renderRoutes();renderRouteSummary();syncRouteIndicator()}
function routeStyle(r){if(!r)return {...defaultStyle};let local={};try{local=JSON.parse(localStorage.getItem(styleKey(r.id))||'{}')}catch{}return {...defaultStyle,...(r.geojson?.properties?.style||{}),...local}}
function routeGeojson(r=activeRoute,points=r?.points||[],style=routeStyle(r)){return geojson(points,{...(r?.geojson?.properties||{}),style})}
function saveStyle(r,patch){if(!r)return;const s={...routeStyle(r),...patch};localStorage.setItem(styleKey(r.id),JSON.stringify(s));r.geojson=routeGeojson(r,r.points,s);drawRoute();renderRoutes();clearTimeout(styleSaveTimer);styleSaveTimer=setTimeout(async()=>{const {error}=await supabase.from('adventure_routes').update({geojson:r.geojson}).eq('id',r.id);if(error)toast('Route style could not be saved.')},450)}
function renderRoutes(){const x=$('#adventureRouteList');if(!x)return;x.innerHTML=routes.length?routes.map(r=>`<button data-id="${r.id}" class="${activeRoute?.id===r.id?'active':''}"><span class="routeSwatch" style="background:${routeStyle(r).color}"></span><span class="advRouteListCopy"><strong>${esc(r.name)}</strong><small>${esc(r.route_kind||'track')} · ${Number(r.distance_miles||0).toFixed(1)} mi · ${(r.points||[]).length} points</small></span><span class="advRouteSelectMark">${activeRoute?.id===r.id?'ACTIVE':'SELECT'}</span></button>`).join(''):'<div class="advEmptyState"><strong>No routes yet</strong><p>Import a GPX file to create your first route or track.</p></div>';x.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectRoute(routes.find(r=>String(r.id)===b.dataset.id))}
function renderRouteSummary(){const x=$('#advRouteSummary');if(!x)return;if(!activeRoute){x.className='advRouteSummary empty';x.innerHTML='<div><small>ACTIVE ROUTE</small><strong>No route selected</strong><p>The Routes icon stays red until you select one.</p></div>';return}x.className='advRouteSummary';x.innerHTML=`<div class="advRouteSummaryMain"><span class="advRouteSummaryDot"></span><div><small>ACTIVE ${esc((activeRoute.route_kind||'route').toUpperCase())}</small><strong>${esc(activeRoute.name)}</strong><p>${Number(activeRoute.distance_miles||0).toFixed(1)} mi · ${(activeRoute.points||[]).length} geometry points · ${(activeRoute.waypoints||[]).length} waypoints</p></div></div><div class="advRouteProgress"><article><small>PROGRESS</small><strong id="advProgress">0%</strong></article><article><small>REMAINING</small><strong id="advRemaining">—</strong></article><article><small>OFF ROUTE</small><strong id="advOffRoute">—</strong></article></div><div class="advRouteSummaryActions"><button id="advFitRoute">FIT MAP</button><button id="advOpenManager">MANAGE</button><button id="advClearRoute">CLEAR</button></div>`;$('#advFitRoute').onclick=fit;$('#advOpenManager').onclick=()=>setRouteTab('manager');$('#advClearRoute').onclick=clearActiveRoute;updateStats()}
function selectRoute(r){if(!r)return;activeRoute=r;routePointIndex=0;drawRoute();renderRoutes();renderEditor();renderWaypoints();renderRouteSummary();syncRouteIndicator();fit();updateStats()}
function clearActiveRoute(silent=false){activeRoute=null;routePointIndex=0;trackLayer&&map.removeLayer(trackLayer);trackLayer=null;waypointLayer?.clearLayers();directionLayer?.clearLayers();renderRoutes();renderEditor();renderWaypoints();renderRouteSummary();syncRouteIndicator();setRouteTab('library');if(!silent)toast('Active route cleared.')}
function drawRoute(){trackLayer&&map.removeLayer(trackLayer);trackLayer=null;waypointLayer?.clearLayers();directionLayer?.clearLayers();if(!activeRoute||activeRoute.points.length<2)return;const s=routeStyle(activeRoute);trackLayer=L.polyline(activeRoute.points.map(p=>[p.lat,p.lon]),{color:s.color,weight:Number(s.weight),opacity:Number(s.opacity),dashArray:s.dash==='dashed'?'12 10':s.dash==='dotted'?'3 9':null,lineCap:'round'}).addTo(map);(activeRoute.waypoints||[]).forEach((w,i)=>L.marker([w.lat,w.lon]).bindPopup(`<b>${esc(w.name||`Point ${i+1}`)}</b>`).addTo(waypointLayer));if(s.arrows)drawDirectionArrows(activeRoute.points,s)}
function drawDirectionArrows(points,s){if(!directionLayer||points.length<2)return;const count=Math.min(8,Math.max(1,Math.floor(points.length/80)));for(let n=1;n<=count;n++){const i=Math.min(points.length-1,Math.max(1,Math.round(n*(points.length-1)/(count+1))));const p=points[i],a=points[Math.max(0,i-1)],angle=bearing(a,p);L.marker([p.lat,p.lon],{interactive:false,icon:L.divIcon({className:'advDirectionArrow',html:`<span style="color:${s.color};transform:rotate(${angle}deg)">➤</span>`,iconSize:[24,24],iconAnchor:[12,12]})}).addTo(directionLayer)}}
function renderEditor(){const x=$('#advRouteEditor');if(!x)return;if(!activeRoute){x.className='advRouteEditor empty';x.textContent='Select a route or track first.';return}const s=routeStyle(activeRoute),point=activeRoute.points[routePointIndex]||activeRoute.points[0],pointNumber=routePointIndex+1;x.className='advRouteEditor';x.innerHTML=`
  <div class="advRouteTitle"><div><small>${esc(activeRoute.route_kind||'track')}</small><strong>${esc(activeRoute.name)}</strong><p>${Number(activeRoute.distance_miles||0).toFixed(1)} mi · ${activeRoute.points.length} geometry points</p></div><button id="advFit">FIT MAP</button></div>
  <section class="advManagerSection"><h4>Route details</h4><label>NAME<input id="advRouteName" value="${esc(activeRoute.name)}"></label><div class="advStyleGrid"><label>TYPE<select id="advRouteKind"><option value="route">Route</option><option value="track">Track</option></select></label><label>LINE TYPE<select id="advRouteDash"><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select></label><label>COLOR<input id="advRouteColor" type="color" value="${s.color}"></label><label>WIDTH<input id="advRouteWidth" type="range" min="2" max="14" value="${s.weight}"></label><label>OPACITY<input id="advRouteOpacity" type="range" min=".2" max="1" step=".1" value="${s.opacity}"></label><label class="advToggleLabel">DIRECTION ARROWS<input id="advRouteArrows" type="checkbox" ${s.arrows?'checked':''}></label></div></section>
  <section class="advManagerSection"><h4>Direction & conversion</h4><div class="advRouteActions"><button id="advReverseRoute">REVERSE DIRECTION</button><button id="advConvertRoute">CONVERT TO ${activeRoute.route_kind==='route'?'TRACK':'ROUTE'}</button></div></section>
  <section class="advManagerSection"><div class="advManagerHeader"><h4>Geometry point editor</h4><small>Point ${pointNumber} of ${activeRoute.points.length}</small></div><div class="advPointNavigator"><button id="advPointPrev">‹</button><input id="advPointIndex" type="number" min="1" max="${activeRoute.points.length}" value="${pointNumber}"><button id="advPointNext">›</button></div><div class="advCoordinateGrid"><label>LATITUDE<input id="advGeometryLat" type="number" step="0.000001" value="${Number(point?.lat||0).toFixed(6)}"></label><label>LONGITUDE<input id="advGeometryLon" type="number" step="0.000001" value="${Number(point?.lon||0).toFixed(6)}"></label></div><div class="advGeometryActions"><button id="advSaveGeometryPoint">SAVE POINT</button><button id="advLocateGeometryPoint">SHOW ON MAP</button><button id="advMovePointEarlier">MOVE EARLIER</button><button id="advMovePointLater">MOVE LATER</button><button id="advInsertPointBefore">INSERT BEFORE</button><button id="advInsertPointAfter">INSERT AFTER</button><button id="advDeleteGeometryPoint" class="danger">DELETE POINT</button></div></section>
  <section class="advManagerSection advPointEditor"><header><div><h4>Waypoints</h4><small>${(activeRoute.waypoints||[]).length} saved</small></div><button id="advEditorAddPoint">＋ ADD ON MAP</button></header><div id="advEditorPointList"></div></section>
  <section class="advManagerSection"><h4>File & route actions</h4><div class="advRouteActions"><button id="advExportRoute">EXPORT GPX</button><button id="advDuplicateRoute">DUPLICATE</button><button id="advDeleteRoute" class="danger">DELETE ROUTE</button></div></section>`;
  $('#advRouteKind').value=activeRoute.route_kind||'track';$('#advRouteDash').value=s.dash;$('#advFit').onclick=fit;$('#advRouteColor').oninput=e=>saveStyle(activeRoute,{color:e.target.value});$('#advRouteWidth').oninput=e=>saveStyle(activeRoute,{weight:+e.target.value});$('#advRouteOpacity').oninput=e=>saveStyle(activeRoute,{opacity:+e.target.value});$('#advRouteDash').onchange=e=>saveStyle(activeRoute,{dash:e.target.value});$('#advRouteArrows').onchange=e=>saveStyle(activeRoute,{arrows:e.target.checked});$('#advRouteName').onchange=e=>renameRoute(e.target.value);$('#advRouteKind').onchange=e=>setRouteKind(e.target.value);$('#advConvertRoute').onclick=convertRoute;$('#advReverseRoute').onclick=reverseRoute;$('#advDuplicateRoute').onclick=duplicateRoute;$('#advExportRoute').onclick=exportRoute;$('#advDeleteRoute').onclick=deleteRoute;$('#advEditorAddPoint').onclick=()=>{openSheet(null);geometryPointMode=null;addPointMode=true;toast('Tap the map to add a waypoint.')};$('#advPointPrev').onclick=()=>setRoutePointIndex(routePointIndex-1);$('#advPointNext').onclick=()=>setRoutePointIndex(routePointIndex+1);$('#advPointIndex').onchange=e=>setRoutePointIndex(Number(e.target.value)-1);$('#advSaveGeometryPoint').onclick=updateRoutePoint;$('#advLocateGeometryPoint').onclick=()=>{const p=activeRoute.points[routePointIndex];openSheet(null);map.setView([p.lat,p.lon],18)};$('#advMovePointEarlier').onclick=()=>moveRoutePoint(-1);$('#advMovePointLater').onclick=()=>moveRoutePoint(1);$('#advInsertPointBefore').onclick=()=>beginGeometryInsert(routePointIndex);$('#advInsertPointAfter').onclick=()=>beginGeometryInsert(routePointIndex+1);$('#advDeleteGeometryPoint').onclick=deleteRoutePoint;renderEditorPoints()}
function renderWaypoints(){const x=$('#advWaypointList');if(!x)return;const pts=activeRoute?.waypoints||[];x.innerHTML=activeRoute?`<div class="advSelectedRoute"><span class="advRouteSummaryDot"></span><span><strong>${esc(activeRoute.name)}</strong><small>${pts.length} waypoint${pts.length===1?'':'s'}</small></span></div>${pts.map((w,i)=>`<button data-point="${i}"><span>●</span><span><strong>${esc(w.name||`Point ${i+1}`)}</strong><small>${w.lat.toFixed(5)}, ${w.lon.toFixed(5)}</small></span></button>`).join('')||'<div class="advEmptyState"><strong>No waypoints yet</strong><p>Add one at your GPS location or tap the map.</p></div>'}`:'<div class="advEmptyState"><strong>No active route</strong><p>Select a route before adding waypoints.</p></div>';x.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>map.setView([pts[+b.dataset.point].lat,pts[+b.dataset.point].lon],17))}
function renderEditorPoints(){const x=$('#advEditorPointList');if(!x||!activeRoute)return;const pts=activeRoute.waypoints||[];x.innerHTML=pts.map((w,i)=>`<div class="advWaypointEditRow"><input data-point-name="${i}" value="${esc(w.name||`Point ${i+1}`)}"><button data-point-up="${i}" aria-label="Move up">↑</button><button data-point-down="${i}" aria-label="Move down">↓</button><button data-point-show="${i}" aria-label="Show on map">◎</button><button data-point-delete="${i}" aria-label="Delete">×</button></div>`).join('')||'<p>No waypoints.</p>';x.querySelectorAll('[data-point-name]').forEach(i=>i.onchange=()=>updatePointName(+i.dataset.pointName,i.value));x.querySelectorAll('[data-point-up]').forEach(b=>b.onclick=()=>moveWaypoint(+b.dataset.pointUp,-1));x.querySelectorAll('[data-point-down]').forEach(b=>b.onclick=()=>moveWaypoint(+b.dataset.pointDown,1));x.querySelectorAll('[data-point-show]').forEach(b=>b.onclick=()=>{const p=pts[+b.dataset.pointShow];openSheet(null);map.setView([p.lat,p.lon],18)});x.querySelectorAll('[data-point-delete]').forEach(b=>b.onclick=()=>deletePoint(+b.dataset.pointDelete))}
async function persistRoute(patch){if(!activeRoute)return;Object.assign(activeRoute,patch);const {error}=await supabase.from('adventure_routes').update(patch).eq('id',activeRoute.id);if(error)throw error;renderRoutes();renderRouteSummary();renderWaypoints();renderEditor();drawRoute();syncRouteIndicator()}
async function renameRoute(name){try{await persistRoute({name:name.trim()||activeRoute.name});toast('Route name saved.')}catch(e){toast(e.message)}}
async function setRouteKind(kind){if(!['route','track'].includes(kind))return;try{await persistRoute({route_kind:kind});toast(`Converted to ${kind}.`)}catch(e){toast(e.message)}}
async function convertRoute(){setRouteKind(activeRoute.route_kind==='route'?'track':'route')}
async function reverseRoute(){try{const oldIndex=routePointIndex,points=[...activeRoute.points].reverse(),waypoints=[...(activeRoute.waypoints||[])].reverse();routePointIndex=Math.max(0,points.length-1-oldIndex);activeRoute.points=points;await persistRoute({geojson:routeGeojson(activeRoute,points),waypoints,distance_miles:total(points)});toast('Route direction reversed.')}catch(e){toast(e.message)}}
async function duplicateRoute(){try{if(!session?.user)throw Error('Sign in before duplicating routes.');const payload={user_id:session.user.id,name:`${activeRoute.name} copy`,source_filename:activeRoute.source_filename,route_kind:activeRoute.route_kind,geojson:routeGeojson(activeRoute,activeRoute.points),waypoints:activeRoute.waypoints||[],distance_miles:activeRoute.distance_miles,elevation_gain_ft:activeRoute.elevation_gain_ft};const {data,error}=await supabase.from('adventure_routes').insert(payload).select().single();if(error)throw error;routes.unshift({...data,points:activeRoute.points.map(p=>({...p}))});selectRoute(routes[0]);toast('Route duplicated.')}catch(e){toast(e.message)}}
async function deleteRoute(){if(!confirm('Delete this route permanently?'))return;try{const id=activeRoute.id;const {error}=await supabase.from('adventure_routes').delete().eq('id',id);if(error)throw error;routes=routes.filter(r=>r.id!==id);localStorage.removeItem(styleKey(id));clearActiveRoute(true);toast('Route deleted.')}catch(e){toast(e.message)}}
function exportRoute(){if(!activeRoute)return;const wpts=(activeRoute.waypoints||[]).map(w=>`<wpt lat="${w.lat}" lon="${w.lon}"><name>${xmlEsc(w.name||'Waypoint')}</name></wpt>`).join('');const tag=activeRoute.route_kind==='route'?'rtept':'trkpt',body=activeRoute.points.map(p=>`<${tag} lat="${p.lat}" lon="${p.lon}">${Number.isFinite(p.ele)?`<ele>${p.ele}</ele>`:''}</${tag}>`).join(''),routeBody=activeRoute.route_kind==='route'?`<rte><name>${xmlEsc(activeRoute.name)}</name>${body}</rte>`:`<trk><name>${xmlEsc(activeRoute.name)}</name><trkseg>${body}</trkseg></trk>`;const text=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Moto Mission" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${xmlEsc(activeRoute.name)}</name></metadata>${wpts}${routeBody}</gpx>`,blob=new Blob([text],{type:'application/gpx+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${activeRoute.name.replace(/[^a-z0-9-_]+/gi,'-')||'route'}.gpx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('GPX exported.')}
async function addWaypoint(lat,lon){if(!activeRoute){openSheet('advRoutesSheet');return toast('Select a route first.')}const name=prompt('Waypoint name','New point');if(name===null)return;const points=[...(activeRoute.waypoints||[]),{lat,lon,name:name||'Waypoint'}];try{await persistRoute({waypoints:points});toast('Waypoint added.')}catch(e){toast(e.message)}}
async function updatePointName(i,name){const pts=[...(activeRoute.waypoints||[])];pts[i]={...pts[i],name};try{await persistRoute({waypoints:pts})}catch(e){toast(e.message)}}
async function moveWaypoint(i,delta){const pts=[...(activeRoute.waypoints||[])],j=i+delta;if(j<0||j>=pts.length)return;[pts[i],pts[j]]=[pts[j],pts[i]];try{await persistRoute({waypoints:pts})}catch(e){toast(e.message)}}
async function deletePoint(i){const pts=[...(activeRoute.waypoints||[])];pts.splice(i,1);try{await persistRoute({waypoints:pts})}catch(e){toast(e.message)}}
function setRoutePointIndex(i){if(!activeRoute?.points?.length)return;routePointIndex=Math.max(0,Math.min(activeRoute.points.length-1,Math.round(i)||0));renderEditor()}
async function saveGeometry(points,message){if(points.length<2)return toast('A route needs at least two geometry points.');activeRoute.points=points;routePointIndex=Math.max(0,Math.min(routePointIndex,points.length-1));try{await persistRoute({geojson:routeGeojson(activeRoute,points),distance_miles:total(points)});fit();toast(message)}catch(e){toast(e.message)}}
async function updateRoutePoint(){const lat=Number($('#advGeometryLat').value),lon=Number($('#advGeometryLon').value);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lon)||lon<-180||lon>180)return toast('Enter a valid latitude and longitude.');const points=activeRoute.points.map((p,i)=>i===routePointIndex?{...p,lat,lon}:p);await saveGeometry(points,'Geometry point saved.')}
async function moveRoutePoint(delta){const points=[...activeRoute.points],next=routePointIndex+delta;if(next<0||next>=points.length)return;[points[routePointIndex],points[next]]=[points[next],points[routePointIndex]];routePointIndex=next;await saveGeometry(points,'Geometry point reordered.')}
function beginGeometryInsert(insertAt){geometryPointMode={insertAt};addPointMode=false;openSheet(null);toast('Tap the map to insert the geometry point.')}
async function insertGeometryPoint(lat,lon,insertAt){const points=[...activeRoute.points];points.splice(Math.max(0,Math.min(points.length,insertAt)),0,{lat,lon,ele:NaN});routePointIndex=Math.max(0,Math.min(points.length-1,insertAt));await saveGeometry(points,'Geometry point inserted.')}
async function deleteRoutePoint(){if(activeRoute.points.length<=2)return toast('A route must keep at least two points.');if(!confirm(`Delete geometry point ${routePointIndex+1}?`))return;const points=[...activeRoute.points];points.splice(routePointIndex,1);routePointIndex=Math.min(routePointIndex,points.length-1);await saveGeometry(points,'Geometry point deleted.')}
function fit(){if(trackLayer)map.fitBounds(trackLayer.getBounds(),{padding:[50,50]});else center()}
function updateStats(){if(!activeRoute||!lastFix)return;let best={i:0,d:Infinity};activeRoute.points.forEach((p,i)=>{const d=miles(lastFix,p);if(d<best.d)best={i,d}});const covered=total(activeRoute.points.slice(0,best.i+1)),all=Number(activeRoute.distance_miles)||total(activeRoute.points),rem=Math.max(0,all-covered);if($('#advProgress'))$('#advProgress').textContent=`${Math.min(100,Math.round(covered/Math.max(all,.001)*100))}%`;if($('#advRemaining'))$('#advRemaining').textContent=`${rem.toFixed(1)} mi`;if($('#advOffRoute')){$('#advOffRoute').textContent=best.d<.05?'ON TRACK':`${Math.round(best.d*5280)} ft`;$('#advOffRoute').classList.toggle('warn',best.d>=.1)}}
function drawRange(){if(!lastFix)return toast('Waiting for GPS.');const mi=Number($('#advRange').value);if(!mi)return toast('Enter a range in miles.');rangeCircle&&map.removeLayer(rangeCircle);rangeCircle=L.circle([lastFix.lat,lastFix.lon],{radius:mi*1609.344,weight:2,fillOpacity:.08}).addTo(map);map.fitBounds(rangeCircle.getBounds());openSheet(null)}
window.addEventListener('moto-road-update',e=>{const d=e.detail||{};if($('#advRoad'))$('#advRoad').textContent=d.road||'Unknown';if($('#advLimit'))$('#advLimit').textContent=Number.isFinite(d.limit_mph)?`${Math.round(d.limit_mph)}`:'--'});
const observer=new MutationObserver(nav);observer.observe(document.querySelector('#app')||document.body,{childList:true,subtree:false});supabase.auth.onAuthStateChange((_e,s)=>{session=s;setTimeout(nav,0)});supabase.auth.getSession().then(({data})=>{session=data.session;nav()});
