import { supabase } from './supabase.js';
const $=q=>document.querySelector(q),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,map=null,baseLayers={},routeLayer=null,gasLayer=null,positionMarker=null,watchId=null,routes=[],activeRoute=null,lastPosition=null,pendingRoute=null;
const R=3958.7613,rad=x=>x*Math.PI/180;
function distance(a,b){const dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function totalDistance(points){let d=0;for(let i=1;i<points.length;i++)d+=distance(points[i-1],points[i]);return d}
function nearestOnRoute(p,pts){let best={index:0,distance:Infinity};pts.forEach((x,i)=>{const d=distance(p,x);if(d<best.distance)best={index:i,distance:d}});return best}
async function ensureLeaflet(){if(window.L)return;await new Promise((ok,no)=>{if(!document.querySelector('link[data-leaflet]')){const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';css.dataset.leaflet='1';document.head.appendChild(css)}const existing=document.querySelector('script[data-leaflet]');if(existing){existing.addEventListener('load',ok,{once:true});existing.addEventListener('error',no,{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function parseGPX(text,filename){const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.querySelector('parsererror'))throw new Error('Invalid GPX file');const read=node=>({lat:Number(node.getAttribute('lat')),lon:Number(node.getAttribute('lon')),ele:Number(node.querySelector('ele')?.textContent),name:node.querySelector('name')?.textContent||null});let points=[...xml.querySelectorAll('trkpt')].map(read).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)),kind='track';if(!points.length){points=[...xml.querySelectorAll('rtept')].map(read).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));kind='route'}if(points.length<2)throw new Error('GPX needs at least two track or route points');const waypoints=[...xml.querySelectorAll('wpt')].map(read).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)),name=xml.querySelector('metadata > name,trk > name,rte > name')?.textContent?.trim()||filename.replace(/\.gpx$/i,'');let gain=0;for(let i=1;i<points.length;i++)if(Number.isFinite(points[i].ele)&&Number.isFinite(points[i-1].ele)&&points[i].ele>points[i-1].ele)gain+=(points[i].ele-points[i-1].ele)*3.28084;return {name,kind,points,waypoints,distance:totalDistance(points),gain}}
function geojson(points){return {type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points.map(p=>[p.lon,p.lat,Number.isFinite(p.ele)?p.ele:0])}}}
function simplify(points,max=80){if(points.length<=max)return points;const out=[],step=(points.length-1)/(max-1);for(let i=0;i<max;i++)out.push(points[Math.round(i*step)]);return out}
function routeGPX(route){const pts=simplify(route.points,100),body=pts.map((p,i)=>`<rtept lat="${p.lat}" lon="${p.lon}"><name>${i===0?'Start':i===pts.length-1?'Finish':`Via ${i}`}</name>${Number.isFinite(p.ele)?`<ele>${p.ele}</ele>`:''}</rtept>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="MotoCloud" xmlns="http://www.topografix.com/GPX/1/1"><rte><name>${esc(route.name)} Route</name>${body}</rte></gpx>`}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/gpx+xml'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function injectNav(){const nav=$('#nav');if(!nav||$('#adventureNav'))return;const btn=document.createElement('button');btn.id='adventureNav';btn.innerHTML='<span class="navIcon">△</span><span>Adventure Ride</span><em>GPX</em>';btn.onclick=openAdventure;const ops=[...nav.querySelectorAll('.navGroup')].find(g=>g.querySelector('.navLabel')?.textContent.trim()==='Operations');(ops||nav).appendChild(btn)}
async function loadRoutes(){const {data}=await supabase.from('adventure_routes').select('*').order('created_at',{ascending:false});routes=(data||[]).map(r=>({...r,points:(r.geojson?.geometry?.coordinates||[]).map(c=>({lon:c[0],lat:c[1],ele:c[2]}))}));renderRouteList()}
function destroyAdventure(){stopNavigation();if(map){map.off();map.remove()}map=null;baseLayers={};routeLayer=null;gasLayer=null;positionMarker=null;pendingRoute=null;document.body.classList.remove('adventure-open');document.querySelector('#adventureOverlay')?.remove()}
function openAdventure(){destroyAdventure();const o=document.createElement('div');o.id='adventureOverlay';o.innerHTML=`<section class="adventureShell"><header><div><small>ADVENTURE BIKE MODE</small><h2>Tracks, routes & fuel</h2></div><button id="closeAdventure" aria-label="Close Adventure Mode">×</button></header><div class="adventureToolbar"><label class="gpxImport">LOAD GPX<input id="gpxInput" type="file" accept=".gpx,application/gpx+xml"></label><button id="locateAdventure">◎ LOCATE</button><button id="fuelAdventure">⛽ GAS</button><select id="adventureMapStyle" aria-label="Map style"><option value="street">Simple map</option><option value="satellite">Satellite</option></select></div><div class="adventureLayout"><aside id="adventureDrawer"><div id="adventureStatus">Load a GPX track or choose a saved route.</div><div id="adventureRouteList"></div></aside><button id="adventureDrawerToggle" class="adventureDrawerToggle" aria-label="Open routes">▲</button><main><div id="adventureMap"></div><div class="adventureMapButtons"><button id="advCenter" aria-label="Center on location">◎</button><button id="advFit" aria-label="Fit route">⌗</button></div><div id="adventureNavPanel" class="hidden"><div><small>ROUTE PROGRESS</small><strong id="advProgress">0%</strong></div><div><small>REMAINING</small><strong id="advRemaining">—</strong></div><div><small>OFF ROUTE</small><strong id="advOffRoute">—</strong></div><button id="stopAdvNav">STOP NAV</button></div></main></div></section>`;document.body.appendChild(o);document.body.classList.add('adventure-open');$('#closeAdventure').onclick=destroyAdventure;$('#gpxInput').onchange=e=>importGPX(e.target.files?.[0]);$('#locateAdventure').onclick=locate;$('#fuelAdventure').onclick=findFuel;$('#adventureMapStyle').onchange=e=>setBase(e.target.value);$('#stopAdvNav').onclick=stopNavigation;$('#advCenter').onclick=locate;$('#advFit').onclick=fitActiveRoute;$('#adventureDrawerToggle').onclick=()=>{const drawer=$('#adventureDrawer'),open=drawer.classList.toggle('open');$('#adventureDrawerToggle').textContent=open?'▼':'▲'};ensureLeaflet().then(initMap).catch(()=>{$('#adventureStatus').textContent='Map library failed to load. Check internet access.'});loadRoutes()}
function initMap(){const el=$('#adventureMap');if(!el)return;if(map){map.off();map.remove()}map=L.map(el,{zoomControl:true,preferCanvas:true}).setView([31,-99],6);baseLayers.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});baseLayers.satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});baseLayers.street.addTo(map);gasLayer=L.layerGroup().addTo(map);requestAnimationFrame(()=>{map.invalidateSize(true);setTimeout(()=>map?.invalidateSize(true),250)});if(pendingRoute){const r=pendingRoute;pendingRoute=null;selectRoute(r)}}
function setBase(kind){if(!map)return;Object.values(baseLayers).forEach(x=>map.removeLayer(x));baseLayers[kind]?.addTo(map);setTimeout(()=>map.invalidateSize(true),50)}
async function importGPX(file){if(!file)return;try{const parsed=parseGPX(await file.text(),file.name),payload={user_id:session.user.id,name:parsed.name,source_filename:file.name,route_kind:parsed.kind,geojson:geojson(parsed.points),waypoints:parsed.waypoints,distance_miles:parsed.distance,elevation_gain_ft:parsed.gain},{data,error}=await supabase.from('adventure_routes').insert(payload).select().single();if(error)throw error;routes.unshift({...data,points:parsed.points});selectRoute(routes[0]);renderRouteList();$('#adventureStatus').textContent=`Loaded ${parsed.name} · ${parsed.distance.toFixed(1)} mi`}catch(e){alert(e.message||e)}}
function renderRouteList(){const box=$('#adventureRouteList');if(!box)return;box.innerHTML=routes.length?routes.map(r=>`<article data-route="${r.id}" class="${activeRoute?.id===r.id?'active':''}"><div><strong>${esc(r.name)}</strong><small>${Number(r.distance_miles||0).toFixed(1)} mi · ${r.route_kind}</small></div><div><button data-convert="${r.id}">ROUTE</button><button data-delete-route="${r.id}" aria-label="Delete route">×</button></div></article>`).join(''):'<p class="empty">No GPX tracks loaded.</p>';box.querySelectorAll('[data-route]').forEach(x=>x.onclick=e=>{if(e.target.closest('button'))return;selectRoute(routes.find(r=>r.id===x.dataset.route));$('#adventureDrawer')?.classList.remove('open');if($('#adventureDrawerToggle'))$('#adventureDrawerToggle').textContent='▲'});box.querySelectorAll('[data-convert]').forEach(x=>x.onclick=()=>{const r=routes.find(a=>a.id===x.dataset.convert);download(`${r.name.replace(/[^a-z0-9]+/gi,'-')}-route.gpx`,routeGPX(r))});box.querySelectorAll('[data-delete-route]').forEach(x=>x.onclick=async()=>{if(!confirm('Delete this saved route?'))return;await supabase.from('adventure_routes').delete().eq('id',x.dataset.deleteRoute);routes=routes.filter(r=>r.id!==x.dataset.deleteRoute);if(activeRoute?.id===x.dataset.deleteRoute){activeRoute=null;if(routeLayer&&map)map.removeLayer(routeLayer);routeLayer=null;stopNavigation()}renderRouteList()})}
function selectRoute(r){if(!r)return;if(!map){pendingRoute=r;activeRoute=r;renderRouteList();return}activeRoute=r;if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.polyline(r.points.map(p=>[p.lat,p.lon]),{weight:6,opacity:.92}).addTo(map);fitActiveRoute();$('#adventureStatus').textContent=`${r.name} · ${Number(r.distance_miles).toFixed(1)} mi · ${Math.round(Number(r.elevation_gain_ft||0))} ft gain`;renderRouteList();startNavigation()}
function fitActiveRoute(){if(routeLayer&&map){map.invalidateSize(true);map.fitBounds(routeLayer.getBounds(),{padding:[32,32],maxZoom:16})}else if(lastPosition&&map)map.setView([lastPosition.lat,lastPosition.lon],15)}
function locate(){navigator.geolocation.getCurrentPosition(p=>{const c={lat:p.coords.latitude,lon:p.coords.longitude};showPosition(c);map?.setView([c.lat,c.lon],15)},e=>alert(e.message),{enableHighAccuracy:true,timeout:15000,maximumAge:3000})}
function showPosition(c){lastPosition=c;if(!map)return;positionMarker?positionMarker.setLatLng([c.lat,c.lon]):positionMarker=L.circleMarker([c.lat,c.lon],{radius:9,weight:3,fillOpacity:1}).addTo(map)}
function startNavigation(){if(!activeRoute)return;$('#adventureNavPanel')?.classList.remove('hidden');if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>{const c={lat:p.coords.latitude,lon:p.coords.longitude};showPosition(c);const hit=nearestOnRoute(c,activeRoute.points),covered=totalDistance(activeRoute.points.slice(0,hit.index+1)),total=Number(activeRoute.distance_miles)||totalDistance(activeRoute.points),remaining=Math.max(0,total-covered);if($('#advProgress'))$('#advProgress').textContent=`${Math.min(100,Math.round(covered/Math.max(total,.001)*100))}%`;if($('#advRemaining'))$('#advRemaining').textContent=`${remaining.toFixed(1)} mi`;if($('#advOffRoute')){$('#advOffRoute').textContent=hit.distance<0.05?'ON TRACK':`${Math.round(hit.distance*5280)} ft`;$('#advOffRoute').classList.toggle('warn',hit.distance>=0.1)}},()=>{}, {enableHighAccuracy:true,maximumAge:2000,timeout:15000})}
function stopNavigation(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;$('#adventureNavPanel')?.classList.add('hidden')}
async function findFuel(){try{const c=lastPosition||await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>ok({lat:p.coords.latitude,lon:p.coords.longitude}),no,{enableHighAccuracy:true,timeout:15000}));if($('#adventureStatus'))$('#adventureStatus').textContent='Finding nearby fuel…';const r=await fetch(`/api/fuel-nearby?lat=${c.lat}&lon=${c.lon}&radius=25000`),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);if(!map||!gasLayer)throw new Error('Map is still loading');gasLayer.clearLayers();d.stations.forEach(s=>L.marker([s.lat,s.lon],{title:s.name}).bindPopup(`<b>${esc(s.name)}</b><br>${s.distance_miles.toFixed(1)} mi away${s.opening_hours?`<br>${esc(s.opening_hours)}`:''}<br><a href="https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lon}" target="_blank" rel="noopener">Route to station</a>`).addTo(gasLayer));$('#adventureStatus').textContent=`${d.stations.length} fuel stations found · ${d.source}`;if(d.stations[0])map.fitBounds(L.latLngBounds([[c.lat,c.lon],...d.stations.slice(0,8).map(s=>[s.lat,s.lon])]),{padding:[32,32]})}catch(e){if($('#adventureStatus'))$('#adventureStatus').textContent=`Fuel unavailable: ${e.message||e}`}}
async function init(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!s)return;new MutationObserver(()=>queueMicrotask(injectNav)).observe(document.body,{childList:true,subtree:true});injectNav()}
init();