import { supabase } from './supabase.js';

const $ = q => document.querySelector(q);
const esc = (s='') => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const rad = n => n*Math.PI/180;
const miles=(a,b)=>{if(!a||!b)return Infinity;const R=3958.7613,d1=rad(b.lat-a.lat),d2=rad(b.lon-a.lon),q=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const total=pts=>pts.slice(1).reduce((n,p,i)=>n+miles(pts[i],p),0);
const styleKey=id=>`motoRouteStyle:${id}`;
const defaultStyle={color:'#7c3aed',weight:6,opacity:.9,dash:'solid',arrows:false};

let session,map,layers={},trackLayer,waypointLayer,poiLayer,rider,rangeCircle,routes=[],activeRoute,lastFix,follow=true,headingUp=false,gpsHandler,addPointMode=false,activeSheet=null;

async function leaflet(){if(window.L)return;await new Promise((ok,no)=>{let l=document.querySelector('link[data-leaflet]');if(!l){l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}let s=document.querySelector('script[data-leaflet]');if(s){if(window.L)return ok();s.addEventListener('load',ok,{once:true});s.addEventListener('error',no,{once:true});return}s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function parseGPX(text,name){const x=new DOMParser().parseFromString(text,'application/xml');if(x.querySelector('parsererror'))throw Error('Invalid GPX file');const read=n=>({lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon'),ele:+(n.querySelector('ele')?.textContent||NaN),name:n.querySelector('name')?.textContent||''});let pts=[...x.querySelectorAll('trkpt')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)),kind='track';if(!pts.length){pts=[...x.querySelectorAll('rtept')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));kind='route'}if(pts.length<2)throw Error('GPX needs at least two points');const waypoints=[...x.querySelectorAll('wpt')].map(read).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));let gain=0;for(let i=1;i<pts.length;i++)if(Number.isFinite(pts[i].ele)&&Number.isFinite(pts[i-1].ele)&&pts[i].ele>pts[i-1].ele)gain+=(pts[i].ele-pts[i-1].ele)*3.28084;return {name:x.querySelector('metadata>name,trk>name,rte>name')?.textContent?.trim()||name.replace(/\.gpx$/i,''),kind,pts,waypoints,distance:total(pts),gain}}
function geojson(pts){return {type:'Feature',properties:{},geometry:{type:'LineString',coordinates:pts.map(p=>[p.lon,p.lat,Number.isFinite(p.ele)?p.ele:0])}}}
function nav(){const n=$('#nav');if(!n||$('#adventureNav'))return;const b=document.createElement('button');b.id='adventureNav';b.innerHTML='<span class="navIcon">△</span><span>Adventure Ride</span><em>MAP</em>';b.onclick=open;const g=[...n.querySelectorAll('.navGroup')].find(x=>x.querySelector('.navLabel')?.textContent.trim()==='Operations');(g||n).appendChild(b)}
function close(){window.removeEventListener('moto-gps-fix',gpsHandler);map?.remove();map=null;document.body.classList.remove('adventure-open','adventure-map-fullscreen');$('#adventureOverlay')?.remove()}

function sheet(id,title,content){return `<section class="advSheet" id="${id}" aria-hidden="true"><div class="advSheetHandle"></div><header><strong>${title}</strong><button data-sheet-close>×</button></header>${content}</section>`}
function shell(){return `<section class="adventureShell">
  <div id="adventureMap"></div>
  <header class="advTopBar"><div><small>ADVENTURE</small><strong id="advTopTitle">Explore</strong></div><div class="advTopStatus"><span id="advGpsDot"></span><b id="advGpsText">GPS waiting</b></div><button id="closeAdventure">×</button></header>
  <div class="advSideRail">
    <button id="advCenter" aria-label="Center">◎</button><button id="advFollow" class="active" aria-label="Follow">➤</button><button id="advHeading" aria-label="Heading mode">🧭</button><button id="advLayersQuick" aria-label="Layers">▱</button><button id="advFull" aria-label="Fullscreen">⛶</button>
  </div>
  <div id="advDataOverlay" class="advDataOverlay"><button id="advDataCollapse">⌄</button><div data-metric="speed"><small>SPEED</small><strong id="advSpeed">--</strong></div><div data-metric="heading"><small>HEADING</small><strong id="advCourse">--</strong></div><div data-metric="road"><small>ROAD</small><strong id="advRoad">Waiting</strong></div><div data-metric="limit"><small>LIMIT</small><strong id="advLimit">--</strong></div><div data-metric="altitude"><small>ALT</small><strong id="advAltitude">--</strong></div><div data-metric="accuracy"><small>GPS</small><strong id="advAccuracy">--</strong></div></div>
  <div id="adventureNavPanel" class="adventureNavPanel hidden"><div><small>PROGRESS</small><strong id="advProgress">0%</strong></div><div><small>REMAINING</small><strong id="advRemaining">—</strong></div><div><small>OFF ROUTE</small><strong id="advOffRoute">—</strong></div></div>
  <nav class="advBottomBar"><button data-sheet="advTrackSheet"><span>●</span>Track</button><button data-sheet="advPointsSheet"><span>＋</span>Points</button><button data-sheet="advLayersSheet"><span>▱</span>Layers</button><button data-sheet="advGpxSheet"><span>⌁</span>GPX</button><button data-sheet="advDataSheet"><span>▦</span>Data</button></nav>
  ${sheet('advTrackSheet','Ride tracking','<div id="advRidePanel"></div><div id="advStopsPanel"></div>')}
  ${sheet('advPointsSheet','Waypoints','<div class="advPointActions"><button id="advAddPoint">＋ ADD ON MAP</button><button id="advAddHere">◎ ADD HERE</button></div><div id="advWaypointList" class="advList"></div>')}
  ${sheet('advLayersSheet','Map layers','<div class="advLayerGrid"><button data-layer="street" class="active">Street</button><button data-layer="satellite">Satellite</button><button data-layer="terrain">Topo</button></div><label class="advRangeRow">RANGE CIRCLE <input id="advRange" type="number" min="0" max="500" step="5" placeholder="Miles"><button id="advRangeDraw">SHOW</button></label>')}
  ${sheet('advGpxSheet','GPX manager','<label class="advImportButton">IMPORT GPX<input id="gpxInput" type="file" accept=".gpx,application/gpx+xml"></label><div class="advGpxLayout"><div id="adventureRouteList" class="advList"></div><div id="advRouteEditor" class="advRouteEditor empty">Select a track or route.</div></div>')}
  ${sheet('advDataSheet','Data overlay','<div class="advMetricChoices"><label><input type="checkbox" data-overlay="speed" checked> Speed</label><label><input type="checkbox" data-overlay="heading" checked> Heading</label><label><input type="checkbox" data-overlay="road" checked> Road</label><label><input type="checkbox" data-overlay="limit" checked> Speed limit</label><label><input type="checkbox" data-overlay="altitude" checked> Altitude</label><label><input type="checkbox" data-overlay="accuracy" checked> GPS accuracy</label></div><button id="advOverlayToggle" class="advPrimary">HIDE OVERLAY</button>')}
  <div id="adventureStatus" class="advToast">Waiting for shared GPS…</div>
</section>`}

async function open(){close();const o=document.createElement('div');o.id='adventureOverlay';o.innerHTML=shell();document.body.appendChild(o);document.body.classList.add('adventure-open');bind();await leaflet();init();await loadRoutes();gpsHandler=e=>useFix(e.detail);window.addEventListener('moto-gps-fix',gpsHandler);if(window.MotoGPS)useFix(window.MotoGPS)}
function bind(){
  $('#closeAdventure').onclick=close;
  $('#gpxInput').onchange=e=>importGPX(e.target.files?.[0]);
  $('#advCenter').onclick=center;
  $('#advFollow').onclick=()=>{$('#advFollow').classList.toggle('active',follow=!follow)};
  $('#advFull').onclick=fullscreen;
  $('#advHeading').onclick=()=>{headingUp=!headingUp;$('#advHeading').classList.toggle('active',headingUp);applyRotation()};
  $('#advLayersQuick').onclick=()=>openSheet('advLayersSheet');
  $('#advRangeDraw').onclick=drawRange;
  $('#advDataCollapse').onclick=()=>$('#advDataOverlay').classList.toggle('compact');
  $('#advOverlayToggle').onclick=()=>{const x=$('#advDataOverlay');x.classList.toggle('hidden');$('#advOverlayToggle').textContent=x.classList.contains('hidden')?'SHOW OVERLAY':'HIDE OVERLAY'};
  document.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));
  document.querySelectorAll('[data-sheet-close]').forEach(b=>b.onclick=()=>openSheet(null));
  document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{base(b.dataset.layer);document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b))});
  document.querySelectorAll('[data-overlay]').forEach(c=>c.onchange=()=>document.querySelector(`[data-metric="${c.dataset.overlay}"]`)?.classList.toggle('hidden',!c.checked));
  $('#advAddPoint').onclick=()=>{addPointMode=!addPointMode;$('#advAddPoint').classList.toggle('active',addPointMode);toast(addPointMode?'Tap the map to add a waypoint.':'Waypoint mode off.')};
  $('#advAddHere').onclick=()=>{if(lastFix)addWaypoint(lastFix.lat,lastFix.lon);else toast('Waiting for GPS.')};
}
function openSheet(id){document.querySelectorAll('.advSheet').forEach(s=>{const on=s.id===id;s.classList.toggle('open',on);s.setAttribute('aria-hidden',String(!on))});document.querySelectorAll('.advBottomBar [data-sheet]').forEach(b=>b.classList.toggle('active',b.dataset.sheet===id));activeSheet=id}
function init(){map=L.map('adventureMap',{zoomControl:false,preferCanvas:true}).setView([31,-99],6);layers.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'});layers.satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'});layers.terrain=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});layers.street.addTo(map);poiLayer=L.layerGroup().addTo(map);waypointLayer=L.layerGroup().addTo(map);map.on('dragstart zoomstart',()=>{$('#advFollow')?.classList.remove('active');follow=false});map.on('click',e=>{if(addPointMode){addWaypoint(e.latlng.lat,e.latlng.lng);addPointMode=false;$('#advAddPoint').classList.remove('active')}});requestAnimationFrame(()=>map.invalidateSize(true))}
function base(k){Object.values(layers).forEach(x=>map.hasLayer(x)&&map.removeLayer(x));layers[k]?.addTo(map)}
function useFix(d){if(!Number.isFinite(d?.latitude)||!Number.isFinite(d?.longitude))return;lastFix={lat:d.latitude,lon:d.longitude,heading:d.heading,speed:d.speed,accuracy:d.accuracy,altitude:d.altitude};if(!rider)rider=L.marker([lastFix.lat,lastFix.lon],{icon:L.divIcon({className:'advRider',html:'<span>▲</span>',iconSize:[36,36],iconAnchor:[18,18]})}).addTo(map);else rider.setLatLng([lastFix.lat,lastFix.lon]);const el=rider.getElement()?.querySelector('span');if(el)el.style.transform=`rotate(${Number.isFinite(d.heading)?d.heading:0}deg)`;if(follow)map.panTo([lastFix.lat,lastFix.lon],{animate:true,duration:.3});$('#advGpsDot').classList.add('locked');$('#advGpsText').textContent=`±${Math.round((d.accuracy||0)*3.28084)} ft`;$('#advSpeed').textContent=Number.isFinite(d.speed)?`${Math.round(d.speed)} mph`:'--';$('#advCourse').textContent=Number.isFinite(d.heading)?`${Math.round(d.heading)}°`:'--';$('#advAltitude').textContent=Number.isFinite(d.altitude)?`${Math.round(d.altitude*3.28084)} ft`:'--';$('#advAccuracy').textContent=Number.isFinite(d.accuracy)?`±${Math.round(d.accuracy*3.28084)} ft`:'--';updateStats();applyRotation()}
function applyRotation(){const pane=$('#adventureMap .leaflet-map-pane');if(!pane)return;const h=headingUp&&Number.isFinite(lastFix?.heading)?-lastFix.heading:0;pane.style.transformOrigin='50% 50%';pane.style.rotate=`${h}deg`}
function center(){if(lastFix)map.setView([lastFix.lat,lastFix.lon],16);else toast('Start Ride Center to provide GPS.')}
function fullscreen(){document.body.classList.toggle('adventure-map-fullscreen');setTimeout(()=>map?.invalidateSize(true),150)}
function toast(msg){const e=$('#adventureStatus');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}

async function importGPX(file){if(!file)return;try{const p=parseGPX(await file.text(),file.name),payload={user_id:session.user.id,name:p.name,source_filename:file.name,route_kind:p.kind,geojson:geojson(p.pts),waypoints:p.waypoints,distance_miles:p.distance,elevation_gain_ft:p.gain};const {data,error}=await supabase.from('adventure_routes').insert(payload).select().single();if(error)throw error;routes.unshift({...data,points:p.pts});renderRoutes();selectRoute(routes[0]);toast('GPX imported.')}catch(e){toast(e.message||String(e))}}
async function loadRoutes(){const {data}=await supabase.from('adventure_routes').select('*').order('created_at',{ascending:false});routes=(data||[]).map(r=>({...r,points:(r.geojson?.geometry?.coordinates||[]).map(c=>({lon:c[0],lat:c[1],ele:c[2]}))}));renderRoutes()}
function routeStyle(r){try{return {...defaultStyle,...JSON.parse(localStorage.getItem(styleKey(r.id))||'{}')}}catch{return {...defaultStyle}}}
function saveStyle(r,patch){const s={...routeStyle(r),...patch};localStorage.setItem(styleKey(r.id),JSON.stringify(s));drawRoute();renderEditor()}
function renderRoutes(){const x=$('#adventureRouteList');if(!x)return;x.innerHTML=routes.length?routes.map(r=>`<button data-id="${r.id}" class="${activeRoute?.id===r.id?'active':''}"><span class="routeSwatch" style="background:${routeStyle(r).color}"></span><span><strong>${esc(r.name)}</strong><small>${esc(r.route_kind||'track')} · ${Number(r.distance_miles||0).toFixed(1)} mi</small></span></button>`).join(''):'<p>No GPX files imported.</p>';x.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectRoute(routes.find(r=>r.id===b.dataset.id)))}
function selectRoute(r){activeRoute=r;drawRoute();renderRoutes();renderEditor();renderWaypoints();fit();$('#adventureNavPanel').classList.remove('hidden');$('#advTopTitle').textContent=r.name;updateStats()}
function drawRoute(){trackLayer&&map.removeLayer(trackLayer);waypointLayer.clearLayers();if(!activeRoute)return;const s=routeStyle(activeRoute);trackLayer=L.polyline(activeRoute.points.map(p=>[p.lat,p.lon]),{color:s.color,weight:Number(s.weight),opacity:Number(s.opacity),dashArray:s.dash==='dashed'?'12 10':s.dash==='dotted'?'3 9':null,lineCap:'round'}).addTo(map);(activeRoute.waypoints||[]).forEach((w,i)=>L.marker([w.lat,w.lon]).bindPopup(`<b>${esc(w.name||`Point ${i+1}`)}</b>`).addTo(waypointLayer))}
function renderEditor(){const x=$('#advRouteEditor');if(!x)return;if(!activeRoute){x.className='advRouteEditor empty';x.textContent='Select a track or route.';return}const s=routeStyle(activeRoute);x.className='advRouteEditor';x.innerHTML=`<div class="advRouteTitle"><div><small>${esc(activeRoute.route_kind||'track')}</small><strong>${esc(activeRoute.name)}</strong></div><button id="advFit">FIT</button></div><label>NAME<input id="advRouteName" value="${esc(activeRoute.name)}"></label><div class="advStyleGrid"><label>COLOR<input id="advRouteColor" type="color" value="${s.color}"></label><label>WIDTH<input id="advRouteWidth" type="range" min="2" max="14" value="${s.weight}"></label><label>OPACITY<input id="advRouteOpacity" type="range" min=".2" max="1" step=".1" value="${s.opacity}"></label><label>LINE<select id="advRouteDash"><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select></label></div><div class="advRouteActions"><button id="advConvertRoute">CONVERT TO ${activeRoute.route_kind==='route'?'TRACK':'ROUTE'}</button><button id="advReverseRoute">REVERSE</button><button id="advDuplicateRoute">DUPLICATE</button><button id="advDeleteRoute" class="danger">DELETE</button></div><div class="advPointEditor"><header><strong>WAYPOINTS</strong><button id="advEditorAddPoint">＋ ADD</button></header><div id="advEditorPointList"></div></div>`;$('#advRouteDash').value=s.dash;$('#advFit').onclick=fit;$('#advRouteColor').oninput=e=>saveStyle(activeRoute,{color:e.target.value});$('#advRouteWidth').oninput=e=>saveStyle(activeRoute,{weight:+e.target.value});$('#advRouteOpacity').oninput=e=>saveStyle(activeRoute,{opacity:+e.target.value});$('#advRouteDash').onchange=e=>saveStyle(activeRoute,{dash:e.target.value});$('#advRouteName').onchange=e=>renameRoute(e.target.value);$('#advConvertRoute').onclick=convertRoute;$('#advReverseRoute').onclick=reverseRoute;$('#advDuplicateRoute').onclick=duplicateRoute;$('#advDeleteRoute').onclick=deleteRoute;$('#advEditorAddPoint').onclick=()=>{openSheet(null);addPointMode=true;toast('Tap the map to add a waypoint.')};renderEditorPoints()}
function renderWaypoints(){const x=$('#advWaypointList');if(!x)return;const pts=activeRoute?.waypoints||[];x.innerHTML=activeRoute?`<div class="advSelectedRoute"><strong>${esc(activeRoute.name)}</strong><small>${pts.length} waypoint${pts.length===1?'':'s'}</small></div>${pts.map((w,i)=>`<button data-point="${i}"><span>●</span><span><strong>${esc(w.name||`Point ${i+1}`)}</strong><small>${w.lat.toFixed(5)}, ${w.lon.toFixed(5)}</small></span></button>`).join('')||'<p>No waypoints yet.</p>'}`:'<p>Select a GPX file first.</p>';x.querySelectorAll('[data-point]').forEach(b=>b.onclick=()=>map.setView([pts[+b.dataset.point].lat,pts[+b.dataset.point].lon],17))}
function renderEditorPoints(){const x=$('#advEditorPointList');if(!x||!activeRoute)return;const pts=activeRoute.waypoints||[];x.innerHTML=pts.map((w,i)=>`<div><input data-point-name="${i}" value="${esc(w.name||`Point ${i+1}`)}"><button data-point-delete="${i}">×</button></div>`).join('')||'<p>No points.</p>';x.querySelectorAll('[data-point-name]').forEach(i=>i.onchange=()=>updatePointName(+i.dataset.pointName,i.value));x.querySelectorAll('[data-point-delete]').forEach(b=>b.onclick=()=>deletePoint(+b.dataset.pointDelete))}
async function persistRoute(patch){if(!activeRoute)return;Object.assign(activeRoute,patch);const {error}=await supabase.from('adventure_routes').update(patch).eq('id',activeRoute.id);if(error)throw error;renderRoutes();renderEditor();drawRoute()}
async function renameRoute(name){try{await persistRoute({name:name.trim()||activeRoute.name});$('#advTopTitle').textContent=activeRoute.name}catch(e){toast(e.message)}}
async function convertRoute(){try{await persistRoute({route_kind:activeRoute.route_kind==='route'?'track':'route'});toast('Conversion saved.')}catch(e){toast(e.message)}}
async function reverseRoute(){try{activeRoute.points.reverse();await persistRoute({geojson:geojson(activeRoute.points)});fit();toast('Direction reversed.')}catch(e){toast(e.message)}}
async function duplicateRoute(){try{const payload={user_id:session.user.id,name:`${activeRoute.name} copy`,source_filename:activeRoute.source_filename,route_kind:activeRoute.route_kind,geojson:geojson(activeRoute.points),waypoints:activeRoute.waypoints||[],distance_miles:activeRoute.distance_miles,elevation_gain_ft:activeRoute.elevation_gain_ft};const {data,error}=await supabase.from('adventure_routes').insert(payload).select().single();if(error)throw error;routes.unshift({...data,points:[...activeRoute.points]});selectRoute(routes[0]);toast('GPX duplicated.')}catch(e){toast(e.message)}}
async function deleteRoute(){if(!confirm('Delete this GPX route?'))return;try{const id=activeRoute.id;const {error}=await supabase.from('adventure_routes').delete().eq('id',id);if(error)throw error;routes=routes.filter(r=>r.id!==id);activeRoute=null;trackLayer&&map.removeLayer(trackLayer);waypointLayer.clearLayers();renderRoutes();renderEditor();renderWaypoints();$('#adventureNavPanel').classList.add('hidden');toast('Deleted.')}catch(e){toast(e.message)}}
async function addWaypoint(lat,lon){if(!activeRoute){openSheet('advGpxSheet');return toast('Select a GPX file first.')}const name=prompt('Waypoint name','New point');if(name===null)return;const points=[...(activeRoute.waypoints||[]),{lat,lon,name:name||'Waypoint'}];try{await persistRoute({waypoints:points});renderWaypoints();toast('Waypoint added.')}catch(e){toast(e.message)}}
async function updatePointName(i,name){const pts=[...(activeRoute.waypoints||[])];pts[i]={...pts[i],name};try{await persistRoute({waypoints:pts});renderWaypoints()}catch(e){toast(e.message)}}
async function deletePoint(i){const pts=[...(activeRoute.waypoints||[])];pts.splice(i,1);try{await persistRoute({waypoints:pts});renderWaypoints()}catch(e){toast(e.message)}}
function fit(){if(trackLayer)map.fitBounds(trackLayer.getBounds(),{padding:[50,50]});else center()}
function updateStats(){if(!activeRoute||!lastFix)return;let best={i:0,d:Infinity};activeRoute.points.forEach((p,i)=>{const d=miles(lastFix,p);if(d<best.d)best={i,d}});const covered=total(activeRoute.points.slice(0,best.i+1)),all=Number(activeRoute.distance_miles)||total(activeRoute.points),rem=Math.max(0,all-covered);$('#advProgress').textContent=`${Math.min(100,Math.round(covered/Math.max(all,.001)*100))}%`;$('#advRemaining').textContent=`${rem.toFixed(1)} mi`;$('#advOffRoute').textContent=best.d<.05?'ON TRACK':`${Math.round(best.d*5280)} ft`;$('#advOffRoute').classList.toggle('warn',best.d>=.1)}
function drawRange(){if(!lastFix)return toast('Waiting for GPS.');const mi=Number($('#advRange').value);if(!mi)return;rangeCircle&&map.removeLayer(rangeCircle);rangeCircle=L.circle([lastFix.lat,lastFix.lon],{radius:mi*1609.344,weight:2,fillOpacity:.08}).addTo(map);map.fitBounds(rangeCircle.getBounds());openSheet(null)}
window.addEventListener('moto-road-update',e=>{const d=e.detail||{};if($('#advRoad'))$('#advRoad').textContent=d.road||'Unknown';if($('#advLimit'))$('#advLimit').textContent=Number.isFinite(d.limit_mph)?`${d.limit_mph}`:'--'});
const observer=new MutationObserver(nav);observer.observe(document.querySelector('#app')||document.body,{childList:true,subtree:false});supabase.auth.onAuthStateChange((_e,s)=>{session=s;setTimeout(nav,0)});supabase.auth.getSession().then(({data})=>{session=data.session;nav()});