import { supabase } from './supabase.js';
const $=q=>document.querySelector(q),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
let session,bikes=[];
const name=b=>[b.year,b.make,b.model].filter(Boolean).join(' ')||b.name||'Motorcycle';
function mpg(entries){const f=entries.filter(x=>x.full_tank);let mi=0,g=0;for(let i=1;i<f.length;i++){const d=Number(f[i].odometer_miles)-Number(f[i-1].odometer_miles);if(d>0&&d<2000){mi+=d;g+=Number(f[i].gallons||0)}}return g?mi/g:null}
async function intel(b){const [f,m,t,r]=await Promise.all([supabase.from('fuel_entries').select('*').eq('bike_id',b.id).order('odometer_miles'),supabase.from('maintenance_intervals').select('*').eq('bike_id',b.id).eq('enabled',true),supabase.from('tire_profiles').select('*').eq('bike_id',b.id).eq('active',true).limit(1).maybeSingle(),supabase.from('ride_sessions').select('duration_seconds').eq('bike_id',b.id).eq('status','complete')]);return {fuel:f.data||[],maint:m.data||[],tire:t.data,rides:r.data||[]}}
async function render(force=false){const main=$('#main');if(!main||!/Motorcycles|Overview/i.test(main.textContent||''))return;if($('#garageIntelligence')&&!force)return;$('#garageIntelligence')?.remove();const s=document.createElement('section');s.id='garageIntelligence';s.className='garageIntel';s.innerHTML='<div class="garageIntelHead"><div><small>GARAGE HEALTH</small><h2>Fleet intelligence</h2></div><button id="refreshGarageIntel">↻</button></div><div id="garageIntelGrid" class="garageIntelGrid"><p>Loading…</p></div>';main.prepend(s);$('#refreshGarageIntel').onclick=()=>render(true);const cards=[];for(const b of bikes){const d=await intel(b),hours=d.rides.reduce((a,x)=>a+Number(x.duration_seconds||0),0)/3600,odo=Number(b.odometer||0),economy=mpg(d.fuel),due=d.maint.map(x=>({name:x.item_name,left:n(x.interval_miles)!==null?Number(x.interval_miles)-(odo-Number(x.last_service_miles||0)):Infinity})).sort((a,z)=>a.left-z.left)[0],used=d.tire?Math.max(0,odo-Number(d.tire.installed_odometer_miles||odo)):0;cards.push(`<article><h3>${esc(name(b))}</h3><div><span><small>ODOMETER</small><b>${odo.toFixed(0)} mi</b></span><span><small>RIDE HOURS</small><b>${hours.toFixed(1)} hr</b></span><span><small>FUEL ECONOMY</small><b>${economy?economy.toFixed(1)+' mpg':'—'}</b></span><span><small>NEXT SERVICE</small><b>${due?esc(due.name):'Not set'}</b></span><span><small>ACTIVE TIRES</small><b>${d.tire?esc(d.tire.name):'Not set'}</b></span><span><small>TIRE MILES</small><b>${d.tire?used.toFixed(0)+' mi':'—'}</b></span></div><footer><button data-fuel="${b.id}">FUEL</button><button data-service="${b.id}">SERVICE</button><button data-tires="${b.id}">TIRES</button></footer></article>`)}$('#garageIntelGrid').innerHTML=cards.join('')||'<p>Add a motorcycle first.</p>';document.querySelectorAll('[data-fuel]').forEach(x=>x.onclick=()=>fuel(bikes.find(b=>b.id===x.dataset.fuel)));document.querySelectorAll('[data-service]').forEach(x=>x.onclick=()=>service(bikes.find(b=>b.id===x.dataset.service)));document.querySelectorAll('[data-tires]').forEach(x=>x.onclick=()=>tires(bikes.find(b=>b.id===x.dataset.tires)))}
async function fuel(b){const odometer=Number(prompt('Current odometer:',b.odometer||0)),gallons=Number(prompt('Gallons added:','2')),total_cost=Number(prompt('Total cost:','0')),tank_capacity_gallons=Number(prompt('Tank capacity gallons:',''));if(!Number.isFinite(odometer)||!Number.isFinite(gallons)||gallons<=0)return;await supabase.from('fuel_entries').insert({user_id:session.user.id,bike_id:b.id,odometer_miles:odometer,gallons,total_cost:Number.isFinite(total_cost)?total_cost:0,full_tank:confirm('Was this a full fill-up?')});await supabase.from('bike_trip_settings').upsert({bike_id:b.id,user_id:session.user.id,tank_capacity_gallons:Number.isFinite(tank_capacity_gallons)&&tank_capacity_gallons>0?tank_capacity_gallons:null,last_fill_odometer:odometer,miles_since_fill:0,updated_at:new Date().toISOString()});render(true)}
async function service(b){const item_name=prompt('Maintenance item:');if(!item_name)return;const interval_miles=n(prompt('Interval miles (blank if none):','')),interval_hours=n(prompt('Interval hours (blank if none):','')),last_service_miles=n(prompt('Mileage at last service:',b.odometer||0)),last_service_hours=n(prompt('Ride hours at last service:','0'));await supabase.from('maintenance_intervals').insert({user_id:session.user.id,bike_id:b.id,item_name,interval_miles,interval_hours,last_service_miles:last_service_miles||0,last_service_hours:last_service_hours||0,last_service_at:new Date().toISOString()});render(true)}
async function tires(b){const profile=prompt('Profile name (example: Supermoto set):');if(!profile)return;const wheel_setup=prompt('Wheel setup:',''),front_tire=prompt('Front tire:',''),rear_tire=prompt('Rear tire:',''),front_psi=n(prompt('Front PSI:','')),rear_psi=n(prompt('Rear PSI:','')),expected_life_miles=n(prompt('Expected life miles:','4000'));await supabase.from('tire_profiles').update({active:false}).eq('bike_id',b.id);await supabase.from('tire_profiles').insert({user_id:session.user.id,bike_id:b.id,name:profile,wheel_setup,front_tire,rear_tire,front_psi,rear_psi,installed_odometer_miles:Number(b.odometer||0),expected_life_miles,active:true});render(true)}
async function init(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!s)return;const {data}=await supabase.from('bikes').select('*');bikes=data||[];new MutationObserver(()=>queueMicrotask(()=>render())).observe(document.body,{childList:true,subtree:true});render()}
init();