import { supabase } from './supabase.js';

const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const finite=value=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))?Number(value):null;
const esc=(value='')=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const rad=value=>value*Math.PI/180;
const milesBetween=(a,b)=>{if(!a||!b)return 0;const R=3958.7613,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const bearingBetween=(a,b)=>{if(!a||!b)return 0;const y=Math.sin(rad(b.lon-a.lon))*Math.cos(rad(b.lat)),x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lon-a.lon));return(Math.atan2(y,x)*180/Math.PI+360)%360};
const compass=value=>['N','NE','E','SE','S','SW','W','NW'][Math.round(((value||0)%360)/45)%8];
const formatTime=milliseconds=>{const total=Math.max(0,Math.floor(milliseconds/10)),minutes=Math.floor(total/6000),seconds=Math.floor(total%6000/100),hundredths=total%100;return`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${String(hundredths).padStart(2,'0')}`};

const MODE_KEY='motoRideExperienceModeV2';
const ROAD_KEY='motoRideRoadDNA-v3';
const LAPS_KEY='motoRideRaceSessions-v3';
const MAP_KEY='motoAdventureProMap-v3';
const TRAIL_KEY='motoTrailBreadcrumb-v3';

const modeProfiles={
  road:{label:'ROAD',name:'Apex Road',tag:'Read the road. Find the rhythm.',accent:'#53a7ff',hot:'#81c6ff',icon:'road'},
  race:{label:'RACE',name:'Track Command',tag:'Every sector. Every degree. Every tenth.',accent:'#ff374f',hot:'#ff8b98',icon:'race'},
  enduro:{label:'ENDURO',name:'Trail Vector',tag:'Climb, grip and return-to-start intelligence.',accent:'#ff9b3d',hot:'#ffd08b',icon:'enduro'},
  adventure:{label:'ADV',name:'Expedition Atlas',tag:'Layers, range and remote-route confidence.',accent:'#dbb94c',hot:'#ffe48a',icon:'adventure'}
};

const iconPaths={
  road:'<path d="M8 22 11 2m5 20-3-20M9.6 7h5M9 12h5.4M8.3 17h5.6"/>',
  race:'<path d="M5 21V4m0 1c5-3 8 3 14 0v9c-6 3-9-3-14 0"/>',
  enduro:'<path d="m3 19 6-10 3 5 3-9 6 14H3Zm5-3h8"/>',
  adventure:'<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5 5-2Z"/>',
  tune:'<path d="M4 7h10m4 0h2M4 17h2m4 0h10M14 4v6M6 14v6"/>',
  layers:'<path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/>',
  timer:'<circle cx="12" cy="13" r="8"/><path d="M9 2h6m-3 3v8l4 2"/>',
  route:'<circle cx="5" cy="19" r="2"/><circle cx="19" cy="5" r="2"/><path d="M6.5 17.5c2-3 5-2 6.5-5s.5-4 4.5-6"/>',
  compass:'<circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5 5-2Z"/>',
  mountain:'<path d="m3 20 7-13 3 6 3-4 5 11H3Z"/>',
  satellite:'<path d="m7 17-3 3m13-3 3-3M8 3l13 13-5 5L3 8l5-5Z"/><path d="m12 7 5 5"/>',
  cloud:'<path d="M7 18a4 4 0 1 1 1-7.9A6 6 0 0 1 20 12a3 3 0 0 1-1 6H7Z"/>',
  flag:'<path d="M5 21V4m0 1c5-3 8 3 14 0v9c-6 3-9-3-14 0"/>',
  launch:'<path d="M12 3v18m-5-5 5 5 5-5M5 8l7-5 7 5"/>',
  breadcrumb:'<path d="M4 19c4-9 6 2 10-7 2-5 4-2 6-7"/><circle cx="4" cy="19" r="1.5"/><circle cx="20" cy="5" r="1.5"/>',
  shield:'<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6l-8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/>',
  download:'<path d="M12 3v12m-4-4 4 4 4-4M4 19h16"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
  save:'<path d="M5 3h12l2 2v16H5V3Z"/><path d="M8 3v6h8V3M8 21v-7h8v7"/>',
  eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
  threeD:'<path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/>'
};
const icon=(name,className='')=>`<svg class="rideV3Icon ${className}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${iconPaths[name]||iconPaths.route}</svg>`;

let mode=localStorage.getItem(MODE_KEY)||'road';
if(!modeProfiles[mode])mode='road';
let gps={},road={},ride={},motion={},route={};
let adventureMap=null;
let premiumLayers={};
let activePremiumBase=null;
let previewLayer=null;
let radarLayer=null;
let refreshQueued=false;
let trailPoints=[];
let lastTrailPoint=null;
let lastAltitudePoint=null;
let grade=0;
let raceClock={running:false,startAt:0,elapsed:0,laps:[],lastLapAt:0,armedLaunch:false,launchStart:0,zeroToThirty:null,zeroToSixty:null};

function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function saveJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function roadDNA(){return{curves:78,elevation:62,pavement:'paved',radius:35,avoidHighways:true,avoidTolls:true,avoidFerries:true,...loadJSON(ROAD_KEY,{})}}
function mapSettings(){return{style:'street',tilt:false,grid:false,routeGlow:true,weather:false,contrast:false,...loadJSON(MAP_KEY,{})}}

function toast(message){let node=$('#rideV3Toast');if(!node){node=document.createElement('div');node.id='rideV3Toast';document.body.appendChild(node)}node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2600)}

function setMode(next){
  if(!modeProfiles[next])return;
  mode=next;
  localStorage.setItem(MODE_KEY,next);
  window.MotoRideExperience?.setMode?.(next);
  document.documentElement.dataset.rideMode=next;
  const overlay=$('#rideDashOverlay');
  if(overlay){overlay.dataset.rideMode=next;enhanceRideDashboard(overlay);renderHero(overlay)}
  window.dispatchEvent(new CustomEvent('moto-ride-v3-mode',{detail:{mode:next}}));
}

function modeRibbon(){return`<nav class="rideV3ModeRibbon" aria-label="Ride mode">${Object.entries(modeProfiles).map(([id,profile])=>`<button type="button" data-v3-mode="${id}" class="${id===mode?'active':''}" style="--mode:${profile.accent}">${icon(profile.icon)}<span><small>${profile.label}</small><b>${profile.name}</b></span></button>`).join('')}</nav>`}
function scene(){return`<div class="rideV3Scene" aria-hidden="true"><div class="rideV3Horizon"></div><div class="rideV3RoadGrid"></div><div class="rideV3Orb orb-a"></div><div class="rideV3Orb orb-b"></div><div class="rideV3Machine"><i></i><i></i><i></i><i></i><span></span></div></div>`}
function heroShell(){return`<section id="rideV3Hero" class="rideV3Hero"><div class="rideV3HeroVisual"><div class="rideV3Attitude"><div class="rideV3AttitudeWorld"><span></span></div><div class="rideV3BikeMark"><i class="wheel front"></i><i class="wheel rear"></i><b></b><em></em></div><div class="rideV3AttitudeTicks"></div></div></div><div class="rideV3HeroCopy"><small id="rideV3Eyebrow"></small><h2 id="rideV3Title"></h2><p id="rideV3Tag"></p><div id="rideV3Metrics" class="rideV3Metrics"></div></div><div id="rideV3Actions" class="rideV3Actions"></div></section>`}
function metric(label,value,sub=''){return`<article><small>${esc(label)}</small><strong>${esc(value)}</strong>${sub?`<span>${esc(sub)}</span>`:''}</article>`}
function action(id,ico,label,sub){return`<button type="button" data-v3-action="${id}">${icon(ico)}<span><b>${label}</b><small>${sub}</small></span></button>`}
function currentSpeed(){return finite(ride.speedMph??ride.speed??gps.speed)??0}
function currentHeading(){return finite(gps.heading??ride.heading)??0}
function currentAltitude(){const meters=finite(gps.altitude??ride.altitude);return meters===null?null:meters*3.28084}
function currentLean(){return finite(motion.lean??window.MotoLeanState?.lean)??0}
function currentG(){return finite(motion.accel??window.MotoLeanState?.accel)??1}
function position(){const lat=finite(gps.latitude??ride.latitude),lon=finite(gps.longitude??ride.longitude);return lat===null||lon===null?null:{lat,lon}}
function surfaceConfidence(){const rough=Math.abs(finite(motion.pitch)??0)+Math.max(0,(currentG()-1)*35);if(rough>24)return'ROUGH';if(rough>12)return'MIXED';return'SMOOTH'}

function heroContent(){
  const speed=Math.round(currentSpeed()),heading=currentHeading(),altitude=currentAltitude(),lean=currentLean(),g=currentG(),dna=roadDNA();
  if(mode==='race'){
    const elapsed=raceClock.running?Date.now()-raceClock.startAt+raceClock.elapsed:raceClock.elapsed,best=raceClock.laps.length?Math.min(...raceClock.laps):null;
    return{metrics:[metric('SESSION',formatTime(elapsed),raceClock.running?'LIVE TIMING':'READY'),metric('LEAN',`${Math.abs(lean).toFixed(1)}°`,lean<0?'LEFT':'RIGHT'),metric('LOAD',`${g.toFixed(2)} G`,'MOTION'),metric('BEST',best?formatTime(best):'--:--.--',`${raceClock.laps.length} LAPS`)],actions:[action('race','timer','RACE CONTROL','laps · launch · sectors'),action('sensors','tune','SENSOR ZERO','calibrate attitude'),action('map','route','TRACK MAP','open route tools')]};
  }
  if(mode==='enduro'){
    const start=trailPoints[0],now=position(),homeDistance=start&&now?milesBetween(now,start):0,homeBearing=start&&now?bearingBetween(now,start):0;
    return{metrics:[metric('GRADE',`${grade>=0?'+':''}${grade.toFixed(1)}%`,grade>=0?'CLIMB':'DESCENT'),metric('ALTITUDE',altitude===null?'--':`${Math.round(altitude)} FT`,'GPS'),metric('HOME',start?`${homeDistance.toFixed(1)} MI`:'SET START',start?`${compass(homeBearing)} ${Math.round(homeBearing)}°`:'BREADCRUMB'),metric('GRIP',surfaceConfidence(),'TERRAIN ESTIMATE')],actions:[action('trail','breadcrumb','TRAIL VECTOR','breadcrumb · return'),action('map','layers','TOPO LAB','terrain layers'),action('mark','flag','MARK HAZARD','save trail point')]};
  }
  if(mode==='adventure'){
    const accuracy=finite(gps.accuracy),routeName=route.name||'No active route';
    return{metrics:[metric('HEADING',`${compass(heading)} ${Math.round(heading)}°`,'COURSE'),metric('ALTITUDE',altitude===null?'--':`${Math.round(altitude)} FT`,'ELEVATION'),metric('GPS',accuracy===null?'WAITING':`±${Math.round(accuracy*3.28084)} FT`,accuracy!==null&&accuracy<10?'STRONG LOCK':'SEARCHING'),metric('ROUTE',routeName,route.distance_miles?`${Number(route.distance_miles).toFixed(1)} MI`:'EXPLORE')],actions:[action('map','layers','ATLAS PRO','layers · radar · 3D'),action('scout','search','ROAD SCOUT','curves · surface'),action('expedition','shield','EXPEDITION','range · readiness')]};
  }
  const limit=finite(road.limit_mph),roadName=road.road||road.name||'Road context loading';
  return{metrics:[metric('SPEED',`${speed} MPH`,limit?`${Math.round(limit)} LIMIT`:'GPS'),metric('ROAD',roadName,road.surface||'LIVE CONTEXT'),metric('CURVE DNA',`${dna.curves}%`,dna.curves>70?'TECHNICAL':'FLOWING'),metric('SURFACE',dna.pavement.toUpperCase(),dna.avoidHighways?'NO HIGHWAYS':'FAST TRANSIT')],actions:[action('road','tune','ROAD DNA','curves · surface · avoid'),action('scout','search','FIND ROADS','OSM road scout'),action('map','route','ROUTE STUDIO','open map planner')]};
}

function renderHero(overlay=$('#rideDashOverlay')){
  const hero=$('#rideV3Hero',overlay);if(!hero)return;
  const profile=modeProfiles[mode],content=heroContent();overlay.dataset.rideMode=mode;overlay.style.setProperty('--v3-accent',profile.accent);overlay.style.setProperty('--v3-hot',profile.hot);
  $('#rideV3Eyebrow',hero).textContent=`${profile.label} / MOTO MISSION RIDE OS`;$('#rideV3Title',hero).textContent=profile.name;$('#rideV3Tag',hero).textContent=profile.tag;$('#rideV3Metrics',hero).innerHTML=content.metrics.join('');$('#rideV3Actions',hero).innerHTML=content.actions.join('');
  $$('.rideV3ModeRibbon [data-v3-mode]',overlay).forEach(button=>button.classList.toggle('active',button.dataset.v3Mode===mode));bindActions(overlay);
  const lean=currentLean(),pitch=finite(motion.pitch)??0,world=$('.rideV3AttitudeWorld',hero),bike=$('.rideV3BikeMark',hero);if(world)world.style.transform=`translateY(${clamp(pitch,-25,25)*.55}px) rotate(${-lean}deg)`;if(bike)bike.style.transform=`translate(-50%,-50%) rotate(${lean*.42}deg) rotateY(${clamp(lean,-40,40)*.35}deg)`;
}
function bindActions(root=document){$$('[data-v3-mode]',root).forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='1';button.onclick=()=>setMode(button.dataset.v3Mode)});$$('[data-v3-action]',root).forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='1';button.onclick=()=>runAction(button.dataset.v3Action)})}
function fragment(html){const template=document.createElement('template');template.innerHTML=html.trim();return template.content.firstElementChild}
function enhanceRideDashboard(overlay){
  if(!overlay?.isConnected)return;overlay.dataset.rideOs='v3';if(!$('.rideV3Scene',overlay))overlay.prepend(fragment(scene()));const dash=$('.rideDash',overlay);
  if(dash&&!$('.rideV3ModeRibbon',dash)){const header=$(':scope > header',dash);header?.insertAdjacentElement('afterend',fragment(modeRibbon()))}
  if(dash&&!$('#rideV3Hero',dash)){const ribbon=$('.rideV3ModeRibbon',dash);ribbon?.insertAdjacentElement('afterend',fragment(heroShell()))}
  const actions=$('.dashHeaderActions',overlay);if(actions&&!$('#rideV3Studio',actions)){const button=document.createElement('button');button.id='rideV3Studio';button.type='button';button.className='rideV3StudioButton';button.innerHTML=`${icon('tune')}<span>STUDIO</span>`;button.onclick=()=>openStudio();actions.insertBefore(button,$('#dashStyle',actions)||actions.firstChild)}
  bindActions(overlay);renderHero(overlay)
}

function sheet(id,title,subtitle,body,className=''){$(`#${id}`)?.remove();const overlay=document.createElement('div');overlay.id=id;overlay.className=`rideV3Sheet ${className}`;overlay.innerHTML=`<section role="dialog" aria-modal="true"><header><div><small>MOTO MISSION / RIDE OS 3</small><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><button type="button" data-v3-close aria-label="Close">${icon('close')}</button></header><div class="rideV3SheetBody">${body}</div></section>`;document.body.appendChild(overlay);overlay.onclick=event=>{if(event.target===overlay||event.target.closest('[data-v3-close]'))overlay.remove()};return overlay}
function studioCards(){return Object.entries(modeProfiles).map(([id,profile])=>`<button type="button" data-studio-mode="${id}" class="rideV3ModeCard ${id===mode?'active':''}" style="--mode:${profile.accent}"><span class="rideV3ModeCardVisual">${icon(profile.icon)}<i></i><i></i></span><span><small>${profile.label}</small><strong>${profile.name}</strong><em>${profile.tag}</em></span><b>${id===mode?icon('check'):''}</b></button>`).join('')}
function openStudio(){const modal=sheet('rideV3StudioSheet','Ride Studio','Choose a purpose-built cockpit. Every mode changes its visual language and high-value tools.',`<div class="rideV3ModeCards">${studioCards()}</div><div class="rideV3StudioGrid"><button data-studio-action="appearance">${icon('layers')}<span><b>DISPLAY DESIGNER</b><small>Themes, gauges and layouts</small></span></button><button data-studio-action="road">${icon('road')}<span><b>ROAD DNA</b><small>Curves and surface preferences</small></span></button><button data-studio-action="map">${icon('threeD')}<span><b>ATLAS PRO</b><small>Map layers and 3D tilt</small></span></button><button data-studio-action="race">${icon('timer')}<span><b>RACE CONTROL</b><small>Laps and launch metrics</small></span></button></div>`,'studio');$$('[data-studio-mode]',modal).forEach(button=>button.onclick=()=>{setMode(button.dataset.studioMode);modal.remove()});$$('[data-studio-action]',modal).forEach(button=>button.onclick=()=>{modal.remove();runAction(button.dataset.studioAction)})}
function runAction(actionId){const actions={road:openRoadDNA,race:openRaceControl,trail:openTrailVector,map:openAtlas,scout:openAdventureScout,expedition:openExpedition,appearance:()=>$('#dashStyle')?.click(),sensors:()=>window.MotoRideTools?.getState?.().motionEnabled?window.MotoRideTools?.recalibrate?.():window.MotoRideTools?.enableSensors?.(),mark:()=>window.MotoRideTools?.markRoad?.()};const result=actions[actionId]?.();if(!actions[actionId])toast('Tool is still loading.');return result}

function openRoadDNA(){
  const settings=roadDNA(),modal=sheet('rideV3RoadSheet','Road DNA','Define the kind of ride you want, then send those preferences into Road Scout.',`<div class="rideV3DNAHero"><div class="rideV3DNAPath"><i></i><i></i><i></i><i></i></div><div><small>LIVE ROUTE PERSONALITY</small><strong id="roadDnaName">${settings.curves>75?'TECHNICAL TWISTIES':settings.curves>45?'FLOWING BACKROADS':'RELAXED TOUR'}</strong><p id="roadDnaSummary"></p></div></div><div class="rideV3SliderGrid"><label><span><b>CURVE APPETITE</b><output id="roadCurvesOut">${settings.curves}%</output></span><input id="roadCurves" type="range" min="0" max="100" value="${settings.curves}"></label><label><span><b>ELEVATION BIAS</b><output id="roadElevationOut">${settings.elevation}%</output></span><input id="roadElevation" type="range" min="0" max="100" value="${settings.elevation}"></label><label><span><b>SEARCH RADIUS</b><output id="roadRadiusOut">${settings.radius} MI</output></span><input id="roadRadius" type="range" min="5" max="100" step="5" value="${settings.radius}"></label></div><div class="rideV3Segment"><button data-surface="paved" class="${settings.pavement==='paved'?'active':''}">PAVED</button><button data-surface="mixed" class="${settings.pavement==='mixed'?'active':''}">MIXED</button><button data-surface="unpaved" class="${settings.pavement==='unpaved'?'active':''}">UNPAVED</button></div><div class="rideV3ToggleList"><label><span><b>Avoid highways</b><small>Bias toward secondary roads</small></span><input id="roadAvoidHighways" type="checkbox" ${settings.avoidHighways?'checked':''}></label><label><span><b>Avoid tolls</b><small>Exclude tolled ways when tagged</small></span><input id="roadAvoidTolls" type="checkbox" ${settings.avoidTolls?'checked':''}></label><label><span><b>Avoid ferries</b><small>Keep the route on land</small></span><input id="roadAvoidFerries" type="checkbox" ${settings.avoidFerries?'checked':''}></label></div><div class="rideV3Footer"><button id="roadSave">SAVE PROFILE</button><button id="roadScout" class="primary">${icon('search')} SCOUT ROADS</button></div>`,'road');
  let surface=settings.pavement;const read=()=>({curves:+$('#roadCurves',modal).value,elevation:+$('#roadElevation',modal).value,radius:+$('#roadRadius',modal).value,pavement:surface,avoidHighways:$('#roadAvoidHighways',modal).checked,avoidTolls:$('#roadAvoidTolls',modal).checked,avoidFerries:$('#roadAvoidFerries',modal).checked});const sync=()=>{const value=read();$('#roadCurvesOut',modal).textContent=`${value.curves}%`;$('#roadElevationOut',modal).textContent=`${value.elevation}%`;$('#roadRadiusOut',modal).textContent=`${value.radius} MI`;$('#roadDnaName',modal).textContent=value.curves>75?'TECHNICAL TWISTIES':value.curves>45?'FLOWING BACKROADS':'RELAXED TOUR';$('#roadDnaSummary',modal).textContent=`${value.pavement.toUpperCase()} · ${value.avoidHighways?'BACKROADS':'FAST TRANSIT'} · ${value.elevation}% ELEVATION`};$$('input',modal).forEach(input=>input.oninput=sync);$$('[data-surface]',modal).forEach(button=>button.onclick=()=>{surface=button.dataset.surface;$$('[data-surface]',modal).forEach(item=>item.classList.toggle('active',item===button));sync()});$('#roadSave',modal).onclick=()=>{saveJSON(ROAD_KEY,read());toast('Road DNA saved.');renderHero();modal.remove()};$('#roadScout',modal).onclick=()=>{saveJSON(ROAD_KEY,read());modal.remove();openAdventureScout()};sync()
}

function raceState(){return{...raceClock,elapsed:raceClock.running?Date.now()-raceClock.startAt+raceClock.elapsed:raceClock.elapsed}}
function openRaceControl(){
  const modal=sheet('rideV3RaceSheet','Race Control','Manual and GPS-assisted timing with lean, load and launch performance.',`<div class="rideV3RaceHero"><div class="rideV3Tach"><i></i><i></i><strong id="raceLiveSpeed">${Math.round(currentSpeed())}</strong><small>MPH</small></div><div><small>SESSION CLOCK</small><strong id="raceClock">${formatTime(raceState().elapsed)}</strong><span id="raceState">${raceClock.running?'LIVE':'READY'}</span></div></div><div class="rideV3RaceMetrics"><article><small>LEAN</small><strong id="raceLean">${Math.abs(currentLean()).toFixed(1)}°</strong></article><article><small>LOAD</small><strong id="raceG">${currentG().toFixed(2)} G</strong></article><article><small>0–30</small><strong id="raceThirty">${raceClock.zeroToThirty?`${(raceClock.zeroToThirty/1000).toFixed(2)}s`:'--'}</strong></article><article><small>0–60</small><strong id="raceSixty">${raceClock.zeroToSixty?`${(raceClock.zeroToSixty/1000).toFixed(2)}s`:'--'}</strong></article></div><div class="rideV3RaceButtons"><button id="raceStart">${raceClock.running?'PAUSE':'START'}</button><button id="raceLap" class="primary">${icon('flag')} LAP</button><button id="raceLaunch">${icon('launch')} ARM LAUNCH</button><button id="raceReset">RESET</button></div><div class="rideV3LapTable"><header><span>LAP</span><span>TIME</span><span>DELTA</span></header><div id="raceLaps"></div></div>`,'race');
  const render=()=>{const state=raceState(),best=state.laps.length?Math.min(...state.laps):null;$('#raceClock',modal).textContent=formatTime(state.elapsed);$('#raceState',modal).textContent=state.running?'LIVE':'READY';$('#raceStart',modal).textContent=state.running?'PAUSE':'START';$('#raceLiveSpeed',modal).textContent=Math.round(currentSpeed());$('#raceLean',modal).textContent=`${Math.abs(currentLean()).toFixed(1)}°`;$('#raceG',modal).textContent=`${currentG().toFixed(2)} G`;$('#raceThirty',modal).textContent=state.zeroToThirty?`${(state.zeroToThirty/1000).toFixed(2)}s`:'--';$('#raceSixty',modal).textContent=state.zeroToSixty?`${(state.zeroToSixty/1000).toFixed(2)}s`:'--';$('#raceLaunch',modal).classList.toggle('armed',state.armedLaunch);$('#raceLaunch',modal).textContent=state.armedLaunch?'LAUNCH ARMED':'ARM LAUNCH';$('#raceLaps',modal).innerHTML=state.laps.length?state.laps.map((lap,index)=>`<div><span>${index+1}</span><b>${formatTime(lap)}</b><em class="${lap===best?'best':''}">${lap===best?'BEST':`${lap-best>=0?'+':''}${((lap-best)/1000).toFixed(2)}`}</em></div>`).join(''):'<p>Complete a lap to build the session table.</p>'};
  $('#raceStart',modal).onclick=()=>{if(raceClock.running){raceClock.elapsed=Date.now()-raceClock.startAt+raceClock.elapsed;raceClock.running=false}else{raceClock.startAt=Date.now();raceClock.running=true;raceClock.lastLapAt=raceClock.startAt}render()};$('#raceLap',modal).onclick=()=>{if(!raceClock.running)return toast('Start the session clock first.');const now=Date.now(),lap=now-raceClock.lastLapAt;if(lap<3000)return toast('Lap is too short.');raceClock.laps.push(lap);raceClock.lastLapAt=now;saveRaceSession();render()};$('#raceLaunch',modal).onclick=()=>{raceClock.armedLaunch=!raceClock.armedLaunch;raceClock.launchStart=0;raceClock.zeroToThirty=null;raceClock.zeroToSixty=null;render();toast(raceClock.armedLaunch?'Launch timer armed. Begin from a stop.':'Launch timer disarmed.')};$('#raceReset',modal).onclick=()=>{if(!confirm('Reset this race session?'))return;raceClock={running:false,startAt:0,elapsed:0,laps:[],lastLapAt:0,armedLaunch:false,launchStart:0,zeroToThirty:null,zeroToSixty:null};render()};const interval=setInterval(()=>{if(!modal.isConnected)return clearInterval(interval);render()},50);render()
}
function saveRaceSession(){const sessions=loadJSON(LAPS_KEY,[]);sessions.unshift({createdAt:new Date().toISOString(),laps:[...raceClock.laps],best:raceClock.laps.length?Math.min(...raceClock.laps):null,zeroToThirty:raceClock.zeroToThirty,zeroToSixty:raceClock.zeroToSixty});saveJSON(LAPS_KEY,sessions.slice(0,30))}

function openTrailVector(){const start=trailPoints[0],now=position(),homeDistance=start&&now?milesBetween(now,start):0,homeBearing=start&&now?bearingBetween(now,start):0,modal=sheet('rideV3TrailSheet','Trail Vector','Breadcrumb navigation, terrain attitude and a direct return-to-start reference.',`<div class="rideV3TrailCompass"><div style="--heading:${currentHeading()}deg"><span>N</span><span>E</span><span>S</span><span>W</span><i></i></div><strong>${compass(currentHeading())}</strong><small>${Math.round(currentHeading())}°</small></div><div class="rideV3TrailMetrics">${metric('BREADCRUMBS',String(trailPoints.length),'GPS POINTS')}${metric('HOME',start?`${homeDistance.toFixed(2)} MI`:'NOT SET',start?`${compass(homeBearing)} ${Math.round(homeBearing)}°`:'')}${metric('GRADE',`${grade>=0?'+':''}${grade.toFixed(1)}%`,grade>=0?'CLIMB':'DESCENT')}${metric('SURFACE',surfaceConfidence(),'MOTION')}</div><div class="rideV3ElevationProfile" id="trailProfile"></div><div class="rideV3Footer"><button id="trailSetHome">${icon('flag')} SET START</button><button id="trailClear">CLEAR TRAIL</button><button id="trailMap" class="primary">${icon('layers')} OPEN TOPO</button></div>`,'trail');renderElevationProfile($('#trailProfile',modal));$('#trailSetHome',modal).onclick=()=>{const point=position();if(!point)return toast('Waiting for GPS.');trailPoints=[{...point,altitude:currentAltitude(),at:Date.now()}];lastTrailPoint=trailPoints[0];saveJSON(TRAIL_KEY,trailPoints);toast('Return point set.');modal.remove();openTrailVector()};$('#trailClear',modal).onclick=()=>{trailPoints=[];lastTrailPoint=null;saveJSON(TRAIL_KEY,[]);toast('Breadcrumb trail cleared.');modal.remove()};$('#trailMap',modal).onclick=()=>{modal.remove();openAtlas({preferTopo:true})}}
function renderElevationProfile(node){if(!node)return;const points=trailPoints.filter(point=>Number.isFinite(point.altitude));if(points.length<2){node.innerHTML='<p>Elevation profile builds as you ride.</p>';return}const min=Math.min(...points.map(point=>point.altitude)),max=Math.max(...points.map(point=>point.altitude)),range=Math.max(1,max-min),coords=points.slice(-80).map((point,index,list)=>`${index/(list.length-1)*100},${92-(point.altitude-min)/range*78}`).join(' ');node.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="trailFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="currentColor" stop-opacity=".55"/><stop offset="1" stop-color="currentColor" stop-opacity=".04"/></linearGradient></defs><polyline points="0,100 ${coords} 100,100" fill="url(#trailFill)" stroke="none"/><polyline points="${coords}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/></svg><span>${Math.round(min)} FT</span><b>${Math.round(max)} FT</b>`}

function openExpedition(){const accuracy=finite(gps.accuracy),checks=[['GPS lock',accuracy!==null&&accuracy<25,accuracy===null?'Waiting':`±${Math.round(accuracy*3.28084)} ft`],['Offline shell',Boolean(navigator.serviceWorker?.controller),'App core cached'],['Route library',Boolean(route.name),'Select or import GPX'],['Motion sensors',Boolean(window.MotoLeanState?.motionEnabled),'Optional'],['Network',navigator.onLine,navigator.onLine?'Online':'Offline-ready shell']];sheet('rideV3ExpeditionSheet','Expedition Readiness','A pre-ride systems check for remote navigation and recording.',`<div class="rideV3ReadinessRing" style="--ready:${Math.round(checks.filter(item=>item[1]).length/checks.length*100)}"><strong>${Math.round(checks.filter(item=>item[1]).length/checks.length*100)}%</strong><small>READY</small></div><div class="rideV3CheckList">${checks.map(([label,ok,sub])=>`<div class="${ok?'ok':'wait'}"><span>${ok?icon('check'):icon('cloud')}</span><b>${esc(label)}</b><small>${esc(sub)}</small></div>`).join('')}</div><div class="rideV3Callout"><b>Offline map note</b><p>The app shell and saved GPX data can work offline. Full offline tile packs need a licensed tile source or a self-hosted map package; Moto Mission does not silently scrape commercial map tiles.</p></div>`,'expedition')}

function patchLeaflet(){if(!window.L?.map||window.L.map.__rideV3Patched)return false;const original=window.L.map;function wrapped(...args){const map=original.apply(this,args),target=args[0],element=typeof target==='string'?document.getElementById(target):target;if(element?.id==='adventureMap'){adventureMap=map;window.MotoAdventureMap=map;setTimeout(()=>{registerPremiumLayers();enhanceAdventure($('#adventureOverlay'));applyMapSettings()},0)}return map}Object.assign(wrapped,original);wrapped.__rideV3Patched=true;window.L.map=wrapped;return true}
function registerPremiumLayers(){if(!adventureMap||!window.L)return;premiumLayers={street:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}),voyager:L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'© OpenStreetMap © CARTO'}),dark:L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'© OpenStreetMap © CARTO'}),topo:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenStreetMap · SRTM · OpenTopoMap'}),usgs:L.tileLayer('https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}',{maxZoom:16,attribution:'USGS The National Map'}),satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri World Imagery'}),esriTopo:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri World Topographic Map'}),humanitarian:L.tileLayer('https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap · HOT'})}}
function mapLayerCards(){const items=[['street','Street','Clean road detail','road'],['voyager','Touring','High legibility','route'],['dark','Night','Low-glare cockpit','cloud'],['topo','Open Topo','Contours and trails','mountain'],['usgs','USGS Topo','US public topo','mountain'],['satellite','Satellite','Aerial terrain','satellite'],['esriTopo','Terrain','World topographic','layers'],['humanitarian','Detail','Dense road labels','search']];return items.map(([id,label,sub,ico])=>`<button type="button" data-pro-map="${id}">${icon(ico)}<span><b>${label}</b><small>${sub}</small></span></button>`).join('')}
function enhanceAdventure(overlay){if(!overlay?.isConnected)return;overlay.dataset.atlasPro='1';const layersSheet=$('#advLayersSheet',overlay);if(layersSheet&&!$('.rideV3AtlasPanel',layersSheet)){const panel=fragment(`<section class="rideV3AtlasPanel"><div class="rideV3AtlasHead"><div><small>ATLAS PRO / FREE LAYER STACK</small><strong>Choose the map for the mission</strong></div>${icon('threeD')}</div><div class="rideV3MapLayerGrid">${mapLayerCards()}</div><div class="rideV3AtlasToggles"><button type="button" data-map-toggle="tilt">${icon('threeD')}<span><b>3D TILT</b><small>Perspective terrain view</small></span></button><button type="button" data-map-toggle="grid">${icon('layers')}<span><b>MAP GRID</b><small>Navigation reference</small></span></button><button type="button" data-map-toggle="contrast">${icon('eye')}<span><b>TRAIL BOOST</b><small>Increase terrain contrast</small></span></button><button type="button" data-map-toggle="weather">${icon('cloud')}<span><b>RADAR</b><small>Latest RainViewer frame</small></span></button></div><p class="rideV3Attribution">Base-map copyright and usage remain with each named provider. Layers load online and are not bulk-downloaded.</p></section>`);const grid=$('.advLayerGrid',layersSheet);grid?.insertAdjacentElement('afterend',panel);bindAdventure(overlay)}enhanceRoadScout(overlay);addMapCompass(overlay);applyMapSettings()}
function addMapCompass(overlay){if($('#rideV3MapCompass',overlay))return;const node=fragment(`<div id="rideV3MapCompass" class="rideV3MapCompass"><div>${icon('compass')}</div><strong>N</strong></div>`);$('.adventureShell',overlay)?.appendChild(node);updateMapCompass()}
function updateMapCompass(){const node=$('#rideV3MapCompass');if(!node)return;const heading=currentHeading();node.style.setProperty('--heading',`${heading}deg`);$('strong',node).textContent=compass(heading)}
function bindAdventure(overlay){$$('[data-pro-map]',overlay).forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='1';button.onclick=()=>{selectPremiumBase(button.dataset.proMap);saveMapSetting('style',button.dataset.proMap)}});$$('[data-map-toggle]',overlay).forEach(button=>{if(button.dataset.bound)return;button.dataset.bound='1';button.onclick=()=>toggleMapFeature(button.dataset.mapToggle)})}
function saveMapSetting(key,value){const settings=mapSettings();settings[key]=value;saveJSON(MAP_KEY,settings);syncMapControls()}
function selectPremiumBase(id){if(!adventureMap||!premiumLayers[id])return toast('Map engine is still loading.');Object.values(premiumLayers).forEach(layer=>{if(adventureMap.hasLayer(layer))adventureMap.removeLayer(layer)});adventureMap.eachLayer(layer=>{if(layer instanceof L.TileLayer&&!Object.values(premiumLayers).includes(layer)&&layer!==radarLayer)adventureMap.removeLayer(layer)});premiumLayers[id].addTo(adventureMap);activePremiumBase=id;if(mapSettings().weather&&radarLayer&&!adventureMap.hasLayer(radarLayer))radarLayer.addTo(adventureMap);setTimeout(()=>adventureMap.invalidateSize(false),50);toast(`${id==='usgs'?'USGS':id.replace(/([A-Z])/g,' $1')} layer active.`);syncMapControls()}
async function toggleMapFeature(feature){const settings=mapSettings();settings[feature]=!settings[feature];saveJSON(MAP_KEY,settings);if(feature==='weather')await setWeatherRadar(settings.weather);applyMapSettings();syncMapControls()}
function applyMapSettings(){const overlay=$('#adventureOverlay');if(!overlay)return;const settings=mapSettings();overlay.classList.toggle('atlas-tilt',Boolean(settings.tilt));overlay.classList.toggle('atlas-grid',Boolean(settings.grid));overlay.classList.toggle('atlas-contrast',Boolean(settings.contrast));if(adventureMap){if(activePremiumBase!==settings.style&&premiumLayers[settings.style])selectPremiumBase(settings.style);setTimeout(()=>adventureMap.invalidateSize(false),200)}syncMapControls()}
function syncMapControls(){const settings=mapSettings();$$('[data-pro-map]').forEach(button=>button.classList.toggle('active',button.dataset.proMap===settings.style));$$('[data-map-toggle]').forEach(button=>button.classList.toggle('active',Boolean(settings[button.dataset.mapToggle])))}
async function setWeatherRadar(enabled){if(!adventureMap||!window.L)return;if(!enabled){if(radarLayer&&adventureMap.hasLayer(radarLayer))adventureMap.removeLayer(radarLayer);return}try{const response=await fetch('https://api.rainviewer.com/public/weather-maps.json');if(!response.ok)throw Error('Radar service unavailable');const data=await response.json(),frame=data.radar?.past?.at(-1);if(!frame?.path)throw Error('No radar frame');if(radarLayer&&adventureMap.hasLayer(radarLayer))adventureMap.removeLayer(radarLayer);radarLayer=L.tileLayer(`https://tilecache.rainviewer.com${frame.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.62,maxZoom:18,attribution:'Weather radar © RainViewer'}).addTo(adventureMap);toast('Latest weather radar loaded.')}catch(error){const settings=mapSettings();settings.weather=false;saveJSON(MAP_KEY,settings);toast(error.message||'Radar unavailable.')}}
function openAtlas(options={}){const nav=$('#adventureNav');if(!$('#adventureOverlay')){if(!nav)return toast('Adventure Map is still loading.');$('#rideDashOverlay')?.remove();nav.click()}const reveal=()=>{const overlay=$('#adventureOverlay');if(!overlay)return setTimeout(reveal,120);enhanceAdventure(overlay);if(options.preferTopo){saveMapSetting('style','topo');selectPremiumBase('topo')}$('#advRoutesSheet')?.classList.remove('open');$('#advLayersSheet')?.classList.add('open');$$('.advBottomBar [data-sheet]').forEach(button=>button.classList.toggle('active',button.dataset.sheet==='advLayersSheet'))};setTimeout(reveal,180)}
function openAdventureScout(){const nav=$('#adventureNav');if(!$('#adventureOverlay')){if(!nav)return toast('Adventure Map is still loading.');$('#rideDashOverlay')?.remove();nav.click()}const reveal=()=>{const overlay=$('#adventureOverlay');if(!overlay)return setTimeout(reveal,120);enhanceAdventure(overlay);$('#advRoutesButton',overlay)?.click();setTimeout(()=>activateScoutTab(overlay),120)};setTimeout(reveal,180)}

function enhanceRoadScout(overlay){const routesSheet=$('#advRoutesSheet',overlay),tabs=$('.advRouteTabs',routesSheet);if(!routesSheet||!tabs||$('#rideV3ScoutTab',routesSheet))return;const tab=document.createElement('button');tab.id='rideV3ScoutTab';tab.type='button';tab.dataset.v3RouteTab='scout';tab.textContent='ROAD SCOUT';tabs.appendChild(tab);const panel=fragment(`<section id="rideV3ScoutPanel" class="rideV3ScoutPanel" data-v3-route-panel hidden><div class="rideV3ScoutHero"><div>${icon('search')}</div><span><small>OPENSTREETMAP DISCOVERY</small><strong>Find nearby roads by shape and surface</strong><p>Scans tagged public road geometry. Always verify access, closures and legal riding conditions.</p></span></div><div class="rideV3ScoutControls"><label>RADIUS <input id="scoutRadius" type="range" min="5" max="60" step="5"><output id="scoutRadiusOut"></output></label><label>CURVE PRIORITY <input id="scoutCurves" type="range" min="0" max="100"><output id="scoutCurvesOut"></output></label><div class="rideV3Segment"><button data-scout-surface="paved">PAVED</button><button data-scout-surface="mixed">MIXED</button><button data-scout-surface="unpaved">UNPAVED</button></div><label class="rideV3ScoutCheck"><input id="scoutAvoidHighways" type="checkbox"><span>Avoid highways and trunk roads</span></label><button id="scoutSearch" class="rideV3ScoutSearch">${icon('search')} SCAN NEARBY ROADS</button></div><div id="rideV3ScoutStatus" class="rideV3ScoutStatus">Ready to scan.</div><div id="rideV3ScoutResults" class="rideV3ScoutResults"></div></section>`);routesSheet.appendChild(panel);tab.onclick=()=>activateScoutTab(overlay);initializeScoutControls(panel);bindAdventure(overlay)}
function activateScoutTab(overlay=$('#adventureOverlay')){const sheet=$('#advRoutesSheet',overlay);if(!sheet)return;$$('[data-route-tab]',sheet).forEach(button=>button.classList.remove('active'));$$('[data-route-panel]',sheet).forEach(panel=>panel.hidden=true);$$('[data-v3-route-tab]',sheet).forEach(button=>button.classList.toggle('active',button.dataset.v3RouteTab==='scout'));$$('[data-v3-route-panel]',sheet).forEach(panel=>panel.hidden=panel.id!=='rideV3ScoutPanel')}
function initializeScoutControls(panel){const settings=roadDNA();let surface=settings.pavement;$('#scoutRadius',panel).value=settings.radius;$('#scoutCurves',panel).value=settings.curves;$('#scoutAvoidHighways',panel).checked=settings.avoidHighways;const sync=()=>{$('#scoutRadiusOut',panel).textContent=`${$('#scoutRadius',panel).value} MI`;$('#scoutCurvesOut',panel).textContent=`${$('#scoutCurves',panel).value}%`;$$('[data-scout-surface]',panel).forEach(button=>button.classList.toggle('active',button.dataset.scoutSurface===surface))};$$('[data-scout-surface]',panel).forEach(button=>button.onclick=()=>{surface=button.dataset.scoutSurface;sync()});$$('input[type=range]',panel).forEach(input=>input.oninput=sync);$('#scoutSearch',panel).onclick=()=>scanRoads({radius:+$('#scoutRadius',panel).value,curves:+$('#scoutCurves',panel).value,pavement:surface,avoidHighways:$('#scoutAvoidHighways',panel).checked},panel);sync()}
async function scanRoads(preferences,panel){const center=position()||(adventureMap?{lat:adventureMap.getCenter().lat,lon:adventureMap.getCenter().lng}:null),status=$('#rideV3ScoutStatus',panel),results=$('#rideV3ScoutResults',panel);if(!center)return toast('Waiting for GPS or map position.');status.textContent='Scanning OpenStreetMap road geometry…';results.innerHTML='<div class="rideV3Loading"><i></i><span>Analyzing curves and surfaces</span></div>';const radiusMeters=Math.round(preferences.radius*1609.344),highwayFilter=preferences.avoidHighways?'[highway!~"motorway|trunk"]':'';const query=`[out:json][timeout:25];way(around:${radiusMeters},${center.lat},${center.lon})[highway]${highwayFilter}[access!="private"][motor_vehicle!="no"];out tags geom;`;try{const response=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:`data=${encodeURIComponent(query)}`});if(!response.ok)throw Error(`Road scan failed (${response.status})`);const data=await response.json(),ranked=(data.elements||[]).map(element=>scoreRoad(element,center,preferences)).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,18);status.textContent=ranked.length?`${ranked.length} candidate roads ranked · tap Preview or Save`:'No matching roads found. Increase the radius or use Mixed surface.';results.innerHTML=ranked.length?ranked.map((roadItem,index)=>roadCard(roadItem,index)).join(''):'<div class="rideV3Empty">No road geometry matched this profile.</div>';$$('[data-preview-road]',results).forEach(button=>button.onclick=()=>previewRoad(ranked[+button.dataset.previewRoad]));$$('[data-save-road]',results).forEach(button=>button.onclick=()=>saveScoutedRoad(ranked[+button.dataset.saveRoad],preferences,button))}catch(error){status.textContent=error.message||'Road scan failed.';results.innerHTML='<div class="rideV3Empty">The free OSM query service may be busy. Try a smaller radius.</div>'}}
function scoreRoad(element,center,preferences){const geometry=(element.geometry||[]).map(point=>({lat:+point.lat,lon:+point.lon})).filter(point=>Number.isFinite(point.lat)&&Number.isFinite(point.lon));if(geometry.length<4)return null;let length=0,bend=0;for(let index=1;index<geometry.length;index++)length+=milesBetween(geometry[index-1],geometry[index]);if(length<.35)return null;for(let index=2;index<geometry.length;index++){let delta=Math.abs(bearingBetween(geometry[index-2],geometry[index-1])-bearingBetween(geometry[index-1],geometry[index]));if(delta>180)delta=360-delta;bend+=Math.min(delta,90)}const curveScore=clamp(bend/Math.max(length,1)*1.5,0,100),tags=element.tags||{},surface=classifySurface(tags),surfaceMatch=preferences.pavement==='mixed'?90:surface===preferences.pavement?100:surface==='unknown'?48:8,curveMatch=100-Math.abs(curveScore-preferences.curves),distance=milesBetween(center,geometry[Math.floor(geometry.length/2)]),accessPenalty=/private|no/.test(tags.access||'')?100:0,score=curveMatch*.52+surfaceMatch*.36+clamp(100-distance/preferences.radius*100,0,100)*.12-accessPenalty;return{id:element.id,name:tags.name||tags.ref||`${(tags.highway||'road').replace(/_/g,' ')} ${element.id}`,highway:tags.highway||'road',surface,rawSurface:tags.surface||tags.tracktype||'not tagged',length,curveScore,distance,geometry,tags,score}}
function classifySurface(tags){const value=String(tags.surface||'').toLowerCase(),highway=String(tags.highway||'').toLowerCase();if(/asphalt|concrete|paved|paving_stones|sett/.test(value))return'paved';if(/gravel|dirt|ground|unpaved|compacted|fine_gravel|sand|mud|earth|grass/.test(value)||highway==='track')return'unpaved';return'unknown'}
function roadCard(item,index){return`<article class="rideV3RoadCard"><div class="rideV3RoadScore"><strong>${Math.round(item.curveScore)}</strong><small>CURVE</small></div><div><small>${esc(item.highway.toUpperCase())} · ${esc(item.surface.toUpperCase())}</small><h3>${esc(item.name)}</h3><p>${item.length.toFixed(1)} mi geometry · ${item.distance.toFixed(1)} mi away · ${esc(item.rawSurface)}</p><div class="rideV3RoadBar"><i style="width:${item.curveScore}%"></i></div></div><div><button data-preview-road="${index}">${icon('eye')} PREVIEW</button><button data-save-road="${index}" class="primary">${icon('save')} SAVE</button></div></article>`}
function previewRoad(item){if(!adventureMap||!window.L)return toast('Map is still loading.');if(previewLayer)adventureMap.removeLayer(previewLayer);previewLayer=L.polyline(item.geometry.map(point=>[point.lat,point.lon]),{color:'#33e0ff',weight:7,opacity:.94,dashArray:'2 10',lineCap:'round'}).addTo(adventureMap);adventureMap.fitBounds(previewLayer.getBounds(),{padding:[70,70]});$('#advRoutesSheet')?.classList.remove('open');toast(`Previewing ${item.name}.`)}
async function saveScoutedRoad(item,preferences,button){button.disabled=true;button.textContent='SAVING…';try{const{data:{session}}=await supabase.auth.getSession();if(!session?.user)throw Error('Sign in before saving routes.');const payload={user_id:session.user.id,name:item.name,source_filename:'OpenStreetMap Road Scout',route_kind:'route',geojson:{type:'Feature',properties:{source:'OpenStreetMap',osm_way_id:item.id,highway:item.highway,surface:item.rawSurface,curve_score:Math.round(item.curveScore),planner_preferences:preferences},geometry:{type:'LineString',coordinates:item.geometry.map(point=>[point.lon,point.lat])}},waypoints:[],distance_miles:item.length,elevation_gain_ft:0};const{error}=await supabase.from('adventure_routes').insert(payload);if(error)throw error;toast(`${item.name} saved to Routes.`);$('#closeAdventure')?.click();setTimeout(()=>$('#adventureNav')?.click(),180);setTimeout(()=>$('#advRoutesButton')?.click(),950)}catch(error){toast(error.message||'Could not save road.');button.disabled=false;button.innerHTML=`${icon('save')} SAVE`}}

function updateRaceLaunch(){if(!raceClock.armedLaunch)return;const speed=currentSpeed(),now=performance.now();if(!raceClock.launchStart&&speed>=2){raceClock.launchStart=now;toast('Launch detected.')}if(!raceClock.launchStart)return;const elapsed=now-raceClock.launchStart;if(!raceClock.zeroToThirty&&speed>=30)raceClock.zeroToThirty=elapsed;if(!raceClock.zeroToSixty&&speed>=60){raceClock.zeroToSixty=elapsed;raceClock.armedLaunch=false;saveRaceSession();toast(`0–60 ${(elapsed/1000).toFixed(2)} seconds.`)}}
function updateTrail(){const point=position();if(!point)return;const altitude=currentAltitude(),now={...point,altitude,at:Date.now()};if(!lastTrailPoint||milesBetween(lastTrailPoint,now)>=.015){trailPoints.push(now);trailPoints=trailPoints.slice(-1500);lastTrailPoint=now;if(trailPoints.length%10===0)saveJSON(TRAIL_KEY,trailPoints)}if(lastAltitudePoint&&altitude!==null&&lastAltitudePoint.altitude!==null){const horizontal=milesBetween(lastAltitudePoint,now)*5280;if(horizontal>8)grade=clamp((altitude-lastAltitudePoint.altitude)/horizontal*100,-45,45)}if(!lastAltitudePoint||milesBetween(lastAltitudePoint,now)>.01)lastAltitudePoint=now}
function scheduleRefresh(){if(refreshQueued)return;refreshQueued=true;requestAnimationFrame(()=>{refreshQueued=false;renderHero();updateMapCompass();updateRaceLaunch();updateTrail()})}
function scanDOM(){const dash=$('#rideDashOverlay');if(dash)enhanceRideDashboard(dash);const adventure=$('#adventureOverlay');if(adventure)enhanceAdventure(adventure)}
function boot(){trailPoints=loadJSON(TRAIL_KEY,[]);lastTrailPoint=trailPoints.at(-1)||null;patchLeaflet();setInterval(()=>{patchLeaflet();if(window.MotoAdventureMap&&!adventureMap){adventureMap=window.MotoAdventureMap;registerPremiumLayers();applyMapSettings()}},250);window.addEventListener('moto-ride-dash-opened',event=>enhanceRideDashboard(event.detail?.overlay||$('#rideDashOverlay')));window.addEventListener('moto-ride-dash-rendered',event=>enhanceRideDashboard(event.detail?.overlay||$('#rideDashOverlay')));window.addEventListener('moto-ride-mode-change',event=>{const next=event.detail?.mode||event.detail?.next;if(modeProfiles[next]){mode=next;renderHero()}});window.addEventListener('moto-gps-fix',event=>{gps={...gps,...(event.detail||{})};scheduleRefresh()});window.addEventListener('moto-road-update',event=>{road=event.detail||{};scheduleRefresh()});window.addEventListener('moto-ride-state',event=>{ride=event.detail||{};scheduleRefresh()});window.addEventListener('moto-motion-update',event=>{motion={...motion,...(event.detail||{})};scheduleRefresh()});window.addEventListener('moto-tools-update',event=>{motion={...motion,...(event.detail||{})};scheduleRefresh()});window.addEventListener('moto-route-update',event=>{route=event.detail||{};scheduleRefresh()});new MutationObserver(scanDOM).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',event=>{const button=event.target.closest?.('#advLayersSheet [data-layer]');if(button)setTimeout(()=>{activePremiumBase=null;saveMapSetting('style',button.dataset.layer==='terrain'?'topo':button.dataset.layer);syncMapControls()},0)},true);scanDOM();requestAnimationFrame(function animate(){const sceneNode=$('.rideV3Scene');if(sceneNode){sceneNode.style.setProperty('--scene-lean',`${currentLean()*.18}deg`);sceneNode.style.setProperty('--scene-speed',String(clamp(currentSpeed()/90,0,1)))}requestAnimationFrame(animate)});window.MotoRideOS3={openStudio,openRoadDNA,openRaceControl,openAtlas,openRoadScout:openAdventureScout,getMode:()=>mode,setMode}}
boot();