import { supabase } from './supabase.js';

const $=q=>document.querySelector(q),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,bikes=[],rides=[],active=null,watchId=null,timer=null,lastPos=null,leanOffset=0,motion={ax:null,ay:null,az:null,g:null,alpha:null,beta:null,gamma:null,lean:null,pitch:null,roll:null},buffer=[],distanceMi=0,maxSpeed=0,speedSum=0,speedCount=0,maxAccel=0,maxBrake=0,maxLean=0;

const mph=mps=>Number.isFinite(mps)?mps*2.236936:0,ft=m=>Number.isFinite(m)?m*3.28084:null,fmtTime=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function hav(a,b){const R=3958.7613,toRad=x=>x*Math.PI/180,dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function bikeName(b){return [b.year,b.make,b.model].filter(Boolean).join(' ')||b.name||'Motorcycle'}
function bikeImage(b,cls=''){return b?.image_url?`<img class="${cls}" src="${esc(b.image_url)}" alt="${esc(bikeName(b))}">`:`<div class="bikePhotoPlaceholder ${cls}">🏍</div>`}

async function loadData(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!s)return;const [b,r]=await Promise.all([supabase.from('bikes').select('*').order('created_at'),supabase.from('ride_sessions').select('*').order('started_at',{ascending:false}).limit(25)]);bikes=b.data||[];rides=r.data||[];injectNav()}
function injectNav(){const nav=$('#nav');if(!nav)return;if($('#rideCenterNav'))return;const btn=document.createElement('button');btn.id='rideCenterNav';btn.innerHTML='<span class="navIcon">◉</span><span>Ride Center</span><em>LIVE</em>';btn.onclick=openRideCenter;const ops=[...nav.querySelectorAll('.navGroup')].find(g=>g.querySelector('.navLabel')?.textContent.trim()==='Operations');(ops||nav).appendChild(btn)}

function openRideCenter(){document.querySelector('#rideCenterOverlay')?.remove();const o=document.createElement('div');o.id='rideCenterOverlay';o.innerHTML=`<section class="rideCenter"><header><div><small>IPHONE SENSOR LOGGER</small><h2>Ride Center</h2></div><button id="closeRideCenter">×</button></header><div id="rideCenterBody"></div></section>`;document.body.appendChild(o);$('#closeRideCenter').onclick=()=>{if(!active)o.remove()};renderHome()}
function renderHome(){const body=$('#rideCenterBody');if(!body)return;if(active){renderLive();return}body.innerHTML=`<div class="rideHero"><span class="rideDot"></span><div><small>READY TO RECORD</small><h3>Start a ride</h3><p>Tap Start Ride, choose your motorcycle, then approve GPS and motion access.</p></div></div><button id="rideStart" class="rideStart">START RIDE</button><p class="rideHint">Keep MotoCloud open and the iPhone screen awake while recording. iOS may pause browser sensors when locked or backgrounded.</p><div class="rideHistory"><h3>Recent rides</h3>${rides.length?rides.map(r=>`<article><div><strong>${esc(r.bike_name)}</strong><small>${new Date(r.started_at).toLocaleString()}</small></div><div><b>${Number(r.distance_miles||0).toFixed(1)} mi</b><small>${fmtTime(r.duration_seconds||0)}</small></div></article>`).join(''):'<div class="rideEmpty">No recorded rides yet.</div>'}</div>`;$('#rideStart').onclick=showBikePicker}

function showBikePicker(){document.querySelector('#rideBikePicker')?.remove();const modal=document.createElement('div');modal.id='rideBikePicker';modal.className='rideModal';modal.innerHTML=`<section><header><div><small>START RIDE</small><h3>Which bike are you riding?</h3></div><button id="closeBikePicker">×</button></header><div class="bikePickerGrid">${bikes.map(b=>`<article class="bikePickCard" data-bike-id="${b.id}">${bikeImage(b,'bikePickPhoto')}<div><strong>${esc(bikeName(b))}</strong><small>${b.image_url?'Tap to ride':'Add a photo or tap to ride'}</small></div><button class="photoButton" data-photo-bike="${b.id}">📷</button><input hidden type="file" accept="image/*" data-photo-input="${b.id}"></article>`).join('')||'<div class="rideEmpty">Add a motorcycle in the Garage first.</div>'}</div></section>`;document.body.appendChild(modal);$('#closeBikePicker').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});modal.querySelectorAll('.bikePickCard').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-photo-bike]'))return;beginRide(c.dataset.bikeId)});modal.querySelectorAll('[data-photo-bike]').forEach(b=>b.onclick=e=>{e.stopPropagation();modal.querySelector(`[data-photo-input="${b.dataset.photoBike}"]`).click()});modal.querySelectorAll('[data-photo-input]').forEach(i=>i.onchange=()=>uploadBikePhoto(i.dataset.photoInput,i.files?.[0]))}

async function uploadBikePhoto(bikeId,file){if(!file)return;if(file.size>5*1024*1024){alert('Use an image smaller than 5 MB.');return}const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=`${session.user.id}/${bikeId}-${Date.now()}.${ext}`;const {error:uploadError}=await supabase.storage.from('bike-images').upload(path,file,{upsert:true,contentType:file.type});if(uploadError){alert(uploadError.message);return}const {data}=supabase.storage.from('bike-images').getPublicUrl(path);const {error}=await supabase.from('bikes').update({image_url:data.publicUrl,updated_at:new Date().toISOString()}).eq('id',bikeId);if(error){alert(error.message);return}await loadData();showBikePicker()}

async function requestMotion(){try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const r=await DeviceMotionEvent.requestPermission();if(r!=='granted')throw new Error('Motion permission was not granted.')}if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();if(r!=='granted')throw new Error('Orientation permission was not granted.')}return true}catch(e){alert(e.message);return false}}
async function beginRide(bikeId){const bike=bikes.find(b=>b.id===bikeId);if(!bike)return;if(!navigator.geolocation){alert('GPS is not available on this device.');return}document.querySelector('#rideBikePicker')?.remove();const motionOK=await requestMotion();const {data,error}=await supabase.from('ride_sessions').insert({user_id:session.user.id,bike_id:bike.id,bike_name:bikeName(bike),status:'recording'}).select().single();if(error){alert(error.message);return}active={...data,bike,motionOK,startMs:Date.now(),latest:null};distanceMi=0;maxSpeed=0;speedSum=0;speedCount=0;maxAccel=0;maxBrake=0;maxLean=0;buffer=[];lastPos=null;leanOffset=0;window.addEventListener('devicemotion',onMotion);window.addEventListener('deviceorientation',onOrientation);watchId=navigator.geolocation.watchPosition(onPosition,e=>setStatus(`GPS error: ${e.message}`),{enableHighAccuracy:true,maximumAge:500,timeout:15000});timer=setInterval(()=>{updateDash();queueSample()},1000);renderLive()}
function onMotion(e){const a=e.accelerationIncludingGravity||e.acceleration||{};motion.ax=a.x??null;motion.ay=a.y??null;motion.az=a.z??null;if([a.x,a.y,a.z].every(Number.isFinite)){motion.g=Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z)/9.80665;maxAccel=Math.max(maxAccel,motion.g);maxBrake=Math.max(maxBrake,Math.max(0,-(a.y||0)/9.80665))}}
function onOrientation(e){motion.alpha=e.alpha??null;motion.beta=e.beta??null;motion.gamma=e.gamma??null;motion.pitch=e.beta??null;motion.roll=e.gamma??null;motion.lean=Number.isFinite(e.gamma)?e.gamma-leanOffset:null;if(Number.isFinite(motion.lean))maxLean=Math.max(maxLean,Math.abs(motion.lean))}
function recalibrateLean(){if(!Number.isFinite(motion.gamma)){alert('Motion data is not ready yet. Hold the phone in its riding position and try again.');return}leanOffset=motion.gamma;motion.lean=0;maxLean=0;setStatus('Lean angle recalibrated to 0°');updateDash()}
function onPosition(p){if(!active)return;const c=p.coords,pos={latitude:c.latitude,longitude:c.longitude};if(lastPos&&c.accuracy<80){const d=hav(lastPos,pos);if(d<0.5)distanceMi+=d}lastPos=pos;const speed=mph(c.speed);if(speed>=0&&speed<250){maxSpeed=Math.max(maxSpeed,speed);speedSum+=speed;speedCount++}active.latest={...pos,altitude:c.altitude,accuracy:c.accuracy,speed,heading:c.heading,timestamp:p.timestamp};updateDash()}

function renderLive(){const body=$('#rideCenterBody');if(!body)return;body.innerHTML=`<div class="liveBikeHero">${bikeImage(active.bike,'liveBikePhoto')}<div><span class="recordPulse"></span><small>RECORDING</small><h3>${esc(active.bike_name)}</h3></div><strong id="rideClock">00:00:00</strong></div><div class="speedDial"><strong id="rideSpeed">--</strong><span>MPH</span></div><div class="rideMetrics"><article><small>DISTANCE</small><strong id="rideDistance">0.00 mi</strong></article><article><small>HEADING</small><strong id="rideHeading">--°</strong></article><article><small>ALTITUDE</small><strong id="rideAltitude">-- ft</strong></article><article><small>GPS ACCURACY</small><strong id="rideAccuracy">-- ft</strong></article><article><small>ACCELERATION</small><strong id="rideAccel">-- g</strong></article><article class="leanMetric"><small>LEAN</small><strong id="rideLean">--°</strong><button id="recalibrateLean">RECALIBRATE</button></article><article><small>PITCH</small><strong id="ridePitch">--°</strong></article><article><small>MAX SPEED</small><strong id="rideMaxSpeed">0 mph</strong></article></div><div class="rideShortcutBar"><button id="openMaps">🗺 Maps</button><button id="openMusic">♫ Music</button><button id="airpodsHelp">◉ AirPods</button></div><div id="rideStatus" class="rideStatus">Waiting for GPS fix…</div><button id="rideStop" class="rideStop">STOP & SAVE RIDE</button>`;$('#rideStop').onclick=stopRide;$('#recalibrateLean').onclick=recalibrateLean;$('#openMaps').onclick=()=>{window.location.href='maps://'};$('#openMusic').onclick=()=>window.open('https://music.apple.com/','_blank');$('#airpodsHelp').onclick=showAirPodsHelp;updateDash()}
function showAirPodsHelp(){document.querySelector('#airpodsModal')?.remove();const m=document.createElement('div');m.id='airpodsModal';m.className='rideModal';m.innerHTML=`<section class="airpodsSheet"><header><div><small>AIRPODS</small><h3>Listening mode</h3></div><button id="closeAirpods">×</button></header><p>iOS does not expose AirPods Noise Cancellation, Transparency, Adaptive, or Off controls to websites or PWAs.</p><div class="airpodSteps"><b>Fastest controls while riding:</b><span>• Press and hold the AirPods stem to cycle listening modes.</span><span>• Or open Control Center, hold the volume slider, then tap Noise Control.</span></div></section>`;document.body.appendChild(m);$('#closeAirpods').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}
function updateDash(){if(!active)return;const sec=Math.floor((Date.now()-active.startMs)/1000),p=active.latest;const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('#rideClock',fmtTime(sec));set('#rideSpeed',p?Math.round(p.speed||0):'--');set('#rideDistance',`${distanceMi.toFixed(2)} mi`);set('#rideHeading',p&&Number.isFinite(p.heading)?`${Math.round(p.heading)}°`:'--°');set('#rideAltitude',p&&Number.isFinite(p.altitude)?`${Math.round(ft(p.altitude))} ft`:'-- ft');set('#rideAccuracy',p&&Number.isFinite(p.accuracy)?`±${Math.round(ft(p.accuracy))} ft`:'-- ft');set('#rideAccel',Number.isFinite(motion.g)?`${motion.g.toFixed(2)} g`:'-- g');set('#rideLean',Number.isFinite(motion.lean)?`${motion.lean.toFixed(1)}°`:'--°');set('#ridePitch',Number.isFinite(motion.pitch)?`${motion.pitch.toFixed(1)}°`:'--°');set('#rideMaxSpeed',`${Math.round(maxSpeed)} mph`);setStatus(p?'GPS locked · Cloud logging active':'Waiting for GPS fix…')}
function setStatus(t){const e=$('#rideStatus');if(e)e.textContent=t}
function queueSample(){if(!active)return;const p=active.latest||{};buffer.push({session_id:active.id,user_id:session.user.id,recorded_at:new Date().toISOString(),latitude:p.latitude??null,longitude:p.longitude??null,altitude_m:p.altitude??null,accuracy_m:p.accuracy??null,speed_mps:Number.isFinite(p.speed)?p.speed/2.236936:null,heading_deg:p.heading??null,accel_x:motion.ax,accel_y:motion.ay,accel_z:motion.az,accel_g:motion.g,rotation_alpha:motion.alpha,rotation_beta:motion.beta,rotation_gamma:motion.gamma,lean_deg:motion.lean,pitch_deg:motion.pitch,roll_deg:motion.roll});if(buffer.length>=10)flushSamples()}
async function flushSamples(){if(!buffer.length)return;const rows=buffer.splice(0,buffer.length);const {error}=await supabase.from('ride_samples').insert(rows);if(error){console.error(error);buffer.unshift(...rows)}}
async function stopRide(){if(!active)return;if(!confirm('Stop and save this ride?'))return;clearInterval(timer);timer=null;if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;window.removeEventListener('devicemotion',onMotion);window.removeEventListener('deviceorientation',onOrientation);queueSample();await flushSamples();const duration=Math.floor((Date.now()-active.startMs)/1000),p=active.latest||{},avg=speedCount?speedSum/speedCount:0;const {error}=await supabase.from('ride_sessions').update({ended_at:new Date().toISOString(),duration_seconds:duration,distance_miles:distanceMi,max_speed_mph:maxSpeed,average_speed_mph:avg,max_accel_g:maxAccel,max_brake_g:maxBrake,max_lean_deg:maxLean,end_lat:p.latitude??null,end_lng:p.longitude??null,status:'complete',updated_at:new Date().toISOString(),...(lastPos?{start_lat:active.start_lat??lastPos.latitude,start_lng:active.start_lng??lastPos.longitude}:{})}).eq('id',active.id);if(error){alert(error.message);return}active=null;await loadData();renderHome()}

const observer=new MutationObserver(injectNav);observer.observe(document.querySelector('#app')||document.body,{childList:true,subtree:false});supabase.auth.onAuthStateChange(()=>setTimeout(loadData,0));loadData();