import { supabase } from './supabase.js';

const $=q=>document.querySelector(q);
const esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,bikes=[],rides=[],active=null,watchId=null,timer=null,lastPos=null,leanOffset=0,wakeLock=null,startPending=false,createdSessionId=null;
let motion={ax:null,ay:null,az:null,g:null,alpha:null,beta:null,gamma:null,lean:null,pitch:null,roll:null},buffer=[],distanceMi=0,maxSpeed=0,speedSum=0,speedCount=0,maxAccel=0,maxBrake=0,maxLean=0;
const prefs=()=>({maps:localStorage.getItem('rideMaps')||'apple',music:localStorage.getItem('rideMusic')||'apple',notifications:localStorage.getItem('rideNotifications')==='true'});
const mph=mps=>Number.isFinite(mps)?mps*2.236936:0,ft=m=>Number.isFinite(m)?m*3.28084:null,fmtTime=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const timeout=(promise,ms,label)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`${label} timed out. Check your connection and try again.`)),ms))]);
function hav(a,b){const R=3958.7613,toRad=x=>x*Math.PI/180,dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function bikeName(b){return [b.year,b.make,b.model].filter(Boolean).join(' ')||b.name||'Motorcycle'}
function bikeImage(b,cls=''){return b?.image_url?`<img class="${cls}" src="${esc(b.image_url)}" alt="${esc(bikeName(b))}">`:`<div class="bikePhotoPlaceholder ${cls}">🏍</div>`}
function safeStage(text){const e=$('#rideStartStage');if(e)e.textContent=text}
function showRuntimeError(error){console.error(error);const body=$('#rideCenterBody');if(!body)return;body.innerHTML=`<div class="rideHero"><span class="rideDot"></span><div><small>LOGGER START FAILED</small><h3>Ride Center recovered</h3><p>${esc(error?.message||String(error)||'Unknown startup error')}</p></div></div><button id="rideRetry" class="rideStart">RETURN TO START</button>`;$('#rideRetry').onclick=renderHome}
async function loadData(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!s)return;const [b,r]=await Promise.all([supabase.from('bikes').select('*').order('created_at'),supabase.from('ride_sessions').select('*').order('started_at',{ascending:false}).limit(25)]);bikes=b.data||[];rides=r.data||[];injectNav();recoverRideState()}
function injectNav(){const nav=$('#nav');if(!nav||$('#rideCenterNav'))return;const btn=document.createElement('button');btn.id='rideCenterNav';btn.innerHTML='<span class="navIcon">◉</span><span>Ride Center</span><em>LIVE</em>';btn.onclick=openRideCenter;const ops=[...nav.querySelectorAll('.navGroup')].find(g=>g.querySelector('.navLabel')?.textContent.trim()==='Operations');(ops||nav).appendChild(btn)}
function openRideCenter(){document.querySelector('#rideCenterOverlay')?.remove();const o=document.createElement('div');o.id='rideCenterOverlay';o.innerHTML=`<section class="rideCenter"><header><div><small>IPHONE SENSOR LOGGER</small><h2>Ride Center</h2></div><div class="rideHeaderActions"><button id="rideSettings">⚙</button><button id="closeRideCenter">×</button></div></header><div id="rideCenterBody"></div></section>`;document.body.appendChild(o);$('#closeRideCenter').onclick=()=>{if(!active&&!startPending)o.remove()};$('#rideSettings').onclick=showSettings;renderHome()}
function renderHome(){const body=$('#rideCenterBody');if(!body)return;if(active){renderLive();return}body.innerHTML=`<div class="rideHero"><span class="rideDot"></span><div><small>READY TO RECORD</small><h3>Start a ride</h3><p>Choose a motorcycle, then approve GPS and motion access.</p></div></div><button id="rideStart" class="rideStart">START RIDE</button><p class="rideHint">Ride startup is isolated from Adventure Mode and recovers automatically if a permission or network request fails.</p><div class="rideHistory"><h3>Recent rides</h3>${rides.length?rides.map(r=>`<article data-ride-detail="${r.id}"><div><strong>${esc(r.bike_name)}</strong><small>${new Date(r.started_at).toLocaleString()}</small></div><div><b>${Number(r.distance_miles||0).toFixed(1)} mi</b><small>${fmtTime(r.duration_seconds||0)}</small></div></article>`).join(''):'<div class="rideEmpty">No recorded rides yet.</div>'}</div>`;$('#rideStart').onclick=showBikePicker;document.querySelectorAll('[data-ride-detail]').forEach(x=>x.onclick=()=>window.dispatchEvent(new CustomEvent('moto-open-ride',{detail:x.dataset.rideDetail})))}
function showSettings(){const p=prefs();document.querySelector('#rideSettingsModal')?.remove();const m=document.createElement('div');m.id='rideSettingsModal';m.className='rideModal';m.innerHTML=`<section><header><div><small>RIDE SETTINGS</small><h3>Shortcuts & permissions</h3></div><button id="closeRideSettings">×</button></header><label>Preferred maps<select id="mapsPref"><option value="apple" ${p.maps==='apple'?'selected':''}>Apple Maps</option><option value="google" ${p.maps==='google'?'selected':''}>Google Maps</option><option value="waze" ${p.maps==='waze'?'selected':''}>Waze</option></select></label><label>Preferred music<select id="musicPref"><option value="apple" ${p.music==='apple'?'selected':''}>Apple Music</option><option value="spotify" ${p.music==='spotify'?'selected':''}>Spotify</option><option value="youtube" ${p.music==='youtube'?'selected':''}>YouTube Music</option></select></label><label class="toggleRow"><input id="rideNotifyPref" type="checkbox" ${p.notifications?'checked':''}> Ride interruption notifications</label><button id="saveRideSettings" class="rideStart">SAVE SETTINGS</button></section>`;document.body.appendChild(m);$('#closeRideSettings').onclick=()=>m.remove();$('#saveRideSettings').onclick=async()=>{localStorage.setItem('rideMaps',$('#mapsPref').value);localStorage.setItem('rideMusic',$('#musicPref').value);const want=$('#rideNotifyPref').checked;if(want&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission();localStorage.setItem('rideNotifications',String(want));m.remove()}}
function showBikePicker(){if(startPending)return;document.querySelector('#rideBikePicker')?.remove();const modal=document.createElement('div');modal.id='rideBikePicker';modal.className='rideModal';modal.innerHTML=`<section><header><div><small>START RIDE</small><h3>Which bike are you riding?</h3></div><button id="closeBikePicker">×</button></header><div class="bikePickerGrid">${bikes.map(b=>`<article class="bikePickCard" data-bike-id="${b.id}">${bikeImage(b,'bikePickPhoto')}<div><strong>${esc(bikeName(b))}</strong><small>${Number(b.odometer||0).toFixed(0)} mi</small></div></article>`).join('')||'<div class="rideEmpty">Add a motorcycle in the Garage first.</div>'}</div></section>`;document.body.appendChild(modal);$('#closeBikePicker').onclick=()=>modal.remove();modal.querySelectorAll('.bikePickCard').forEach(c=>c.onclick=()=>{if(!startPending)prepareRide(c.dataset.bikeId)})}
async function prepareRide(bikeId){if(startPending||active)return;const bike=bikes.find(b=>b.id===bikeId);if(!bike)return;if(Number(bike.rides_since_odometer_confirm||0)>=20){const value=prompt('Confirm current odometer mileage:',Number(bike.odometer||0).toFixed(1));if(value===null)return;const n=Number(value);if(!Number.isFinite(n)||n<0)return alert('Enter a valid odometer value.');const {error}=await supabase.from('bikes').update({odometer:n,rides_since_odometer_confirm:0,odometer_last_confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',bike.id);if(error)return alert(error.message);bike.odometer=n;bike.rides_since_odometer_confirm=0}await beginRide(bikeId)}
async function requestMotion(){try{let ok=true;if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')ok=(await timeout(DeviceMotionEvent.requestPermission(),10000,'Motion permission'))==='granted';if(ok&&typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')ok=(await timeout(DeviceOrientationEvent.requestPermission(),10000,'Orientation permission'))==='granted';return ok}catch(e){console.warn('Motion unavailable',e);return false}}
function showStarting(bike){document.querySelector('#rideBikePicker')?.remove();const body=$('#rideCenterBody');if(body)body.innerHTML=`<div class="rideHero"><span class="recordPulse"></span><div><small>STARTING LOGGER</small><h3>${esc(bikeName(bike))}</h3><p id="rideStartStage">Requesting sensor permissions…</p></div></div><button class="rideStart" disabled>PLEASE WAIT</button>`}
function cleanupRuntime(){clearInterval(timer);timer=null;if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}window.removeEventListener('devicemotion',onMotion);window.removeEventListener('deviceorientation',onOrientation)}
async function beginRide(bikeId){if(startPending||active)return;const bike=bikes.find(b=>b.id===bikeId);if(!bike||!navigator.geolocation)return alert('GPS is not available on this device.');startPending=true;createdSessionId=null;showStarting(bike);cleanupRuntime();try{const motionOK=await requestMotion();safeStage('Creating ride session…');const result=await timeout(supabase.from('ride_sessions').insert({user_id:session.user.id,bike_id:bike.id,bike_name:bikeName(bike),status:'recording'}).select().single(),15000,'Ride session');if(result.error)throw result.error;createdSessionId=result.data.id;active={...result.data,bike,motionOK,startMs:Date.now(),latest:null,ready:false};localStorage.setItem('motoActiveRide',JSON.stringify({id:active.id,bikeId:bike.id,bikeName:bikeName(bike),startedAt:active.startMs}));distanceMi=maxSpeed=speedSum=speedCount=maxAccel=maxBrake=maxLean=0;buffer=[];lastPos=null;leanOffset=0;safeStage('Loading ride dashboard…');renderLive();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(motionOK){window.addEventListener('devicemotion',onMotion,{passive:true});window.addEventListener('deviceorientation',onOrientation,{passive:true})}active.ready=true;watchId=navigator.geolocation.watchPosition(onPosition,e=>setStatus(`GPS error: ${e.message}`),{enableHighAccuracy:true,maximumAge:1500,timeout:20000});timer=setInterval(()=>{try{updateDash();queueSample()}catch(e){console.error('Ride timer error',e)}},1000);setBadge(1);void acquireWakeLock();createdSessionId=null}catch(e){cleanupRuntime();if(createdSessionId){await supabase.from('ride_sessions').update({status:'failed',ended_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',createdSessionId)}active=null;localStorage.removeItem('motoActiveRide');showRuntimeError(e)}finally{startPending=false}}
function onMotion(e){if(!active?.ready)return;try{const a=e.accelerationIncludingGravity||e.acceleration||{};motion.ax=a.x??null;motion.ay=a.y??null;motion.az=a.z??null;if([a.x,a.y,a.z].every(Number.isFinite)){motion.g=Math.sqrt(a.x*a.x+a.y*a.y+a.z*a.z)/9.80665;maxAccel=Math.max(maxAccel,motion.g);maxBrake=Math.max(maxBrake,Math.max(0,-(a.y||0)/9.80665))}}catch(err){console.warn('Motion sample skipped',err)}}
function onOrientation(e){if(!active?.ready)return;try{motion.alpha=e.alpha??null;motion.beta=e.beta??null;motion.gamma=e.gamma??null;motion.pitch=e.beta??null;motion.roll=e.gamma??null;motion.lean=Number.isFinite(e.gamma)?e.gamma-leanOffset:null;if(Number.isFinite(motion.lean))maxLean=Math.max(maxLean,Math.abs(motion.lean))}catch(err){console.warn('Orientation sample skipped',err)}}
function recalibrateLean(){if(!Number.isFinite(motion.gamma))return alert('Motion data is not ready yet.');leanOffset=motion.gamma;motion.lean=0;maxLean=0;updateDash()}
function onPosition(p){if(!active?.ready)return;try{const c=p.coords,pos={latitude:c.latitude,longitude:c.longitude};if(lastPos&&Number.isFinite(c.accuracy)&&c.accuracy<80){const d=hav(lastPos,pos);if(Number.isFinite(d)&&d<0.5)distanceMi+=d}lastPos=pos;const speed=mph(c.speed);if(speed>=0&&speed<250){maxSpeed=Math.max(maxSpeed,speed);speedSum+=speed;speedCount++}active.latest={...pos,altitude:c.altitude,accuracy:c.accuracy,speed,heading:c.heading,timestamp:p.timestamp};updateDash();if(document.querySelector('#adventureOverlay'))queueMicrotask(()=>{try{window.dispatchEvent(new CustomEvent('moto-position',{detail:{...active.latest}}))}catch(e){console.warn('Adventure position bridge skipped',e)}})}catch(e){console.error('GPS sample skipped',e)}}
function openMaps(){window.location.href=({apple:'maps://',google:'comgooglemaps://',waze:'waze://'})[prefs().maps]||'maps://'}
function openMusic(){window.location.href=({apple:'music://',spotify:'spotify://',youtube:'youtubemusic://'})[prefs().music]||'music://'}
function renderLive(){if(!active)return;const body=$('#rideCenterBody');if(!body)throw new Error('Ride dashboard container is missing.');body.innerHTML=`<div class="liveBikeHero">${bikeImage(active.bike,'liveBikePhoto')}<div><span class="recordPulse"></span><small>RECORDING</small><h3>${esc(active.bike_name)}</h3></div><strong id="rideClock">00:00:00</strong></div><div class="speedDial"><strong id="rideSpeed">--</strong><span>MPH</span></div><div class="rideMetrics"><article><small>DISTANCE</small><strong id="rideDistance">0.00 mi</strong></article><article><small>HEADING</small><strong id="rideHeading">--°</strong></article><article><small>ALTITUDE</small><strong id="rideAltitude">-- ft</strong></article><article><small>GPS ACCURACY</small><strong id="rideAccuracy">-- ft</strong></article><article><small>ACCELERATION</small><strong id="rideAccel">-- g</strong></article><article class="leanMetric"><small>LEAN</small><strong id="rideLean">--°</strong><button id="recalibrateLean">RECALIBRATE</button></article><article><small>PITCH</small><strong id="ridePitch">--°</strong></article><article><small>MAX SPEED</small><strong id="rideMaxSpeed">0 mph</strong></article></div><div class="rideShortcutBar"><button id="openMaps">🗺 ${prefs().maps}</button><button id="openMusic">♫ ${prefs().music}</button><button id="airpodsHelp">◉ AirPods</button></div><div id="rideStatus" class="rideStatus">Waiting for GPS fix…</div><button id="rideStop" class="rideStop">STOP & SAVE RIDE</button>`;$('#rideStop').onclick=stopRide;$('#recalibrateLean').onclick=recalibrateLean;$('#openMaps').onclick=openMaps;$('#openMusic').onclick=openMusic;$('#airpodsHelp').onclick=()=>alert('Press and hold the AirPods stem to cycle listening modes, or use Control Center.');updateDash()}
function updateDash(){if(!active)return;const sec=Math.floor((Date.now()-active.startMs)/1000),p=active.latest,set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('#rideClock',fmtTime(sec));set('#rideSpeed',p?Math.round(p.speed||0):'--');set('#rideDistance',`${distanceMi.toFixed(2)} mi`);set('#rideHeading',p&&Number.isFinite(p.heading)?`${Math.round(p.heading)}°`:'--°');set('#rideAltitude',p&&Number.isFinite(p.altitude)?`${Math.round(ft(p.altitude))} ft`:'-- ft');set('#rideAccuracy',p&&Number.isFinite(p.accuracy)?`±${Math.round(ft(p.accuracy))} ft`:'-- ft');set('#rideAccel',Number.isFinite(motion.g)?`${motion.g.toFixed(2)} g`:'-- g');set('#rideLean',Number.isFinite(motion.lean)?`${motion.lean.toFixed(1)}°`:'--°');set('#ridePitch',Number.isFinite(motion.pitch)?`${motion.pitch.toFixed(1)}°`:'--°');set('#rideMaxSpeed',`${Math.round(maxSpeed)} mph`);setStatus(p?'GPS locked · Cloud logging active':'Waiting for GPS fix…')}
function setStatus(t){const e=$('#rideStatus');if(e)e.textContent=t}
function queueSample(){if(!active?.ready)return;const p=active.latest||{};buffer.push({session_id:active.id,user_id:session.user.id,recorded_at:new Date().toISOString(),latitude:p.latitude??null,longitude:p.longitude??null,altitude_m:p.altitude??null,accuracy_m:p.accuracy??null,speed_mps:Number.isFinite(p.speed)?p.speed/2.236936:null,heading_deg:p.heading??null,accel_x:motion.ax,accel_y:motion.ay,accel_z:motion.az,accel_g:motion.g,rotation_alpha:motion.alpha,rotation_beta:motion.beta,rotation_gamma:motion.gamma,lean_deg:motion.lean,pitch_deg:motion.pitch,roll_deg:motion.roll});if(buffer.length>=10)void flushSamples()}
async function flushSamples(){if(!buffer.length)return;const rows=buffer.splice(0);const {error}=await supabase.from('ride_samples').insert(rows);if(error){console.error(error);buffer.unshift(...rows)}}
async function stopRide(){if(!active||!confirm('Stop and save this ride?'))return;cleanupRuntime();queueSample();await flushSamples();const duration=Math.floor((Date.now()-active.startMs)/1000),p=active.latest||{},avg=speedCount?speedSum/speedCount:0;await supabase.from('ride_sessions').update({ended_at:new Date().toISOString(),duration_seconds:duration,distance_miles:distanceMi,max_speed_mph:maxSpeed,average_speed_mph:avg,max_accel_g:maxAccel,max_brake_g:maxBrake,max_lean_deg:maxLean,end_lat:p.latitude??null,end_lng:p.longitude??null,status:'complete',updated_at:new Date().toISOString()}).eq('id',active.id);const b=active.bike;await supabase.from('bikes').update({odometer:Number(b.odometer||0)+distanceMi,gps_odometer_miles:Number(b.gps_odometer_miles||0)+distanceMi,rides_since_odometer_confirm:Number(b.rides_since_odometer_confirm||0)+1,updated_at:new Date().toISOString()}).eq('id',b.id);localStorage.removeItem('motoActiveRide');void releaseWakeLock();setBadge(0);active=null;await loadData();renderHome()}
async function acquireWakeLock(){try{if('wakeLock'in navigator)wakeLock=await navigator.wakeLock.request('screen')}catch(e){console.warn('Wake lock unavailable',e)}}
async function releaseWakeLock(){try{await wakeLock?.release()}catch{}wakeLock=null}
function setBadge(n){try{n?navigator.setAppBadge?.(n):navigator.clearAppBadge?.()}catch{}}
function notify(title,body){if(prefs().notifications&&'Notification'in window&&Notification.permission==='granted')new Notification(title,{body,icon:'/app-icon.svg'})}
function recoverRideState(){const saved=localStorage.getItem('motoActiveRide');if(!saved||active)return;try{const r=JSON.parse(saved),db=rides.find(x=>x.id===r.id&&x.status==='recording');if(db){notify('MotoCloud ride may still be active',`${r.bikeName} was left recording.`);setBadge(1)}}catch{localStorage.removeItem('motoActiveRide')}}
window.addEventListener('error',e=>{if(startPending||active&&!active.ready)showRuntimeError(e.error||new Error(e.message))});
window.addEventListener('unhandledrejection',e=>{if(startPending||active&&!active.ready){e.preventDefault();showRuntimeError(e.reason instanceof Error?e.reason:new Error(String(e.reason)))}});
document.addEventListener('visibilitychange',()=>{if(active?.ready&&!document.hidden)void acquireWakeLock()});
window.addEventListener('pagehide',()=>{if(active)localStorage.setItem('motoRideInterrupted','true')});
const observer=new MutationObserver(injectNav);observer.observe(document.querySelector('#app')||document.body,{childList:true,subtree:false});
supabase.auth.onAuthStateChange(()=>setTimeout(loadData,0));
loadData();