const $=q=>document.querySelector(q);
let lastCoords=null,lastWeatherAt=0,lastRoadAt=0,lastRoadCoords=null,loading=false,roadLoading=false,currentRoadLimit=null;
const OVERPASS_ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.nchc.org.tw/api/interpreter'];

function cardinal(deg){if(!Number.isFinite(deg))return '—';return ['N','NE','E','SE','S','SW','W','NW'][Math.round(deg/45)%8]}
function localTime(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function setText(id,value){const el=$(id);if(el)el.textContent=value}
function haversineMiles(a,b){if(!a||!b)return Infinity;const R=3958.7613,toRad=x=>x*Math.PI/180,dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function parseSpeedLimit(value){if(!value)return null;const raw=String(value).trim(),number=Number.parseFloat(raw);if(!Number.isFinite(number))return {display:raw,mph:null,raw};const mph=/km\/?h|kph/i.test(raw)?number*0.621371:number;return {display:`${Math.round(mph)} mph`,mph:Math.round(mph),raw}}
function prettyRoadType(value){return value?String(value).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()):'Unknown'}
function roadInfoMarkup(){return `<section class="rideRoadCard" id="rideRoadCard">
  <div class="rideSpeedLimitSign"><small>SPEED<br>LIMIT</small><strong id="rideSpeedLimitValue">--</strong></div>
  <div class="rideRoadCopy"><small>ROAD INFORMATION</small><h3 id="rideRoadName">Locating road…</h3><p id="rideSpeedLimitDelta">Waiting for GPS position</p></div>
  <button id="refreshSpeedLimit" type="button" title="Refresh road information">↻</button>
  <div class="rideRoadDetails">
    <span><small>TYPE</small><b id="rideRoadType">—</b></span>
    <span><small>SURFACE</small><b id="rideRoadSurface">—</b></span>
    <span><small>LANES</small><b id="rideRoadLanes">—</b></span>
    <span><small>SOURCE</small><b id="rideRoadSource">Waiting</b></span>
  </div>
  <details class="rideRoadDiagnostic"><summary>Lookup details</summary><p id="rideRoadDiagnosticText">No lookup completed yet.</p></details>
</section><p class="rideSpeedLimitNote">Advisory only. Road signs and local law take priority. Road data © OpenStreetMap contributors.</p>`}
function showPage(index){const viewport=$('#rideSwipeViewport'),track=$('#rideSwipeTrack');if(!viewport||!track)return;const page=index===1?1:0;viewport.dataset.page=String(page);track.style.transform=`translateX(-${page*50}%)`;document.querySelectorAll('[data-ride-page]').forEach(b=>b.classList.toggle('active',Number(b.dataset.ridePage)===page));if(page===1)refreshWeather(false)}
function weatherMarkup(){return `<section class="rideWeatherPage"><div class="rideWeatherHeading"><div><small>LOCAL RIDING WEATHER</small><h3 id="rideWeatherLocation">Current location</h3></div><button id="refreshRideWeather" class="rideWeatherRefresh" type="button">↻</button></div><div id="rideWeatherStatus" class="rideWeatherStatus">Waiting for location…</div><div class="rideWeatherHero"><strong id="rideWeatherTemp">--°</strong><div><span id="rideWeatherRain">--% rain</span><small id="rideWeatherUpdated">Not updated</small></div></div><div class="rideWeatherGrid"><article><small>CHANCE OF RAIN</small><strong id="rideWeatherRainCard">--%</strong></article><article><small>HUMIDITY</small><strong id="rideWeatherHumidity">--%</strong></article><article><small>WIND</small><strong id="rideWeatherWind">-- mph</strong><span id="rideWeatherWindDir">—</span></article><article><small>SUNRISE</small><strong id="rideWeatherSunrise">--</strong></article><article><small>SUNSET</small><strong id="rideWeatherSunset">--</strong></article><article><small>DAILY RAIN MAX</small><strong id="rideWeatherRainMax">--%</strong></article></div><a id="openLocalWeather" class="rideWeatherLink" href="https://weather.apple.com/" target="_blank" rel="noopener">OPEN LOCAL WEATHER</a><p class="rideWeatherFoot">Forecast follows the phone’s current GPS position. Swipe right to return to ride metrics.</p></section>`}
function enhanceRideLive(){const body=$('#rideCenterBody');if(!body||!body.querySelector('#rideStop')||body.querySelector('#rideSwipeViewport'))return;const current=[...body.childNodes],tabs=document.createElement('div');tabs.className='ridePageTabs';tabs.innerHTML='<button type="button" data-ride-page="0" class="active">RIDE</button><button type="button" data-ride-page="1">WEATHER</button>';const viewport=document.createElement('div');viewport.id='rideSwipeViewport';viewport.className='rideSwipeViewport';viewport.dataset.page='0';const track=document.createElement('div');track.id='rideSwipeTrack';track.className='rideSwipeTrack';const ride=document.createElement('section');ride.className='rideSwipePage rideDataPage';current.forEach(node=>ride.appendChild(node));const roadCard=document.createElement('div');roadCard.innerHTML=roadInfoMarkup();const status=ride.querySelector('#rideStatus');if(status)ride.insertBefore(roadCard,status);else ride.appendChild(roadCard);const weather=document.createElement('section');weather.className='rideSwipePage';weather.innerHTML=weatherMarkup();track.append(ride,weather);viewport.appendChild(track);body.append(tabs,viewport);tabs.querySelectorAll('[data-ride-page]').forEach(b=>b.onclick=()=>showPage(Number(b.dataset.ridePage)));$('#refreshRideWeather').onclick=()=>refreshWeather(true);$('#refreshSpeedLimit').onclick=()=>refreshRoadInfo(true);let startX=null;viewport.addEventListener('touchstart',e=>{startX=e.touches[0]?.clientX??null},{passive:true});viewport.addEventListener('touchend',e=>{if(startX===null)return;const dx=(e.changedTouches[0]?.clientX??startX)-startX;startX=null;if(Math.abs(dx)<45)return;showPage(dx<0?1:0)},{passive:true});refreshWeather(false);refreshRoadInfo(false);startRoadMonitor()}
async function fetchForecast(lat,lon){const params=new URLSearchParams({latitude:String(lat),longitude:String(lon),current:'temperature_2m,relative_humidity_2m,precipitation_probability,wind_speed_10m,wind_direction_10m',daily:'sunrise,sunset,precipitation_probability_max',temperature_unit:'fahrenheit',wind_speed_unit:'mph',timezone:'auto',forecast_days:'1'}),response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!response.ok)throw new Error(`Weather service returned ${response.status}`);return response.json()}
function timeoutFetch(url,ms=10000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);return fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}}).finally(()=>clearTimeout(timer))}
async function fetchOverpass(lat,lon){const query=`[out:json][timeout:10];way(around:60,${lat},${lon})[highway];out tags center;`,errors=[];for(const endpoint of OVERPASS_ENDPOINTS){try{const response=await timeoutFetch(`${endpoint}?data=${encodeURIComponent(query)}`,12000);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();return {data,source:new URL(endpoint).hostname}}catch(error){errors.push(`${new URL(endpoint).hostname}: ${error.name==='AbortError'?'timeout':error.message}`)}}throw new Error(errors.join(' · '))}
function chooseRoad(elements,lat,lon){const ways=(elements||[]).filter(x=>x.type==='way'&&x.tags?.highway);if(!ways.length)return null;return ways.map(x=>({way:x,distance:haversineMiles({latitude:lat,longitude:lon},{latitude:x.center?.lat??lat,longitude:x.center?.lon??lon})})).sort((a,b)=>a.distance-b.distance||Number(Boolean(b.way.tags.maxspeed))-Number(Boolean(a.way.tags.maxspeed)))[0]}
async function fetchRoadInfo(lat,lon){const {data,source}=await fetchOverpass(lat,lon),picked=chooseRoad(data.elements,lat,lon);if(!picked)return {status:'no-road',source,diagnostic:'OpenStreetMap returned no nearby highway ways within 60 meters.'};const tags=picked.way.tags||{};return {status:'road',source,distance:picked.distance,road:tags.name||tags.ref||tags.destination||'Unnamed road',limit:parseSpeedLimit(tags.maxspeed),type:prettyRoadType(tags.highway),surface:prettyRoadType(tags.surface),lanes:tags.lanes||'—',diagnostic:tags.maxspeed?`Matched ${tags.highway} about ${Math.round(picked.distance*5280)} ft away. maxspeed=${tags.maxspeed}.`:`Matched ${tags.highway} about ${Math.round(picked.distance*5280)} ft away, but this road has no maxspeed tag.`}}
function getPosition(force=false){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not available.'));if(lastCoords&&!force)return resolve(lastCoords);navigator.geolocation.getCurrentPosition(p=>{lastCoords={latitude:p.coords.latitude,longitude:p.coords.longitude};resolve(lastCoords)},reject,{enableHighAccuracy:true,maximumAge:force?0:300000,timeout:15000})})}
function updateSpeedDifference(limitMph=currentRoadLimit){const current=Number.parseFloat($('#rideSpeed')?.textContent||''),card=$('#rideRoadCard');if(!Number.isFinite(limitMph)){setText('#rideSpeedLimitDelta','No posted speed limit is mapped for this road');card?.classList.remove('over');return}if(!Number.isFinite(current)){setText('#rideSpeedLimitDelta','Waiting for current speed');card?.classList.remove('over');return}const delta=Math.round(current-limitMph);setText('#rideSpeedLimitDelta',delta>0?`${delta} mph over mapped limit`:delta<0?`${Math.abs(delta)} mph below mapped limit`:'At mapped limit');card?.classList.toggle('over',delta>0)}
function clearRoadFields(){setText('#rideSpeedLimitValue','--');setText('#rideRoadType','—');setText('#rideRoadSurface','—');setText('#rideRoadLanes','—');currentRoadLimit=null}
async function refreshRoadInfo(force=false){if(roadLoading)return;if(!force&&Date.now()-lastRoadAt<45*1000)return;roadLoading=true;setText('#rideRoadName','Locating road…');setText('#rideSpeedLimitDelta','Querying mapped road data');setText('#rideRoadSource','Loading');try{const c=await getPosition(force),moved=haversineMiles(lastRoadCoords,c);if(!force&&lastRoadCoords&&moved<0.03&&Date.now()-lastRoadAt<2*60*1000)return;const result=await fetchRoadInfo(c.latitude,c.longitude);lastRoadCoords={...c};lastRoadAt=Date.now();setText('#rideRoadSource',result.source||'OpenStreetMap');setText('#rideRoadDiagnosticText',result.diagnostic||'Lookup completed.');if(result.status!=='road'){clearRoadFields();setText('#rideRoadName','Road not identified');setText('#rideSpeedLimitDelta','No mapped road found near the GPS position');return}setText('#rideRoadName',result.road);setText('#rideRoadType',result.type);setText('#rideRoadSurface',result.surface);setText('#rideRoadLanes',result.lanes);currentRoadLimit=result.limit?.mph??null;setText('#rideSpeedLimitValue',result.limit?.mph??result.limit?.display??'--');updateSpeedDifference()}catch(error){clearRoadFields();setText('#rideRoadName','Road lookup failed');setText('#rideSpeedLimitDelta','Tap refresh to retry');setText('#rideRoadSource','Failed');setText('#rideRoadDiagnosticText',error.name==='AbortError'?'Road-data request timed out.':error.message||String(error))}finally{roadLoading=false}}
function startRoadMonitor(){if(window.__motoSpeedLimitTimer)clearInterval(window.__motoSpeedLimitTimer);window.__motoSpeedLimitTimer=setInterval(()=>{if(!$('#rideStop')){clearInterval(window.__motoSpeedLimitTimer);window.__motoSpeedLimitTimer=null;return}refreshRoadInfo(false);updateSpeedDifference()},5000)}
async function refreshWeather(force=false){if(loading)return;if(!force&&Date.now()-lastWeatherAt<10*60*1000)return;loading=true;setText('#rideWeatherStatus','Updating local weather…');try{const c=await getPosition(force),data=await fetchForecast(c.latitude,c.longitude),cur=data.current||{},daily=data.daily||{},rain=Number(cur.precipitation_probability),temp=Number(cur.temperature_2m),humidity=Number(cur.relative_humidity_2m),wind=Number(cur.wind_speed_10m),dir=Number(cur.wind_direction_10m),rainMax=Number(daily.precipitation_probability_max?.[0]);setText('#rideWeatherTemp',Number.isFinite(temp)?`${Math.round(temp)}°`:'--°');setText('#rideWeatherRain',Number.isFinite(rain)?`${Math.round(rain)}% rain`:'--% rain');setText('#rideWeatherRainCard',Number.isFinite(rain)?`${Math.round(rain)}%`:'--%');setText('#rideWeatherHumidity',Number.isFinite(humidity)?`${Math.round(humidity)}%`:'--%');setText('#rideWeatherWind',Number.isFinite(wind)?`${Math.round(wind)} mph`:'-- mph');setText('#rideWeatherWindDir',Number.isFinite(dir)?`${cardinal(dir)} · ${Math.round(dir)}°`:'—');setText('#rideWeatherSunrise',localTime(daily.sunrise?.[0]));setText('#rideWeatherSunset',localTime(daily.sunset?.[0]));setText('#rideWeatherRainMax',Number.isFinite(rainMax)?`${Math.round(rainMax)}%`:'--%');setText('#rideWeatherUpdated',`Updated ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`);setText('#rideWeatherStatus','Live forecast for your current position');const link=$('#openLocalWeather');if(link)link.href=`https://weather.com/weather/today/l/${c.latitude},${c.longitude}`;lastWeatherAt=Date.now()}catch(error){setText('#rideWeatherStatus',`Weather unavailable: ${error.message||error}`)}finally{loading=false}}
const observer=new MutationObserver(()=>queueMicrotask(enhanceRideLive));observer.observe(document.body,{childList:true,subtree:true});enhanceRideLive();