import { supabase } from './supabase.js';

const $=q=>document.querySelector(q),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,bikes=[],sources=[],selectedBike=null,activeSource=null,telemetry={},simTimer=null,lastSaved=0;
const sourceMeta={
 phone:['Phone Sensors','GPS / motion'],obdlink_lx:['OBDLink LX','Native iPhone bridge required'],esp32:['ESP32 Bike Module','BLE / Wi-Fi bridge'],bmw_can:['BMW CAN','ESP32 CAN interface'],honda_kline:['Honda K-Line','ESP32 K-Line interface'],pv3:['Dynojet PV3','Future integration'],get_ecu:['GET ECU','Future integration'],simulator:['Simulator','Dashboard test source']
};
const bikeName=b=>[b.year,b.make,b.model].filter(Boolean).join(' ')||b.name||'Motorcycle';
const num=(v,d='--')=>Number.isFinite(Number(v))?Number(v):d;

async function load(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(!s)return;const [b,src]=await Promise.all([supabase.from('bikes').select('*').order('created_at'),supabase.from('vehicle_data_sources').select('*').order('priority')]);bikes=b.data||[];sources=src.data||[];selectedBike=bikes[0]||null;seedDefaults();injectNav();}
async function seedDefaults(){if(!session||sources.length)return;const rows=['phone','obdlink_lx','esp32','bmw_can','honda_kline','simulator'].map((type,i)=>({user_id:session.user.id,bike_id:selectedBike?.id||null,source_type:type,display_name:sourceMeta[type][0],priority:(i+1)*10,connection_mode:type==='obdlink_lx'?'native_bridge':type==='simulator'?'local':'bridge'}));const {data}=await supabase.from('vehicle_data_sources').insert(rows).select();sources=data||[]}
function injectNav(){const nav=$('#nav');if(!nav||$('#vehicleDataNav'))return;const btn=document.createElement('button');btn.id='vehicleDataNav';btn.innerHTML='<span class="navIcon">◫</span><span>Vehicle Data</span><em>LIVE</em>';btn.onclick=open;const ops=[...nav.querySelectorAll('.navGroup')].find(g=>g.querySelector('.navLabel')?.textContent.trim()==='Operations');(ops||nav).appendChild(btn)}
function open(){document.querySelector('#vehicleDataOverlay')?.remove();const o=document.createElement('div');o.id='vehicleDataOverlay';o.innerHTML=`<section class="vehicleDataShell"><header><div><small>VEHICLE TELEMETRY</small><h2>Data Sources & Gauges</h2></div><button id="closeVehicleData">×</button></header><div class="vehicleDataToolbar"><label>Motorcycle<select id="vehicleBike">${bikes.map(b=>`<option value="${b.id}">${esc(bikeName(b))}</option>`).join('')}</select></label><button id="startSim">START TEST MODE</button></div><div class="vehicleGaugeCluster">${gauge('rpm','RPM','0','rpm')}${gauge('speed','SPEED','0','mph')}<div class="vehicleGaugeSmall">${tile('coolant','COOLANT','--','°F')}${tile('intake','INTAKE','--','°F')}${tile('voltage','BATTERY','--','V')}${tile('throttle','THROTTLE','--','%')}${tile('load','ENGINE LOAD','--','%')}${tile('gear','GEAR','--','')}${tile('hours','ENGINE HOURS','--','hr')}${tile('dtc','DTCs','0','')}</div></div><section class="vehicleSources"><div class="vehicleSectionHead"><div><small>CONNECTION MANAGER</small><h3>Available sources</h3></div><span id="vehicleActiveSource">No active source</span></div><div id="vehicleSourceList"></div></section><p class="vehicleDataNote">OBDLink LX uses Bluetooth Classic. The iPhone PWA cannot pair with it directly; a native iOS wrapper or ESP bridge must forward telemetry into MotoCloud. The simulator verifies the full dashboard and storage path now.</p></section>`;document.body.appendChild(o);$('#closeVehicleData').onclick=()=>{stopSim();o.remove()};$('#vehicleBike').onchange=e=>selectedBike=bikes.find(b=>b.id===e.target.value)||null;$('#startSim').onclick=toggleSim;renderSources();apply({})}
function gauge(id,label,value,unit){return `<article class="vehicleGauge"><small>${label}</small><strong id="vg-${id}">${value}</strong><span>${unit}</span><i id="vg-${id}-bar"></i></article>`}
function tile(id,label,value,unit){return `<article><small>${label}</small><strong id="vg-${id}">${value}</strong><span>${unit}</span></article>`}
function renderSources(){const box=$('#vehicleSourceList');if(!box)return;box.innerHTML=sources.map(s=>{const meta=sourceMeta[s.source_type]||[s.display_name,''];const blocked=s.source_type==='obdlink_lx';return `<article class="vehicleSourceCard ${s.status==='connected'?'connected':''}"><div><b>${esc(meta[0])}</b><small>${esc(meta[1])}</small></div><span>${esc(s.status||'disconnected')}</span><button data-source="${s.id}" ${blocked?'disabled':''}>${blocked?'BRIDGE REQUIRED':'SELECT'}</button></article>`}).join('');box.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>selectSource(b.dataset.source))}
async function selectSource(id){activeSource=sources.find(s=>s.id===id)||null;if(!activeSource)return;await supabase.from('vehicle_data_sources').update({status:'connected',last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);sources=sources.map(s=>({...s,status:s.id===id?'connected':s.status==='connected'?'disconnected':s.status}));$('#vehicleActiveSource').textContent=`Active: ${activeSource.display_name}`;renderSources()}
function toggleSim(){if(simTimer){stopSim();return}activeSource=sources.find(s=>s.source_type==='simulator')||null;$('#startSim').textContent='STOP TEST MODE';let t=0;simTimer=setInterval(()=>{t+=.25;const rpm=1800+Math.abs(Math.sin(t))*7600,speed=Math.max(0,(rpm-1500)/120),data={rpm,vehicle_speed_mph:speed,coolant_temp_f:170+Math.sin(t/4)*18,intake_temp_f:78+Math.sin(t/3)*7,battery_voltage:14.1+Math.sin(t)*.15,throttle_percent:8+Math.abs(Math.sin(t))*82,engine_load_percent:20+Math.abs(Math.sin(t*.8))*72,gear:Math.min(6,Math.max(1,Math.floor(speed/18)+1)),engine_hours:124.6,dtc_count:0};ingest(data,'Simulator')},1000);ingest({},'Simulator')}
function stopSim(){if(simTimer)clearInterval(simTimer);simTimer=null;const b=$('#startSim');if(b)b.textContent='START TEST MODE'}
function ingest(data,sourceName='Bridge'){telemetry={...telemetry,...data,recorded_at:new Date().toISOString()};apply(telemetry);const badge=$('#vehicleActiveSource');if(badge)badge.textContent=`Posted by: ${sourceName}`;window.dispatchEvent(new CustomEvent('moto-telemetry-updated',{detail:{...telemetry,source:sourceName}}));save(data)}
function apply(d){const map={rpm:['rpm',0],speed:['vehicle_speed_mph',0],coolant:['coolant_temp_f',0],intake:['intake_temp_f',0],voltage:['battery_voltage',1],throttle:['throttle_percent',0],load:['engine_load_percent',0],gear:['gear',0],hours:['engine_hours',1],dtc:['dtc_count',0]};for(const [id,[key,dec]] of Object.entries(map)){const e=$(`#vg-${id}`),v=Number(d[key]);if(e)e.textContent=Number.isFinite(v)?v.toFixed(dec):id==='rpm'||id==='speed'?'0':'--'}const rb=$('#vg-rpm-bar'),sb=$('#vg-speed-bar');if(rb)rb.style.setProperty('--pct',`${Math.min(100,(Number(d.rpm)||0)/100)}%`);if(sb)sb.style.setProperty('--pct',`${Math.min(100,(Number(d.vehicle_speed_mph)||0)/1.2)}%`)}
async function save(d){if(!session||!selectedBike||Date.now()-lastSaved<5000)return;lastSaved=Date.now();const rideId=JSON.parse(localStorage.getItem('motoActiveRide')||'null')?.id||null;await supabase.from('vehicle_telemetry_samples').insert({user_id:session.user.id,bike_id:selectedBike.id,session_id:rideId,source_id:activeSource?.id||null,rpm:d.rpm??null,vehicle_speed_mph:d.vehicle_speed_mph??null,coolant_temp_f:d.coolant_temp_f??null,intake_temp_f:d.intake_temp_f??null,battery_voltage:d.battery_voltage??null,throttle_percent:d.throttle_percent??null,engine_load_percent:d.engine_load_percent??null,gear:d.gear??null,engine_hours:d.engine_hours??null,dtc_count:d.dtc_count??null,raw:d})}
window.MotoTelemetryBridge={ingest:(payload,source='External bridge')=>ingest(payload,source),setSource:name=>{const s=sources.find(x=>x.display_name===name||x.source_type===name);if(s)selectSource(s.id)}};
new MutationObserver(()=>queueMicrotask(injectNav)).observe(document.body,{childList:true,subtree:true});load();